### ISSUE TITLE
Add `key` to matrix

### ISSUE THREAD

**Issue by pbielak** [iterative/dvc#10043]
The addition of `matrix` functionality simplified quite a lot for me. However, contrary to `foreach` stages, there is no `key` property available. I often find myself composing output paths using the parametrization fields.

Let me give an example – first, using foreach:

```yaml
train_model:
  foreach:
    backbone_A_dim_100:
      backbone: A
      dim: 100
   backbone_B_dim_100:
     backbone: B
     dim: 100
   backbone_A_dim_200:
     ....
  do:
    cmd: python train_model.py --backbone ${item.backbone} --dim ${item.dim}
    outs:
    - data/models/${key}/
```

This can be simplified into a `matrix` stage:

```yaml
train_model:
  matrix:
    backbone: ["A", "B"]
   dim: [100, 200]
  cmd: python train_model.py --backbone ${item.backbone} --dim ${item.dim}
  outs:
  - data/models/${item.backbone}_${item.dim}/
```

The output path is composed of both the `item.backbone` and `item.dim`, which in this simplified case might not be that problematic, but it becomes more demanding and error prone with more `matrix` parameters. An easier way would be to include the `key` of the `matrix` stage into the templating context, i.e.:

```yaml
train_model:
  matrix:
    backbone: ["A", "B"]
   dim: [100, 200]
  cmd: python train_model.py --backbone ${item.backbone} --dim ${item.dim}
  outs:
  - data/models/${key}/
```

I already implemented the requested functionality ~~and will link it in a moment.~~ – see [PR#10044](https://github.com/iterative/dvc/pull/10044)
