### ISSUE TITLE
Support Access of Dictionary Items in matrix-stages

### ISSUE THREAD

**Issue by mfakaehler** [iterative/dvc#10094]
When I work with matrix-stages I would like to use further parameters for each item, specified in the `params.yaml`
A prototpy-stage would look like
```
# dvc.yaml
stages:
  eval:
    matrix:
      model: ${models}
      testset: ${testsets}
   cmd: python src/eval_script.py --model ${item.model} --evalset ${item.evalset} --model-family ${item.model.family}
...
```
And the params.yaml would be:
```
# params.yaml
models:
  m1:
    family: b21
  m2: 
    family: x22
      
testsets: [evalA, evalB]
```

This is similar to foreach-stages, where you can access properties by calling ${item.property}
