### ISSUE TITLE
`dvc pull filename`: says "missing cache files" when trying to get data from an S3 remote

### ISSUE THREAD

**Issue by paulmueller** [iterative/dvc#10095]
# Bug Report

## Description

I have an S3 remote set-up with S3 credentials. The S3 remote was created originally with DVC version 2.x, which means there are files stored in the `XX/YYYYYY` pattern  and in the `files/md5/XX/YYYYYY` pattern. Recently, I created a .dvc file with the following content:

```

# This .dvc file was created by the hpc_pipeline_code package
outs:
- md5: 18486b05fd3d3ceb277656582c63a665
  size: 12181143901
  path: M001_data.rtdc

meta:
  sample: CD3_B220
  nevents: 496912
  date: 2023-11-14
  device: ZMDD-AcC-04682c-208b19
  dce_ppid_generation: UNKNOWN
  dce_ppid_background: UNKNOWN
  dce_ppid_segmenter: UNKNOWN
  dce_ppid_feature: UNKNOWN
  dce_ppid_gate: UNKNOWN
  dce_ppid_hash: no-pipeline-id-hash
```

As far as I understand, this is a valid .dvc file. The corresponding S3 resource is also there on an OpenStack swift S3-compatible storage:

![image](https://github.com/iterative/dvc/assets/2853022/65877554-1e3f-482b-b2a9-783d61e7691b)

However, when trying to pull the file via `dvc pull M001_data.rtdc`, I get the following error message:

```
dvc -vv pull M001_data.rtdc
Collecting                                                                                                                                                     |0.00 [00:03,    ?entry/s]
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
md5-dos2unix: 18486b05fd3d3ceb277656582c63a665                                                                                                                                           
Fetching
Building workspace index                                                                                                                                      |7.00 [00:00, 1.43kentry/s]
Comparing indexes                                                                                                                                              |8.00 [00:00,  377entry/s]
Applying changes                                                                                                                                               |1.00 [00:00,   359file/s]
M       /home/paul/trepos/hpc_pipeline_data/data_raw/hsmfs/RTDC/20231114_NS_mouse/lymphocytes/CD3_B220/M001_data.rtdc
1 file modified

```

### Reproduce

I have not tried to reproduce this issue. Could it have something to do with how DVC 2 stores data differently in a remote compared to DVC 3?

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.29.0 (pip)
-------------------------
Platform: Python 3.11.0rc1 on Linux-6.2.0-36-generic-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 2.20.0
	dvc_objects = 1.2.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.4.1
Supports:
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.161)
Config:
	Global: /home/paul/.config/dvc
	System: /etc/xdg/xdg-ubuntu/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/bed53b92440c5e220e8dbc19ffb6e72f

```

**Comment by pmrowla** [comment]
The .dvc file you generated will make DVC look for the file in the 2.x cache location (without the `files/md5` prefix). DVC files in 3.x have an additional `hash` field for outputs that did not exist in 2.x.

If the file in your remote is stored in the 3.x `files/md5` location, you need to generate a .dvc file like:
```
outs:
- md5: 18486b05fd3d3ceb277656582c63a665
  size: 12181143901
  path: M001_data.rtdc
  hash: md5
...
```

The presence of the `hash: md5` field is what makes DVC use the `files/<hash>` location in cache and remote storage.
