### ISSUE TITLE
Handle dvcfile paths consistently between run and repro

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#1025]
If I run:

```
dvc run -d code/script.py -d data/input.csv -o data/output.csv -f data/output.csv.dvc python code/script.py
```

The Dvcfile will contain:

```
cmd: python code/script.py
deps:
- md5: ....
  path: code/script.py
- md5: ...
  path: data/input.csv
md5: ...
outs:
- cache: true
  md5: ...
  path: data/output.csv
```

But if I run `dvc repro data/output.csv.dvc` it will fail because paths are not handled the same way. I guess the `-f` parameter in the `run` command is the problem, but the real culprit is perhaps the inconsistency in behavior between `run` and `repro`: one defaults to the CWD and the other to the Dvcfile directory. I believe it would be best to use CWD on both, or mutate the relative paths in the Dvcfile to reflect their relative path to the target directory instead of CWD.
