### ISSUE TITLE
repro: dvc.lock incompatible with linters if length of path causes a line break

### ISSUE THREAD

**Issue by observingClouds** [iterative/dvc#10257]
# Bug Report

## Description

Long paths for dependencies and outputs of a stage that cause a line break in dvc.lock files will have trailing whitespaces. These trailing whitespaces are an issue if linters like pre-commit are used and git itself also issues a warning.

### Reproduce

```
git init
dvc init
dvc stage add -n print --outs veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpathorfilename.txt "echo 'abc' > veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpathorfilename.txt"
dvc repro print
```

Leads to `dvc.lock` with additional whitespace after `path:` and `>`:
```yaml
schema: '2.0'
stages:
  print:
    cmd: echo 'abc' > 
      veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpathorfilename.txt
    outs:
    - path: 
        veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpathorfilename.txt
      hash: md5
      md5: 0bee89b07a248e27c83fc3d5951213c1
      size: 4
```

This let git complain when using `git add` with `warning: 2 lines add whitespace errors.` and also fails with linters, e.g. pre-commit linter `trailing-whitespace`

`.pre-commit-config.yaml`:
```yaml
default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
```

```bash
% pre-commit install
pre-commit installed at .git/hooks/pre-commit
% git add dvc.lock 
% git commit
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing dvc.lock
```

### Expected

I expected the lock file to not contain trailing whitespaces so that common linters work without any issues.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.40.1 (conda)
---------------------------
Platform: Python 3.12.1 on macOS-13.5-x86_64-i386-64bit
Subprojects:
        dvc_data = 3.7.0
        dvc_objects = 3.0.6
        dvc_render = 1.0.0
        dvc_task = 0.3.0
        scmrepo = 2.0.2
Supports:
        http (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.12.2, boto3 = 1.33.13)
Config:
        Global: /Users/haukeschulz/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s7s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s7s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/3c4a7de42b87f04fe56dc0ef7485507f
```

**Additional Information (if any):**
