### ISSUE TITLE
dvc.yaml - cmd bash variables not working inside curly brackets

### ISSUE THREAD

**Issue by DSchreyer** [iterative/dvc#10534]
# Bug Report
When trying to run a bash command within the `dvc.yaml` I cannot access the the bash variables with using curly brackets. Escaping only works when not using curly brackets.

## Description

The `dvc.yaml` looks like this:
```stages:
  03_02_testing:
    outs:
      - output
    cmd:
      - |
        bash << EOF
        mkdir output
        d=\$(date +"%Y%m%d%H%M")

        touch output/\${d}_test_curly_brackets
        touch output/\$d-normal
        EOF
```

The `$d` variable normally can be used but `${d}` does not work. See images

![image](https://github.com/user-attachments/assets/5c6a1b60-fc62-4dcf-bdd8-80be59d81b0f)

### Reproduce

Execute the command in an own `dvc.yaml`.

### Expected

That both `\$d` and `\${d}` return the same information.

**Comment by skshetry** [comment]
Hi. DVC does not support multi-line scripts, i.e. they are executed on line-by-line basis.

You can instead write it as follows:
```yaml
03_02_testing:
  outs:
    - output
  cmd:
    - |
      mkdir output
      d=$(date +"%Y%m%d%H%M") && touch output/$d_test_curly_brackets touch output/\$d-normal
```

or, as follows: 
```yaml
03_02_testing:
  outs:
    - output
  cmd:
    - mkdir output
    - d=$(date +"%Y%m%d%H%M") && touch output/$d_test_curly_brackets touch output/\$d-normal
```


Both are equivalent.
