### ISSUE TITLE
Optional vars files: dynamic DAGs

### ISSUE THREAD

**Issue by mike-grayhat** [iterative/dvc#10554]
I have quite unusual case where I rely on variable generation from the first stage of the pipeline. The problem is that on the first run it doesn't exist yet which in turn invalidates the whole yaml file.

```
vars:
  - items: {}
  - items.yaml # non-existent before the first run

stages:
  collect_items:
    ...
  process:
    foreach: ${items}
    do:
     ...
```

I don't see an easy way out of it (even hydra works only on experiment runs, not on general dvc repros) and an option to skip missing variables would help a lot.
