### ISSUE TITLE
repro: strange runs caching

### ISSUE THREAD

**Issue by ermolaev94** [iterative/dvc#10589]
# Bug Report

## Description

I noticed strange runs caching and can't understand how it works and how it should work.

Accoding to the documentation [here](https://dvc.org/doc/user-guide/pipelines/run-cache): "Every time you run a pipeline with DVC, it logs the unique signature of each stage run (in .dvc/cache/runs). If it never happened before, its command(s) are executed normally. Every subsequent time a stage runs under the same conditions, the previous results can be restored instantly — without wasting time or computing resources."

I noticed that sometimes my experiments run the same stages even they were already run some time ago and are available in a cache. So I created synthetic pipeline to demonstrate.

### Reproduce

Let's look on the following pipeline:

```
stages:
  gen:
    matrix:
      pair: [ {ds: ds1.txt, content: ds1_content }, {ds: ds2.txt, content: ds2_content }]
    cmd: >-
        python gen.py ${item.pair.ds} ${item.pair.content}
    outs:
      - ${item.pair.ds}
  train:
    cmd: >-
      python train.py -i ds1.txt ds2.txt --suffix "train" --out train.txt
    deps:
      - ds1.txt
      - ds2.txt
    outs:
      - train.txt
  complete:
    cmd: >-
      python complete.py train.txt complete.txt
    deps:
      - train.txt
    outs:
      - complete.txt
```

Then I run this pipeline:

```
$ dvc repro dvc.yaml
```

My files cache looks as following now:

```
$ find DVC_CACHE/files/ -type f
files/md5/bc/5bdc8aafe6e601c08feef1889f0dc5
files/md5/65/e23aa5c1d6964a4be0014aab856f0e
files/md5/a5/ac2161ecdd63ed48ded78fc9465e0b
files/md5/76/6e7c6f46a7ff58e79656b4d71527d2
```

while my runs cache looks as following:

```
$ find runs/ -type f -exec cat {} \;
cmd: python complete.py train.txt complete.txt
deps:
- path: train.txt
  hash: md5
  md5: 766e7c6f46a7ff58e79656b4d71527d2
  size: 27
outs:
- path: complete.txt
  hash: md5
  md5: bc5bdc8aafe6e601c08feef1889f0dc5
  size: 34
cmd: python train.py -i ds1.txt ds2.txt --suffix "train" --out train.txt
deps:
- path: ds1.txt
  hash: md5
  md5: a5ac2161ecdd63ed48ded78fc9465e0b
  size: 11
- path: ds2.txt
  hash: md5
  md5: 65e23aa5c1d6964a4be0014aab856f0e
  size: 11
outs:
- path: train.txt
  hash: md5
  md5: 766e7c6f46a7ff58e79656b4d71527d2
  size: 27
```

### Expected

I expected that each stage will be saved in a runs cache i.e. each stage can be reproduced if it was run before, but generation stages are lost.

It's interesting that adding new stage doesn't produce new run for generation, but produce for training with no dependency to the order of stages:

```
  gen_extra:
    matrix:
      pair: [ { ds: ds3.txt, content: ds3_content }]
    cmd: >-
      python gen.py ${item.pair.ds} ${item.pair.content}
    outs:
      - ${item.pair.ds}
  train_extra:
    cmd: >-
      python train.py -i ds3.txt --suffix "train" --out train_extra.txt
    deps:
      - ds3.txt
    outs:
      - train_extra.txt
```

```
$ find runs/ -type f -exec cat {} \;                                                              
cmd: python complete.py train.txt complete.txt                                                                                                              
deps:                                                                                                                                                       
- path: train.txt                                                                                                                                           
  hash: md5                                                                                                                                                 
  md5: 766e7c6f46a7ff58e79656b4d71527d2                                                                                                                     
  size: 27                                                                                                                                                  
outs:                                                                                                                                                       
- path: complete.txt                                                                                                                                        
  hash: md5
  md5: bc5bdc8aafe6e601c08feef1889f0dc5 
  size: 34
cmd: python train.py -i ds3.txt --suffix "train" --out train_extra.txt
deps:
- path: ds3.txt
  hash: md5
  md5: 3227d1f7a4742bc083c7398c6e8086dc 
  size: 11
outs:
- path: train_extra.txt
  hash: md5
  md5: 72d835b3f745dd59c520724577cca256 
  size: 16
cmd: python train.py -i ds1.txt ds2.txt --suffix "train" --out train.txt
deps:
- path: ds1.txt
  hash: md5
  md5: a5ac2161ecdd63ed48ded78fc9465e0b 
  size: 11
- path: ds2.txt
  hash: md5
  md5: 65e23aa5c1d6964a4be0014aab856f0e 
  size: 11
outs:
- path: train.txt
  hash: md5
  md5: 766e7c6f46a7ff58e79656b4d71527d2 
  size: 27
```

Also, I suspected that problem with the "matrix" construction, but replacing `gen_extra` with the same stage without `matrix` didn't help.

Also, I expected, that if I remove dvc.lock file, but cache stores runs that were in this lock file, dvc will be able to pull them from cache instead of runing, but it's not. I checked, hashes are the same - both for files & commands.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.55.2 (pip)
-------------------------
Platform: Python 3.10.14 on Linux-6.8.0-31-generic-x86_64-with-glibc2.39
Subprojects:
        dvc_data = 3.16.6
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.4.0
        scmrepo = 3.3.7
Supports:
        gdrive (pydrive2 = 1.20.0),
        http (aiohttp = 3.10.6, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.10.6, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2024.9.0, boto3 = 1.35.23)
Config:
        Global: /home/ermolaev/.config/dvc
        System: /etc/xdg/xdg-ubuntu/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p7
Caches: local
Remotes: gdrive, gdrive, gdrive, s3
Workspace directory: ext4 on /dev/nvme0n1p7
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2fc3667ce02f8444dcf57de175d67d76
```

**Additional Information (if any):**

So, now for me it looks like:
- currently run-cache does not work as described in the doc
- caching of runs is performed only with `.lock` files, `repro` or `exp run` don't try to find command in the cache
- caching of runs doesn't look stable, some stages are missing without reason that I can catch

I provide my scripts & data for tests in the attached archive.
[dvc_stand.zip](https://github.com/user-attachments/files/17416752/dvc_stand.zip)
