### ISSUE TITLE
Transitive dependencies

### ISSUE THREAD

**Issue by m-legrand** [iterative/dvc#10599]
Let's imagine I have a project structured like this:

```
pyproject.toml
src/
    model.py  # uses packages defined in pyproject.toml
scripts/
    make_abc.py  # imports src.model
```

And that I have a single stage

```yaml
stages:
  stage_name:
    cmd: python abc.py
    deps:
      - make_abc.py
    outs:
      - data/abc.txt
```

Even if I don't change `make_abc.py`, I'd like to invalidate `abc.csv` whenever I update some dependencies (in `pyproject.toml`) or change the source code (in `src/`).
One solution would be to add all of the above as dependencies to all my stages (which I do at the moment), but it makes the `dvc.yaml` quite big and repetitive.

It would be great to say once and for all that every time something is dependent on a python script in the `scripts/` folder, it's also really dependent on `pyproject.toml` and `src/`.
Maybe something like:

```yaml
dependencies:
    scripts/*.py:
        - pyproject.toml
        - src/**/*.py
```
