### ISSUE TITLE
dvc pull hangs indefinitely

### ISSUE THREAD

**Issue by dom-nura** [iterative/dvc#10625]
# Bug Report

dvc pull hangs indefinitely

windows 11, 
python 3.12, 
dvc 3.56.0

```
mkdir c::\tmp\foo
cd c:\tmp\foo
dvc init --no-scm
```
create a .dvc file:
```
md5: 18209fb515862e1af194d959306d8932
frozen: true
deps:
- path: sdxl_vae.safetensors
  repo:
    url: https://huggingface.co/stabilityai/sdxl-vae
    rev_lock: 6f5909a7e596173e25d4e97b07fd19cdf9611c76
outs:
- hash: md5
  path: sdxl_vae.safetensors
```

dvc pull

result: hangs forever.
