### ISSUE TITLE
How to manage repetitive `dvc run` commands (like unpacking of many zip files)?

### ISSUE THREAD

**Issue by sotte** [iterative/dvc#1119]
Assume you download a bunch of zips.
```
data/
  download/
    file1.zip
    ...
    fileN.zip
```

 Now you need to unpack the files to lets say `data/unpacked/file{i}`. Something like this:
```
data/
  unpacked/
    file1/
    ...
    fileN/
```
When I use a Makefile to manage my pipeline I would write a simple rule for unpacking the zips and put them into their target folders. What is the best approach to do something like this with DVC? Right now I just type a bunch of `dvc run` commands but that does not scale well.

**Comment by efiop** [comment]
Hi @sotte !

Very interesting scenario! We have been thinking about introducing a build matrix https://github.com/iterative/dvc/issues/1018 to handle a bit different scenario, but i think in your case it could be useful as well. For example, Dvcfile placed in `data/unpacked` could look like:

```
cmd: tar -xf {deps} -C {outs}
matrix:
   - deps:
        - path: file1.tgz
      outs:
        - path: file1
   - deps:
        - path: file2.tgz
     outs:
        - path: file2
    ....
```

Would something like that suit you? Please feel free to share any thoughts or suggestions.

Thanks,
Ruslan

**Comment by sotte** [comment]
That looks quite nice!
Wildcards would be nice. Something like this:
```
matrix:
  - deps:
    -path: file*.csv.tgz
    outs:
    - path: file*.csv
```
But I guess the deps and outs have to be specified explicitly.
