### ISSUE TITLE
run: Warn about duplicated arguments

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1255]
Summary
-------------
You can specify the same output more than one type without any hint.
It would be great to have at least a warning, helping the user with potential typos.

Expected behavior
------------------------
```bash
dvc run \
  --file double-output.dvc \
  --outs hello.txt \
  --outs hello.txt \
  'echo "hello" > hello.txt'

Warning: Output 'hello.txt' was specified more than one time
```

`cat double-output.dvc`:
```
cmd: echo "hello" > hello.txt
md5: ec93debb48f6f21a03f5dbe10fa0a6c2
outs:
- cache: true
  md5: b1946ac92492d2347c6235b4d2611184
  path: hello.txt
```

Actual behavior
--------------------
```bash
dvc run \
  --file double-output.dvc \
  --outs hello.txt \
  --outs hello.txt \
  'echo "hello" > hello.txt'
```

`cat double-output.dvc`:
```
cmd: echo "hello" > hello.txt
md5: ec93debb48f6f21a03f5dbe10fa0a6c2
outs:
- cache: true
  md5: b1946ac92492d2347c6235b4d2611184
  path: hello.txt
- cache: true
  md5: b1946ac92492d2347c6235b4d2611184
  path: hello.txt
```

System configuration
----------------------------
DVC version: `0.19.12`
Installation: `Arch Linux AUR package`
