### ISSUE TITLE
dvc: optional cache file encryption

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1317]
E.g. we would push encrypted files to remote for improved security.

**Comment by mroutis** [comment]
From the Discord channel:

> The basic idea would be to be able to store data and models on an untrusted cloud provider :innocent:  while stile being able to share with others or work on it locally by using a shared decryption key among members

**Comment by aurelien-clu** [comment]
# Description
`dvc` enables us to share data and models on a `remote` server / data storage service.
**Such service may not always be trusted for our (or our clients) data and models.**

This would be as follows:
- pushing encrypts automatically data
- fetching decrypts data (at the cost of using twice the space temporarily at best or all the time at worst)
- local data is always un-encrypted (so it is usable)

The encryption key would have to be shared among project members.

# Configuration example
```bash
dvc remote add [...] --encryption-method AES-256 --encryption-key XYZ
```

**Comment by aurelien-clu** [comment]
Example of `dvc` file ([source](https://dvc.org/doc/user-guide/dvc-file-format):

```yaml
cmd: python cmd.py input.data output.data metrics.json
    deps:
    - md5: da2259ee7c12ace6db43644aef2b754c
      path: cmd.py
      md5_encrypted: [...]
    - md5: e309de87b02312e746ec5a500844ce77
      path: input.data
      md5_encrypted: [...]
    md5: 521ac615cfc7323604059d81d052ce00 # <= this hash is about this file?
    outs:
    - cache: true
      md5: 70f3c9157e3b92a6d2c93eb51439f822
      md5_encrypted: [...]
      metric: false
      path: output.data
    - cache: false
      md5: d7a82c3cdfd45c4ace13484a931fc526
      md5_encrypted: [...]
      metric:
        type: json
        xpath: AUC
      path: metrics.json
   locked: True
```
