### ISSUE TITLE
checkout: use more than one core to check checksum when checking into another branch

### ISSUE THREAD

**Issue by IamGianluca** [iterative/dvc#1331]
I'm working with a few million images that sum up to ~11GB. When I run a `dvc checkout`, `dvc` checks that files haven't changed, and if they did, it computes the new md5. This, however, could take more than 15 minutes when we are working with lots of images.

`htop` shows that during this process only one core is being used. Perhaps we could speed up the process using multiprocessing and distributing the check of such files across all available cores in the machine.

**Comment by IamGianluca** [comment]
Thank you @efiop, I really appreciate it!

I'm still seeing long execution times (in the order of hours) with `checkout` and `gc` operations when dealing with lots of image files. I think this is a fairly common use case, unfortunately ― at least for me at work and in Kaggle competitions :-)

**Comment by efiop** [comment]
Hi @IamGianluca !

Thanks for the feedback! We've received a report about a similar problem https://github.com/iterative/dvc/issues/1340, that makes me think that it is a regression, we will investigate shortly.

Thanks,
Ruslan

**Comment by efiop** [comment]
@IamGianluca Hi! Could you please tell how you store and work with those numbers of files? Is it a single directory that you add as a whole to dvc?

**Comment by IamGianluca** [comment]
@efiop Hi! I have an archive that I've unpacked with a command like `dvc run -d data.tgz -o data tar -xvf data.tgz`. To give you an example:

The first step in my pipeline unzip a zip archive ― I could have done it using `unzip` to be honest, no need to have a script for that.
```
cmd: python src/unzip.py
deps:
- md5: 1f3abde732c38f588078a0b5348dd068
  path: src/unzip.py
- md5: 33b493c035c7f57987e45c03771e4881
  path: data/train_simplified.zip
md5: c0e0419d1ba738b2d18c6a258e70dde4
outs:
- cache: true
  md5: 7912198d4c1266ec90f483ec9a5ab55d.dir
  path: data/raw_csv
```

Then I've converted some csv files to jpg...
```
cmd: python src/extract.py --sz 64 --pct 0.01
deps:
- md5: 898ef2313cbf76d8009eea978deda791
  path: src/extract.py
- md5: 7912198d4c1266ec90f483ec9a5ab55d.dir
  path: data/raw_csv
md5: fb6962dd27be359923646e56215038b8
outs:
- cache: true
  md5: 88e192f334ffa0cbf1da667431192219.dir
  path: data/train-64
- cache: true
  md5: d247f2f8829d1761d0f156d431cdb81d.dir
  path: data/test-64
```

Then, trained a classifier...
```
cmd: python src/train.py
deps:
- md5: 3b282c32adaac1e7cbc21b4ef956b9e0
  path: src/train.py
- md5: 88e192f334ffa0cbf1da667431192219.dir
  path: data/train-64
- md5: d247f2f8829d1761d0f156d431cdb81d.dir
  path: data/test-64
md5: 1a967756e126d749a1a9c2fe50137026
outs:
- cache: true
  md5: 7a6578b1bbceb968348fd7b6e2724d2e
  path: models/stage1.pth
```

And so on...
