### ISSUE TITLE
"Error: Failed to pull data from the cloud" when pulled data is a directory

### ISSUE THREAD

**Issue by guerrapin** [iterative/dvc#1376]
When pulling data from remote storage, I execute the following command:
`dvc pull train.dvc`

with content of the file:
_train.dvc_
```
cmd: python train.py
deps:
- md5: 454410a0e96e7c268914287865e94bbc
  path: data/dataset.csv
md5: c1b4f121d34f4dbd426089bbbec26d3c
outs:
- cache: true
  md5: 9f1f44cc23e76e794f7423d4a76147a3.dir
  path: outputs/models/
```

Then obtain the following error:
```
[##############################] 100% Collecting information
[##############################] 100% outputs/models
[##############################] 100% Collecting information
(1/3): [##############################] 100% outputs/models/task_a.pkl
(2/3): [##############################] 100% outputs/models/task_b.pkl
(3/3): [##############################] 100% outputs/models/task_c.pkl
Checking out ' outputs/models' with cache '9f1f44cc23e76e794f7423d4a76147a3.dir'.
Linking directory 'outputs/models'.
Error: Failed to pull data from the cloud: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

It seems that it happens because of the output of `train.dvc` is a directory. It works fine when it's a file.

some infos:
dvc==0.21.0 installed with pip
macOS 10.14
