### ISSUE TITLE
local: don't resolve 'remote://myremote' paths when saving to dvc file

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1451]
```
$ dvc remote add mylocal ~/src/TMP/
$ dvc add remote://mylocal/
```
will produce
```
md5: 64cb9070ffe56b9694d24be5728e99e3
outs:
- cache: true
  md5: b5a280f8252682ff4ddd642ea39b428e.dir
  path: /Users/dmitry/src/TMP
```

instead of 

```
md5: 64cb9070ffe56b9694d24be5728e99e3
outs:
- cache: true
  md5: b5a280f8252682ff4ddd642ea39b428e.dir
  path: remote://mylocal/
```
