### ISSUE TITLE
stage: Support a way to specify paths relative to the dvc root

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1493]
Instead of having something like:
```yaml
- path: ../../../data/stories.json.gz
```

Support the following syntax:
```yaml
- path: $(dvc root)/data/stories.json.gz
```

---

Related: #779

**Comment by dmpetrov** [comment]
We can store only full-dvc-path (relative to root) in all dvc files. So, `--cwd` and `dvc root` won't be needed in many cases.

**Comment by efiop** [comment]
But it doesn't make sense to do something like `../../.../path/to/something` unless you are trying to hide dvc files somwhere. Currently paths in dvc files are realtive to the dvc file location, not dvc root.

**Comment by efiop** [comment]
This is feature is related to dynamic path resolution in general, alongside with wildcards, parametrization and stuff like that.

**Comment by dmpetrov** [comment]
Oh, I was thinking about this issue in the context of `cwd` in dvc-files. I didn't mean `../../.../path/to/something` I meant `path/to/something` if dvc-file is in this dir. It comes down to the question - why don't we save cwd in all dvc-files. But it seems like a different scenario.

**Comment by efiop** [comment]
We will save it, in https://github.com/iterative/dvc/issues/1092 :)

**Comment by shcheklein** [comment]
Is it still relevant (and in what case?), considering the change we made with `wdir` and `-f` recently?

**Comment by mroutis** [comment]
@shcheklein , I don't think is relevant anymore, if so, feel free to reopen with more details.

**Comment by joostmeulenbeld** [comment]
@shcheklein I have the same feature request as this issue's OP. You mentioned `wdir` and `-f`. `wdir` is the solution we currently use, but it's not ideal (explained below). I guess `-f` is an option to a command, but we write our `dvc.yaml` files by hand, so that doesn't help either. Can this issue be reopened or should I open a new issue? Also, this issue is from 2019 so if in the meantime a new solution has become available please say so.

Example workspace structure:

- src/
  - script.py
- data/
  - project1/
    - input/
      - input.txt
    - dvc.yaml

Where `data/project1/dvc.yaml` contains:
```yaml
stages:
  process-data:
    deps:
      - ../../src/script.py
      - input/input.txt
    outs:
      - output/output.txt
    cmd:
      - python $DVC_ROOT/src/script.py input/input.txt output/output.txt
```

In the `cmd` part, I can reference `$DVC_ROOT`, but in the `deps` I have to use relative paths since there, `$DVC_ROOT` is not defined. AFAIK there are two solutions to this problem, both suboptimal:
- As shown above with `../../src/script.py` - for deeper workspaces counting the number of `../` becomes inconvenient, and when rearranging the project folders within `data` you have to update those number of `../`s. This makes refactoring more effort.
- Using `wdir: ../..` in every stage is a solution, but requires **all** paths to be written with respect to the project root. This leads to very long paths for deep folder structures (writing `data/some_product/development/some_project/preprocess` everywhere becomes old very quickly...). It also makes moving/renaming folders within the workspace a pain since it requires updating all paths, and copying parts of code between `dvc.yaml` files is also a hassle for the same reason.

**Comment by joostmeulenbeld** [comment]
@shcheklein  Can this issue be reopened or should I open a new issue?

**Comment by shcheklein** [comment]
@joostmeulenbeld how about using [templating](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#templating) in `dvc.yaml`? can you try to introduce a param / var that would contain `data/project1` for example? - thus reducing duplication?

also, you could probably even try to introduce a var that has `dvc root` in it.

**Comment by joostmeulenbeld** [comment]
@shcheklein Thanks, we switched to using your approach. 

Now our DVC files look like this, which is better than the two options I had before. Moving/copying DVC files around requires only chaning the `repo` variable value in one place in each dvc (if it needs to change at all - quite often it doesn't have to).

```yaml
vars:
  - repo: ../..

stages:
  process-data:
    deps:
      - ${repo}/src/script.py
      - input/input.txt
    outs:
      - output/output.txt
    cmd:
      - python ${repo}/src/script.py input/input.txt output/output.txt
```
