### ISSUE TITLE
move: path doesn't match wdir

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1683]
`dvc --version: 0.30.1+97c099`

**Steps to reproduce**:

```bash
mkdir data/
echo "foo" > data/foo
echo "bar" > data/bar
dvc add -R data
find data -type f -not -iwholename '*.dvc' | xargs -I {} dvc move {} data/raw
```

`foo` stage file results in:
```yaml
md5: 3bccbf004063977442029334c3448687
outs:
- cache: true
  md5: d3b07384d113edec49eaa6238ad5ff00
  metric: false
  path: foo
wdir: .
```

Where it should be `path: data/raw/foo` or change the `wdir` to `../../`
