### ISSUE TITLE
metrics: deprecate hcsv and htsv in favor of "header: true"

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1731]
`.hcsv` and `.htsv` aren't standard well-known file extensions, and it is hard to tell what's going on without reading the documentation:

> htsv and hcsv are tsv and csv but the values in the first row of the file will be used as the field names and can be used to address columns in the --xpath option.

```yaml
outs:
  - path: metrics.tsv
    md5: 294b631cd2c4ccf615dfa4f6833d12e0
    cache: false
    metric:
      type: tsv
      header: true
```

This would require to add the following flag: `dvc metrics modify --header file.csv`
