### ISSUE TITLE
stage: preserve comments and don't add default fields removed by user

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1799]
```
md5: adbb969c66c0fe9449b17a57afcd9531
outs:
- cache: true
  md5: c157a79031e1c40f85931829bc5fc552
  metric: false
  path: file
  persist: false
wdir: .
```
