### ISSUE TITLE
dvc status regression after 0.33.1 release

### ISSUE THREAD

**Issue by qchenevier** [iterative/dvc#1828]
I'm using OSX/Darwin.

All the checksums in my pipelines have changed starting from version 0.33.1.

Bug very similar to https://github.com/iterative/dvc/issues/1680

E.g: With a single file added with `dvc add helico_val.h5.dvc`:

###### dvc 0.32.1: OK ✅
```
$ pip install dvc==0.32.1
$ dvc status --show-checksums helico_val.h5.dvc
+-------------------------------------------+
|                                           |
|     Update available 0.32.1 -> 0.34.1     |
|       Run pip install dvc --upgrade       |
|                                           |
+-------------------------------------------+

Pipeline is up to date. Nothing to reproduce.
```

##### dvc 0.33.1: NOK ❌
```
$ pip install dvc==0.33.1
$ dvc status --show-checksums helico_val.h5.dvc
+-------------------------------------------+
|                                           |
|     Update available 0.33.1 -> 0.34.1     |
|       Run pip install dvc --upgrade       |
|                                           |
+-------------------------------------------+

helico_val.h5.dvc:
	changed checksum
```

##### dvc 0.34.1: NOK ❌
```
$ pip install dvc==0.34.1
$ dvc status --show-checksums helico_val.h5.dvc
helico_val.h5.dvc:
	changed checksum
```

I also did the check by computing the md5 sum with `md5 helico_val.h5` and it seems that the right version of the md5 is for version <= 0.32.1

**Comment by efiop** [comment]
Hi @qchenevier !

Could you show `helico_val.h5.dvc` please?

**Comment by efiop** [comment]
@qchenevier Also, mind showing `dvc status helico_val.h5.dvc -v` logs for those versions?

**Comment by efiop** [comment]
Ok, was able to reproduce
```
#!/bin/bash

set -e
set -x

rm -rf myrepo
mkdir myrepo
cd myrepo
git init

pip uninstall -y dvc
pip install dvc==0.32.1

dvc init

echo foo > foo

dvc add foo

dvc status

pip install dvc==0.33.1

dvc status
```

**Comment by efiop** [comment]
The difference in foo.dvc generated by 0.32.1 and 0.33.1:

032.0
```
md5: 1505491fb04120d56bc84064355b17e1
outs:
- cache: true
  md5: d3b07384d113edec49eaa6238ad5ff00
  metric: false
  path: foo
wdir: .
```

0.33.1
```
md5: 5997af024eb327f28cd9b4729d2d32e2
outs:
- cache: true
  md5: d3b07384d113edec49eaa6238ad5ff00
  metric: false
  path: foo
  persist: false
wdir: .
```

so the problem is that we don't exclude default `persist: false` value when computing checksum.
