### ISSUE TITLE
stage: ruamel.yaml loads md5 as inf

### ISSUE THREAD

**Issue by felkost** [iterative/dvc#2024]
** information about your setup**
DVC version(0.40.3 or 0.40.4), Platform and method of installation (pip), DEB(Linux Mint), 

 I've just upgraded  from 0.35 and suddenly got that error:
![image](https://user-images.githubusercontent.com/15686832/58030764-c88aee80-7b27-11e9-9ef1-1821fc2e93de.png)

**Comment by efiop** [comment]
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/580049728910262303

**Comment by efiop** [comment]
```
diff --git a/dvc/utils/stage.py b/dvc/utils/stage.py
index e88f3c2..178c5c8 100644
--- a/dvc/utils/stage.py
+++ b/dvc/utils/stage.py
@@ -13,8 +13,8 @@ def load_stage_file(path):

 def load_stage_fd(fd, path):
     try:
-        yaml = YAML()
-        return yaml.load(fd) or {}
+        import yaml
+        return yaml.safe_load(fd)
     except YAMLError as exc:
         raise StageFileCorruptedError(path, cause=exc)
```
looks like a ruamel issue. Replacing it with pyyaml fixes it. Also,

**Comment by efiop** [comment]
Looks like for some reason this specific value `md5: 4661e177303623051910790245640135` is triggering the bug:
```
md5: 4661e177303623051910790245640135  
outs:                                  
- cache: true                          
  md5: 90104d9e83cfb825cf45507e90aadd27
  metric: false                        
  path: dvc.ico                        

```
