### ISSUE TITLE
Support declaring environment variables in DVC file

### ISSUE THREAD

**Issue by robogeek** [iterative/dvc#2042]
Obviously some command-line tool configuration is set using environment variables.  DVC does not support setting environment variables in a DVC file.  Neither [DVC file reference](https://dvc.org/doc/user-guide/dvc-file-format) nor [dvc run command reference](https://dvc.org/doc/commands-reference/run) show anything about setting an environment variable.

As to how it should be visible to the users:

* `dvc run -e VARIABLE=value` -- support setting this option multiple times
* In the top level of a DVC file have an `env` tag, like so:

```yaml
cmd: echo This is a command
env:
    - VARIABLE_NAME=value
    - VARIABLE_NAME2=value
    - VARIABLE_NAME3=value
```

OR

```yaml
cmd: echo This is a command
env:
    VARIABLE_NAME: value
    VARIABLE_NAME2: value
    VARIABLE_NAME3: value
```

For comparison, this is exactly how environment variables are defined in a Docker Compose file: https://docs.docker.com/compose/compose-file/#environment
