### ISSUE TITLE
status: granular output for directories

### ISSUE THREAD

**Issue by MikkelAntonsen** [iterative/dvc#2180]
Imagine dvc tracking a directory full of images and files containing labels.

If I delete/change/update a label or image, dvc will tell me that something in the directory has changed, but not exactly what. It would be nice is dvc status could be made more granular, returning something like 

```
data.dvc:
    outputs:
        data/foo: new
        data/bar: deleted
```

instead of 

```
data.dvc:
	changed outs:
		modified:           data
```

as it is today.

Thanks:)
