### ISSUE TITLE
stage: marked as changed after modifying meta attribute 

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2209]
`DVC version: 0.50.1`

The meta attribute should not affect the reproduction of a stage.

### Steps to reproduce

1. Save a DVC-file (_capitalize.dvc_) with the following content:

```yaml
cmd: cat input.txt | tr a-z A-Z > output.txt

deps:
- path: input.txt

outs:
- path: output.txt

meta:
  author: mroutis
```

2. Create _input.txt_: `echo hello > input.txt`

3. Reproduce it: `dvc repro capitalize.dvc`

4. Add another key to meta:
```diff
meta:
  author: mroutis
+ issue: 2209
```
5. Reproduce it again: `dvc repro capitalize.dvc`
