### ISSUE TITLE
stage: don't add default fields removed by user

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2210]
`DVC version: 0.50.1`

It was supposed to be solved as part of #1799 

### Steps to reproduce

1. Save a DVC-file (_capitalize.dvc_) with the following content:

```yaml
cmd: cat input.txt | tr a-z A-Z > output.txt

deps:
- path: input.txt

outs:
- path: output.txt

meta:
  author: mroutis
```

2. Create _input.txt_: `echo hello > input.txt`

3. Reproduce it: `dvc repro capitalize.dvc`

```yaml
cmd: cat input.txt | tr a-z A-Z > output.txt

deps:
- path: input.txt

  md5: b1946ac92492d2347c6235b4d2611184
outs:
- path: output.txt

  md5: 0084467710d2fc9d8a306e14efbe6d0f
  cache: true
  metric: false
  persist: false
meta:
  author: me

md5: 911cf77624b3dfc4c4f898dac3b16719
wdir: .
```
