### ISSUE TITLE
pipeline show doesn't display dependencies

### ISSUE THREAD

**Issue by eliorc** [iterative/dvc#2341]
**Setup** - Running on version 0.53.2, inside of a docker container, where container runs on Ubuntu 16.04 and the host also

I have created a file using the standard `dvc run -d ... -O ...` (notice I do opt for `-O` since the output will be versioned in git), and the resulting `.dvc` file has the following contents

```
md5: 40da64f2840947559287922675c52006
cmd: python scripts/create_dataset.py /opt/data/dataset.csv
wdir: ../../../..
deps:
- md5: 6fb9ea7998edffee57c6affc3cedfb1f
  path: /opt/data/data1.csv
- md5: 6a2dbe6e3362e871c8e019b628a3928b.dir
  path: /opt/data/data2.csv
- md5: 9968f15e5d0e52fff7dd8228322227b4.dir
  path: /opt/data/data_dir
- md5: 87cb2324a47914d995c9110c30fcaa0f
  path: /opt/scripts/create_dataset.py
outs:
- md5: 62ef5271e749f086ef0dc19aee6d279a
  path: /opt/data/dataset.csv
  cache: false
  metric: false
  persist: false
```
Also, the files specified in `-d` are not DVC versioned, they are also tracked normally in git.

The problem is, that when I try to visualize, all I see is the last step, disregarding the dependencies, so the output of `dvc pipeline show --ascii /opt/data/dataset.csv.dvc`

```
+--------------------------------------------------+
| data/dataset.csv.dvc |
+--------------------------------------------------+
```

And none of the dependencies are present - Why aren't the dependencies showing up?

(filenames and paths have been changed for privacy reasons, so if the `wdir` doesn't add up, it's ok)
