### ISSUE TITLE
dvc run : possible bug with deeply nested dependencies

### ISSUE THREAD

**Issue by tdeboissiere** [iterative/dvc#2483]
**Please provide information about your setup**

ubuntu 18.05, dvc==0.59.2, `pip` install with miniconda python 3.7

```bash
#!/bin/bash

set -x
set -e

rm -rf dvc_test
mkdir dvc_test && cd dvc_test
mkdir scripts
mkdir -p data/recommended/dataset1/dataset1_proc
echo bar > data/recommended/dataset1/v1.txt
git init
dvc init
echo -e "import sys\
\nwith open(sys.argv[1], 'w') as f: f.write(sys.argv[2])" > scripts/script.py

# Run works
dvc run -y \
    -w $PWD/data/recommended/dataset1/dataset1_proc\
    -f ./data/recommended/dataset1/dataset1_proc/v1.dvc\
    -d ../../../../scripts/script.py \
    -o v1 \
    "mkdir v1 && python ../../../../scripts/script.py v1/v1.txt proc_data"

# Inspecting v1.dvc shows that the script.py dependency is missing on ../
cat data/recommended/dataset1/dataset1_proc/v1.dvc

# Because of the, repro does not work
dvc repro data/recommended/dataset1/dataset1_proc/v1.dvc
```

**Comment by efiop** [comment]
Hi @tdeboissiere ! Are you sure this is the same command? I see you've specified `-w` in `dvc run` ,but there is no `wdir: ` field in the dvc file.

**Comment by tdeboissiere** [comment]
@efiop : Sorry, this was run with version 0.57 (which still logged `wdir` in the `.dvc` file even if it's the default `.`).

If you run it with 0.59, `wdir` is absent indeed

**Comment by efiop** [comment]
@tdeboissiere Sorry, I just missed the `-f` option in your command and was surprised about `wdir` missing. But it makes sense now.

Ok, so running your reproduction script I get:
```
+ cat data/recommended/dataset1/dataset1_proc/v1.dvc                      
md5: 1f92bcfcf1ef2766da1ea3c373289dca                                     
cmd: mkdir v1 && python ../../../../scripts/script.py v1/v1.txt proc_data 
deps:                                                                     
- md5: 791b9c74b1d9308a3226b93a36689dad                                   
  path: ../../../../scripts/script.py                                     
outs:                                                                     
- md5: 188ed6cb603658d01ef7ba8fb7c434fe.dir                               
  path: v1                                                                
  cache: true                                                             
  metric: false                                                           
  persist: false                                                          
+ dvc repro data/recommended/dataset1/dataset1_proc/v1.dvc                
Stage 'data/recommended/dataset1/dataset1_proc/v1.dvc' didn't change.     
Data and pipelines are up to date.                                        
```

which has correct path in the dvcfile and `dvc repro` reports that there is nothing to reproduce, so it sees all the dependencies.
