### ISSUE TITLE
dvc get unable to find DVC-file error

### ISSUE THREAD

**Issue by ValdarT** [iterative/dvc#2725]
I get an "unable to find DVC-file" error when trying to download a file from a private repository.

This is the command:
```
dvc get https://github.com/private_repo/my_repo/ model.pkl --rev branchname
```

This is the error:
```
ERROR: failed to get 'model.pkl' from 'https://github.com/private_repo/my_repo/' - unable to find DVC-file with output 'model.pkl'
```

This is the content of the `.dvc` file with the `model.pkl` output:
```
cmd: python train.py
outs:
- path: resources/model.pkl
  metric: false
  cache: true
  persist: false
  md5: a933f14a1466d27382a8a265eacd3034
- path: resources/evaluation.json
  metric: true
  cache: false
  persist: false
  md5: 286ea699ee07c4de3a689d48fd5e677b
deps:
- path: resources/X_train.pkl
  md5: e8f9fecdab4411d6a5ad4b09cc6b7821
- path: resources/y_train.pkl
  md5: 107fb604950f2099f892dc3a5898f50b
- path: resources/X_test.pkl
  md5: 3d00a8e4aab1670398757e2c76850f8d
- path: resources/y_test.pkl
  md5: b249173c50595c1f9663f40a057309e8
md5: 91f945a0209e673487e61637089aaab4
```
The path of the above .dvc file in the repo is: `my_repo/my_service/service_train.dvc`

System info (dvc installed with conda):
```
DVC version: 0.66.3
Python version: 2.7.15
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
```

Any ideas regarding the possible reasons behind the error would be highly appreciated.
