### ISSUE TITLE
Unclear dependencies conflict when installing from conda-forge

### ISSUE THREAD

**Issue by drorata** [iterative/dvc#3643]
I have a `conda` environment defined by:

```yml
name: my_env
channels:
    - conda-forge
    - plotly
dependencies:
    - python=3.8
    - pip
    - pytest
    - "pandas<2.0"
    - "matplotlib<4.0"
    - "scikit-learn<0.23"
    - "pymc3<4.0"
    - mkl-service
    - "python-graphviz<0.14"
    - pydot
    - "bidict<0.20"
    - tqdm
    - plotly=4.6.0
    # - "dvc<1.0"
    - pip:
        - pgmpy==0.1.9
        - streamlit
```

Once uncommenting the `dvc` dependency, I get messages like:

```
Found conflicts! Looking for incompatible packages
```

After about 30 minutes I terminated the process and now wondering why is it happening and what's the best approach to add `dvc` to this environment. Hinted by #2782 I tried to remove `tqdm` from the dependencies and add `dvc`, but conflicts appeared again. Any ideas?

This happened on
* macOS 10.15.4
*  conda version 4.8.3

**NB** I moved `dvc` to the `pip` section and was able to update the environment. Still it would be nice to have it install using `conda(-forge)`.
