### ISSUE TITLE
`fill_from_lock` called when `stage.cmd_chaged == True`

### ISSUE THREAD

**Issue by tall-josh** [iterative/dvc#3918]
## Bug Report

Using mutlistage dvc file. `dvc repro` for the fist time on `dvc.yaml` works no issue. However, if I change the `cmd` in `dvc.yaml` the new command is not run, instead dvc says `Stage 'st2' is cached` (interestingly it omits `skipping`). After doing some digging I noticed this
 
https://github.com/iterative/dvc/blob/master/dvc/stage/loader.py#L178

Is using the `lock_data` correct? If the `cmd` has changed, shouldn't we use the `stage_data`?

### Please provide information about your setup

`dvc.yaml`
```yaml
stages:
  st1:
    deps:
    - data.txt
    outs:
    - base_dir/stage1_output.txt
    cmd: >-
        mkdir base_dir;
        cat data.txt > base_dir/stage1_output.txt
  st2:
    deps:
    - base_dir/stage1_output.txt
    outs:
    - base_dir/stage2_output.txt
    cmd: >-
        echo SOMETHING
        > base_dir/stage2_output.txt;
        cat base_dir/stage1_output.txt >>
        base_dir/stage2_output.txt
```

`$ dvc repro dvc.yaml`

**Correctly runs both stages**

Modify `cmd` in `dvc.yaml` ie: set `st2.cmd` to 

```yaml
    cmd: >-
        echo SOMEOTHERTHING
        > base_dir/stage2_output.txt;
        cat base_dir/stage1_output.txt >>
        base_dir/stage2_output.txt
```

`$ dvc repro dvc.yaml`

**Expected Output**

**Does not pickup change in `st2.cmd`**

---

```console
$ dvc version
DVC version: 1.0.0a6+68bea2.mod
Python version: 3.7.6
Platform: Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Binary: False
Package: None
Supported remotes: http, https
Cache: reflink - not supported, hardlink - supported, symlink - supported
Repo: dvc, git
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
