### ISSUE TITLE
Add an option or command to dump `dvc run` by a stage name

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4002]
I suppose we have enough information to construct a command that was used to create the stage from a dvc.yaml file?

It would help a lot in editing the file, scripting, etc.

**Comment by efiop** [comment]
@shcheklein The usecase is not really clear. Could you elaborate?

**Comment by shcheklein** [comment]
Yep, sure. Let's say I have a project with `dvc.yaml`:

```yaml
stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    outs:
    - data/prepared
```

and I don't a script/history to get the initial `dvc run` command that was used to create this file.

Now, imagine I decided to introduce params and/or metrics. I changed the `src/prepare.py` to. include:

```python
import yaml

params = yaml.safe_load(open('params.yaml'))['prepare']

# Test data set split ratio
split = params['split']
random.seed(params['seed'])
...
```

it means that I need to run `dvc run` again or manually update the `dvc.yaml` to get it to something like:

```yaml
stages:
 prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
```

In this simplified example, probably not that much difference, but if I want to do a bit more sophisticated changes, it would be great to have something like:

`dvc repro --dump prepare` that outputs:

`dvc run --overwrite -d src/prepare.py -d data/data.xml -o data/prepared python src/prepare.py data/data.xml`

so that one can quickly fix, adding `-n prepare -p prepare.split,prepare.seed` and run it again.
