### ISSUE TITLE
params: store as deps in dvc.lock? Like metrics/plots are outs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4069]
UPDATE: Jump to https://github.com/iterative/dvc/issues/4069#issuecomment-646428961

---

> Also relates to `dvc run -p` option.

## Report

Parameters are currently stored in a `params` field (inside the corresponding stage) in `dvc.yaml` and `dvc.lock`. This is good for dvc.yaml since it makes is easy to read but for dvc.lock which I think we don't want users editing usually, why isn't it just part of `deps`?

This is because `metrics` and `plots` are actually just listed under `outs` in dvc.lock, which makes sense since from the internal point of view of DVC that's all they are. Aren't params just a special kind of dependencies? At least param files.

Now:

```yaml
  outs:
  - path: train.json
    md5: d8b874c5fa18c32b2d67f73606a1be60
  params:
    params.yaml:
      prmgrp:
        prm1: 1
        prm2: 2
```

Suggested:

```yaml
  deps:
  - path: train.json
    md5: d8b874c5fa18c32b2d67f73606a1be60
  - params.yaml:
      type: params # or just assume if there's subfields it's a params file
      prmgrp:
        prm1: 1
        prm2: 2
    # md5: can params files be cached by DVC? (separate question)
```

### Please provide information about your setup

DVC 1.0

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by skshetry** [comment]
`lock` file is an implementation detail, so, the answer to your question will be  a mix of implementation details and aesthetics, not anything in concrete, it might not even make much sense to you, but I'll try.

I see params as `special`. It's not a dependency in `dvc`'s traditional point-of-view. It's not a file and dependency is a value of param, not the file. I was thinking of even separating ordinary deps and params internally (currently `params` is a `ParamsDependency` which extends from `BaseDependency` which all **files** in `s3`, `ssh`, `gs` share), because we are treating in differently, and we have to treat it differently. Because, the notion of dependency being a file is no longer true.

To reiterate my point, `metrics` and `plots` are not treated differently at all. For dvc, they are all outputs, only `dvc plots/metrics` care about them. But, for params, they are treated a bit differently. 

Next thing is I did not like `params` getting crammed into deps flow. This is the aesthetics point.

```yaml
deps:
  - path: file1.txt
    checksum: something
  - path: params.yaml
    params:
       - key1:
            nested.nested2:
               value1: 1
               value2: 2
  - path: file2.txt
    checksum: something
  ```

vs:
```yaml
deps:
  - path: file1.txt
    checksum: something
  - path: file2.txt
    checksum: something
params:
  params.yaml:
    key1:
      nested.nested2:
        value1: 1
        value2: 2
```

I like the latter one. I could also give some points about easier `loading`/`dumping`, but I think the most important are those two.

Again, it boils down to a personal preference rather than some standardized format.

**Comment by jorgeorpinel** [comment]
Your first YAML sample (of what not to do) looks good to me actually, just trying to have params files always at the bottom of the list (since the order doesn't matter AFAIK) e.g.:

```yaml
deps:
  - path: file1.txt
    checksum: something
  - path: file2.txt
    checksum: something
  - path: params.yaml
    params:
       - key1:
            nested.nested2:
               value1: 1
               value2: 2
  - path: more_params.yaml
       - ...
```

Your second YAML sample to me looks like an abbreviation of:

```yaml
deps:
  - path: file1.txt
    checksum: something
  - path: file2.txt
    checksum: something
  - path: params.yaml
    checksum: something
params:
  params.yaml:
    key1:
      nested.nested2:
        value1: 1
        value2: 2
```

And yes I get that it would need extra YAML load/dump logic. Which I would also find reasonable except for the redundancy.

Where is the params.yaml file checksum otherwise BTW? Don't we need it? 🙂
