### ISSUE TITLE
`dvc status` reports changed checksum when it should not

### ISSUE THREAD

**Issue by jnd77** [iterative/dvc#4159]
### Please provide information about your setup

**Output of `dvc version`:**

1.1.6

**Additional Information (if any):**

Am not sure if it's a bug, but I have an unexplained behavior with `dvc status`.
In my repo, there are around 500+ files, each with their own dvc file.
After doing a `dvc pull`, when I run `dvc status`, the output contains a lot of files with status `changed checksum`.
If I run `dvc status --cloud`, it says "Data and pipelines are up to date.".

Most of the files were added a while ago (with 0.90 version), and don't show up in the `dvc status` output. Their dvc file looks like:

```
outs:
- md5: 1bde15f3ad495f8d626c6ad1d294133a
  path: expected-output.png
```

The files showing up in dvc status were added more recently and their dvc file looks like:

```
md5: ba1443b70c6ff71d5531284f21c080c9
outs:
- md5: fc66af77ab971e2dc2b28565f0e19510
  path: 000011.png
  cache: true
  metric: false
  persist: false
```

Were the second set of files added with the wrong command (am not the one who added them so I don't know how they were adeed)? Or is it an issue with `dvc status` ?

Thanks.
