### ISSUE TITLE
Support multiline command?

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4373]
Something like done in Github actions with run and script?
```yaml
stages:
  stage1:
    cmd: |
      cmd1
      cmd2
```

Or, perhaps:
```yaml
stages:
  stage1:
    cmd:
      - cmd1
      - cmd2
```

Or, maybe both?

Need to double check if we will be able to keep the dump in this shape or form.

#### Why?
Better expression

#### Current Workaround:
```yaml
stages:
  stage1:
    cmd: >-
      cmd1
      && cmd2
      && cmd3
```

**Comment by efiop** [comment]
For the record:
```
stages:
  stage1:
    cmd: |
      cmd1
      cmd2
```

this is already supported and will be passed as is to the shell (we use shell=True in Popen). I would keep it as is.

```
stages:
  stage1:
    cmd:
      - cmd1
      - cmd2
```

This looks great and I think it should behave like cmd1 && cmd2 && cmd3, meaning that if one command fails then the rest is not executed and results in a stage failure.

**Comment by ClementWalter** [comment]
I am starting working on it

**Comment by efiop** [comment]
Hi @ClementWalter !

Thanks for looking into it! What advantages/disadvantages do you see for doing a `join` like that?

**Comment by skshetry** [comment]
@efiop, does that multiline string work on all shells?

**Comment by efiop** [comment]
Keeping open for the question about multiline cmd handling raised by @skshetry

**Comment by jorgeorpinel** [comment]
Hi. I'm curious what's the use case for this. Is there a good example of multiple commands that share deps and outs? (to improve the docs)

**Comment by skshetry** [comment]
> Hi. I'm curious what's the use case for this.

This is more of a convenience/ergonomical feature. So, anything you can write in a single line can be written in multiple lines or vice versa but might be easier than just cramming it in one with `&&`.


> Is there a good example of multiple commands that share deps and outs? (to improve the docs)

You can use Github search for this (about usage of `&&`). But, why does it have to share `deps`/`outs` at all?

Here's a list of what I could find:

- building a model and testing it with a different script
- building each model in a separate virtual environment and evaluating them
- building each model in a separate directory and running a script
- `cd ../directory && python script.py` - looks like they are keeping dvc repo and code separately.
- fetching a pre-trained model and training them on local datasets (`wget`, etc).
- cleaning up randomly generated files after building/training/evaluating.
- setting some env vars, PythonPath, etc.
- `cd directory && python test.py` - maybe `cd` is more convenient than `wdir` as `cd` only affects during runtime.

**Comment by jorgeorpinel** [comment]
Thanks! I'm aware of POSIX `&&`. My question is about a real user need that this issue initially tried to cover. I'm getting the idea that this is basically for nice formatting (alt. to `&&` basically).

Also thanks for the specific example ideas! I think that most of them may be better served by other forms thouogh:

> - building a model and testing it with a different script
> - fetching a pre-trained model and training them on local datasets (wget, etc).
> - cleaning up randomly generated files after building/training/evaluating.

Multiple stages

> - building each model in a separate virtual environment and evaluating them
> - building each model in a separate directory

Stage groups (`foreach` syntax in DVC 2.0)

> - cd ../directory && python script.py
> - cd directory && python test.py

`wdir` (or just keeping `&&`)

"setting some env vars" seems like the only instance where this is really convenient, to avoid an ugly string full of `&&`.

> why does it have to share deps/outs at all?

Initially I was assuming that would be the point of having several commands in a stage, since having each command have separate deps/outs and listing those in a single stage doesn't sound very clean (again, better to use 2 stages instead?) Although I suppose if the stages are parallel, it could be a nice use of this feature, along with a `desc` or `# comment` about that perhaps.

Anyway, my Q is answered. Will check with Ivan whether it's worth improving the docs for this. Thanks again!

**Comment by skshetry** [comment]
> Multiple stages

You are thinking of an ideal situation. I won't be creating a separate stage just to clean the logfile the script creates. It's a convenience feature. 

> 
> > * building each model in a separate virtual environment and evaluating them
> > * building each model in a separate directory
> 
> Stage groups (`foreach` syntax in DVC 2.0)

How do you create a virtual environment and run the script with `foreach`? It's a different thing.

> 
> > * cd ../directory && python script.py
> > * cd directory && python test.py
> 
> `wdir` (or just keeping `&&`)

Like I said, `cd` definitely has its place. `wdir` applies to all `outs`/`deps` whereas `cd` is a runtime component.

**Comment by jorgeorpinel** [comment]
It all seems very hypothetical to me but yes, you may be right.

**Comment by skshetry** [comment]
> It all seems very hypothetical to me but yes, you may be right.

All of the examples are from Github's search. How could that be hypothetical?

**Comment by jorgeorpinel** [comment]
Oh I meant not from DVC users.

**Comment by shcheklein** [comment]
@jorgeorpinel 

> Oh I meant not from DVC users.

I guess, they are from DVC users since they come from Github repos that use DVC.

**Comment by jorgeorpinel** [comment]
Ah, I didn't realize those GitHub repos use DVC! I thought it was from generic repos. Will try to find some some of them...

**Comment by jorgeorpinel** [comment]
Too bad that

> You can't use the following wildcard characters as part of your search query: . , : ; / \ ` ' " = * ! ? # $ & + ^ | ~ < > ( ) { } [ ]. The search will simply ignore these symbols.

i.e. I can't actually search for `&&` \- according to [GH search docs](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-code#considerations-for-code-search).
 
So far I've been able to find one interesting example (`python -m ... && fdupes ...`) in [my search](https://github.com/search?q=filename%3Advc.yaml+%26%26&type=Code) but @skshetry if you have a better search can you share it please? I'll keep looking for now.

**Comment by johnnychen94** [comment]
> building each model in a separate virtual environment and evaluating them

Here's the Julia example: where `Pkg.instantiate()` sets up the project environment (like `pip install -r requirements.txt`)

```yaml
prepare:
  foreach: ${models}
  do:
    cmd: >-
      julia --color=yes --startup=no --project=prepare -e "using Pkg; Pkg.instantiate()" &&
      julia --color=yes --startup=no --project=prepare \
        prepare/main.jl data/train/rawdata/ data/train/prepared/${item.name}.h5 \
        --patch-stride ${item.data.patch_stride} \
        --patch-size ${item.data.patch_size} \
        --augment-times ${item.data.augment_times}
    deps:
    - data/train/rawdata
    - prepare
    outs:
    - data/train/prepared/${item.name}.h5
```

I'm thinking of `dvc` as a build system like `make`, so setting up a virtual environment has real merits for reproducibility. Version compatibility is the root of many hidden problems.
