### ISSUE TITLE
Make Output files Optional (dvc run)

### ISSUE THREAD

**Issue by kailingding** [iterative/dvc#4410]
Hi, I've been using DVC for a while now. Loved it so far.

Recently, I'm working on a pipeline that doesn't always output files that are defined in `dvc run -o` command. In other words, if there is a DVC feature that can cache an output file if existed and ignore it if such a file does not exist, that would be great! Because when running experiments, output files defined with `-o` would not always be outputed.

Here's an example of what I exactly mean:

score.py
```python
import json

if __name__ == "__main__":
    score = {"rmse": 0.98}

    saved = True
    if saved:
        with open("./score.json", 'w') as fp:
            json.dump(score, fp)
```

Terminal
```
>>> git init
>>> dvc init
>>> dvc run -n score  -o ./score.json  python ./score.py
```

After running commands above, a `score.json` would be cached by DVC. 

But when I set
```python
saved = False
```
And run the following command
```
dvc repro ./dvc.yaml
```

The following error occurs
```
ERROR: failed to reproduce 'dvc.yaml': output 'score.json' does not exist
```

If there is a feature that can solve this problem, that would be awesome!

**Comment by shcheklein** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/745002571353030717

**Comment by efiop** [comment]
For the record: clearly we can't make these optional by-default, as that will be too error-prone in most of the cases. We could consider introducing a special flag for such options, but that would only make sense if we would also make a similar optional dependency flag for stages that might depend on this file, otherwise you might as well just not specify the output at all.

I see that you've already discussed using empty files as placeholders and I would also suggest doing that instead of a special optional dep/out flag. Seems like that workaround is currently working for you just fine, so I would stick to it, since it is a lot less hacky than optional deps/outs that we would have to introduce otherwise. That said, I can see that being a potential advanced feature in the future.

**Comment by shcheklein** [comment]
@kailingding btw, what type of outputs do you need this feature for first? It looks like your case is about logging (optionally) some ML metrics, right? is it a regular DVC metrics files, or some plots (`dvc plots`)?

I'm asking primarily for two reasons - if it's a metrics file, then due to #https://github.com/iterative/dvc/issues/4068#issuecomment-676540417 empty file might not an option? Also, if we this feature is needed mostly for end results (loggers) we might solve it faster by allowing optional leaf outputs I guess.

**Comment by kailingding** [comment]
It can be both **metrics** files and the **output** files, and they are regular DVC files. If allowing option leaf outputs is fast to fix the problem, then I could just store the metrics using `-o` instead of `-m`. 

But more importantly, I think if `-o` could have a feature of setting a file optional or not, it is more useful compared to if this feature is built on `-m` because the output files are not necessarily just metrics files. It could be model pickle files, some logging files, and so on. I have a separate config file that controls whether these output files will be written when the pipeline is run. Therefore, I could turn off the flag for writing certain files in the config, and if there is an 'option' feature in `-o`, that would be very helpful because there is no need for writing placeholder files and also DVC will be more flexible in terms of outputting files. 

Let me know if any parts that I didn't explain clearly. Or you might have better solutions in mind already. Thanks in advance.

**Comment by shcheklein** [comment]
@kailingding makes sense, thanks! A few questions that come to my mind:

> but that would only make sense if we would also make a similar optional dependency flag for stages that might depend on this file, otherwise you might as well just not specify the output at all.

btw, @efiop why do we need to change anything about dependencies? DVC can recognize optional outputs and it being empty is just as a valid state.

> But more importantly, I think if -o could have a feature of setting a file optional or not

@kailingding - any ideas how would we specify these options?

**Comment by aguschin** [comment]
Encountered this issue while applying DVC to the YOLO repo.

There is a stage which converts the model to different formats (coreml, tflite, pytorch). These formats are specified in params.yaml. And I cannot track them, because in fact they are optional outputs. Though I want to do that, for example, to store them separately or be able to run `dvc get $URL path-to-particular-model`.
```yaml
# somewhere in params.yaml
export:
    include: ['torchscript', 'onnx', 'coreml']
```

But I’d like to track these artefacts and store them with DVC. Workaround is to store a folder with them.

```yaml
# dvc.yaml
stages:
 export:
   params:
     - params.yaml:
         - export
   deps:
     - models/export.py
     - ${export.weights}
   cmd: python models/export.py --params params.yaml
   outs:
     - runs/train/weights
   # I'm not specifying outputs because they are optional
   #   - runs/train/weights/best.torchscript.pt
   #   - runs/train/weights/best.onnx
   #   - runs/train/weights/best.mlmodel
```

As @efiop mentioned above, there could be stages that depend on this optional outputs. In this situation we may have a script which checks that conversion was successful and the model shows acceptable quality.

Other example from the same repo is producing metrics/images as a result of model testing. In that case I may want to see metric values in Studio (and possibly images in the future).

CC @shcheklein

**Comment by stephahn** [comment]
I just faced the same problem and having to change the file each time impossible as we should have only one place to configure the application. 
Also no tracking these files is not an option. 

the hacking solution that I found is to create automatically a placeholder if the file does not exist after the script (using bash script). 

Let call it `dvc_optional_outputs.sh`
```bash
#!/bin/bash

# Check if at least one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <output_filename1> [<output_filename2> ...]"
    exit 1
fi

# Iterate over all provided filenames
for output_file in "$@"; do
    # Check for the optional output
    if [ ! -f "$output_file" ]; then
        echo "Placeholder content for $output_file" > "$output_file"
        echo "Optional output not produced for $output_file!"
    fi
done
fi

output_file=$1
# Check for the optional output
if [ ! -f "$output_file" ]; then
    echo "Placeholder content" > "$output_file"
    echo "Optional output not produced!"
fi
```

And then in dvc.yaml, I call a my command and add the script with optional files at the end. 

````yaml

stages:
  export:
       deps:
         - models/export.py
         - ${export.weights}
       cmd: python models/export.py --params params.yaml && bash dvc_optional_outputs.sh  runs/train/weights/best.torchscript.pt runs/train/weights/best.onnx runs/train/weights/best.mlmodel
````

Could it be a solution? We keep tracking on the file without breaking dvc and without the need of a manual work.
