### ISSUE TITLE
Using parameters on pipeline commands

### ISSUE THREAD

**Issue by fredtcaroli** [iterative/dvc#4525]
I currently have a couple of stages that use the same script. For example, I have a single script for fetching data from my data lake, but I call it twice: once for training data and another for testing data. There are a couple of ways I can accomplish that.

#### Naive way

```yaml
# dvc.yaml
fetch_training_data:
    cmd: python fetch_data.py 01-04-2020 01-05-2020
fetch_test_data:
    cmd: python fetch_data.py 01-05-2020 07-05-2020
```

So my `fetch_data.py` receives a date range. Training data is the entire month of April, and testing data is the first week of May.

This works OK, but I'd like to run retraining every month, so these dates need to be parameterized somehow.

#### A better way

Let's set up a `param.yaml` file this time. We'll need to tell our script how to read that parameter though

```python
# fetch_data.yaml
import sys
import yaml
import datetime

start_date_param = sys.argv[1]
end_date_param = sys.argv[2]
with open('params.yaml', 'r') as fin:
    config = yaml.load(fin, Loader=yaml.SafeLoader)
start_date = datetime.datetime.strptime(config[start_date_param], '%Y-%m-%d').date()
end_date = datetime.datetime.strptime(config[end_date_param], '%Y-%m-%d').date()

fetch_data(start_date, end_date)
```

```yaml
# params.yaml
start_date: '01-04-2020'
end_date: '01-05-2020'
eval_start_date: '01-05-2020'
eval_end_date: '07-05-2020'
```

```yaml
# dvc.yaml
fetch_training_data:
    cmd: python fetch_data.py start_date end_date
    params:
        - start_date
        - end_date
fetch_test_data:
    cmd: python fetch_data.py eval_start_date eval_end_date
    params:
        - eval_start_date
        - eval_end_date
```

This is a bit better. There's definitely a couple of hoops you need to go through, but it gets the job done.
You could also instead bake a `stage` parameter that tells you which parameters to read. That might be better for some cases.

#### The bestest way

Now here's my feature request. Imagine a world where I can simply setup my script parameters to read directly from the parameters file. Here's my suggestion:

```python
# fetch_data.py
import sys
import datetime
start_date = datetime.datetime.strptime(sys.argv[1], '%Y-%m-%d').date()
end_date = datetime.datetime.strptime(sys.argv[2], '%Y-%m-%d').date()

fetch_data(start_date, end_date)
```

```yaml
# params.yaml
start_date: '01-04-2020'
end_date: '01-05-2020'
eval_start_date: '01-05-2020'
eval_end_date: '07-05-2020'
```

```yaml
# dvc.yaml
fetch_training_data:
    cmd: python fetch_data.py {{start_date}} {{end_date}}
fetch_test_data:
    cmd: python fetch_data.py {{eval_start_date}} {{eval_end_date}}
```

See what I did there? I wouldn't even need to specify the `params` specification, since you can infer it from the `cmd`. That could also play nicely with other parameter files, like so:
```yaml
cmd: python fetch_data.py {{data_params.yaml:start_date}} {{data_params.yaml:end_date}}
```

So what do you think? That would greatly simplify my workflow, and I think it would be a great addition to this already awesome tool.
