### ISSUE TITLE
Opening Pickle Files Changes Hash

### ISSUE THREAD

**Issue by pfigliozzi** [iterative/dvc#4661]
Hi all I have been having an issue with hashes generated on a pickled model that I track with DVC. I originally asked about this issue in [this message on discord](https://discord.com/channels/485586884165107732/485596304961962003/761614334370775103). I will summarize the issue below:

In my project I have a DAG that looks like this:
```yaml
stages:
  download_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw_data.csv
  transform_data:
    cmd: python src/transform_data.py
    deps:
    - data/raw_data.csv
    - src/transform_data.py
    outs:
    - data/data_transformer.pkl
    - data/modeling_data.csv
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/modeling_data.csv
    outs:
    - data/model.pkl
  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
    - data/model.pkl
    - data/modeling_data.csv
    outs:
    - data/model_plot.png:
        cache: false
    metrics:
    - data/model_metrics.json
```

And I make a change to my database (which will change the data that is downloaded) in the `download_data` step.

So to have dvc run through the entire pipeline I run `dvc repro -f`. But then I get a curious result when I look at the dvc.lock file after running.
When I look at the diff of the dvc.lock file the hashes for my model doesn't line up:

![gitstatus](https://cdn.discordapp.com/attachments/485596304961962003/761615260909305896/unknown.png)

The new model.pkl file in the `train_model` step has a different hash than the model.pkl file in the `evaluate_model` step. However, all the other files have consistent hashes between the different steps, e.g. raw_data.csv and modeling_data.csv. What is going on? __Why would model.pkl file have two different hashes across the two steps?__

I talked with @pared about it in discord and he asked if my `evaluate_model` step was changing my model.pkl file at all and I told him that it shouldn't be. The way I am saving and loading the pickle file is pretty basic. In `train_model` I dump the model with: 
```python
# Save the trained model.
with open("data/model.pkl", "wb") as f:
    pickle.dump(model, f)
```
And in `evaluate_model` I load it with:
```python
# Load the model.
with open("data/model.pkl", "rb") as f:
    model = pickle.load(f)
```
I don't touch the file in any other lines in those two steps.

I don't really know what is going on. I was able to confirm the hashes in the screenshot above, that is, I did `dvc repro -f train_model` and got a hash of model.pkl of `59f89b3e627db1deecc85911690699fa` and then ran `dvc repo -f evaluate_model` and got a hash of model.pkl of `2d06aa6a6d3b5e98ae4f0c9de3f0294c` (this was done in a separate script using `hashlib` similar to how it is done in DVC). This may not even be a DVC issue and may be just a `pickle` issue, but I am completely lost as to why it is happening.

__DVC version__
```
(base) pfigl@lxm0224 [.../dvc_demo/my_model] $ dvc version
DVC version: 1.8.1 (conda)
---------------------------------
Platform: Python 3.8.3 on Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.10
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Repo: dvc, git
```

__DVC config__
```
(base) pfigl@lxm0224 [.../dvc_demo/my_model] $ cat .dvc/config 
[core]
    remote = localremote
['remote "localremote"']
    url = /home/pfigl/GitHub/dvc_demo/dvc_remote
```
