### ISSUE TITLE
Sharing for experiments and checkpoints

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#4897]
We need a way to share experiments between remote executors and a local environment.

Scenarios:
- Run an experiment through CI/CD (without auto-commits) and see the results in a local environment
- Run an experiment in a remote machine (yeah, it is not implemented yet but the experiment architecture should support it).
- Run parallel experiments in a local machine and see all the runs from a single place.

An "experiment" can be:
- regular experiment `dvc exp`
- an experiment with checkpoints. All the checkpoints need to be shared as well.

What is important:
1. **Addressation** - experiments and checkpoints name should be consistent among the remote and local runs.
2. **Names** - it should be a clear connection (ideally 1-1) between experiment names and Git branches in the main repo.
3. **Local exp to branch** - we need a way (command) to convert regular experiments (w/ and w/o checkpoints) to Git branches in the main repo.
4.  **Run-cache exp to branch** - we need a way (command) to convert experiments from run-cache (w/ and w/o checkpoints) to Git branches in the main repo.

EDITS: It extends #4821

**Comment by pmrowla** [comment]
I've been thinking about this a bit more, and I think custom git refs may work for us here rather than storing patches in DVC run-cache or exp-cache.

We've discussed the potential of using a custom git ref namespace for experiments before, but it was tabled since github actions cannot be triggered when pushing a custom (non-branch or tag) ref.

However, in this case even though we have to push an actual branch to trigger a github actions (or gitlab) CI/CD build, I think we can still leverage custom refs as a cleaner way to store experiment patches.

Internally on the DVC side, we will need to support `git push` and `git fetch`'ing from our experiments workspace (`.dvc/experiments`) to and from a custom refs namespace (like `refs/exp/...` or `refs/dvcexp/...`). This would also facilitate sharing experiments between team members even without taking the CI/CD use case into consideration. 

* `dvc exp push` (or maybe `dvc push --exp`) would push all "local" experiment branches to an upstream git remote (plus the run cache for whatever we have already run locally)
* `dvc exp pull` would pull everything from the upstream `refs/exp` into our local experiments workspace (plus the associated run cache).
* We would probably also need commands to list and gc experiments in the upstream git repo

On the CI/CD side, we are still limited by needing to push actual branches or PRs in order to trigger a build, so either

* the user needs to set up an actual repo level github branch with the changes they want to test and push it
* or we trigger it ourselves by pushing a PR branch via something like `dvc exp deploy`

The user's CML workflow would look similar to the existing DVC workflow except that we use `exp run` instead of `repro`. This would result in a single new experiment branch generated in `.dvc/experiments` on the CI runner (including checkpoint commits for checkpoint experiments). We can then push that experiment to our custom ref from the CI runner, the same way we would do it from a "local" machine.

In the end, on github/gitlab there will be a branch (named appropriately for the experiment) containing a single commit (required to trigger the build). The result of the 

Hypothetical workflow:
```yaml
name: train-test
on: [push]
jobs:
  run:
    ...
    steps:
      - uses: actions/checkout@v2
      - name: cml_run_exp
        ...
        run: |
          ...
          # Pull data & run-cache
          dvc pull data --run-cache

          # Run as experiment instead of via repro 
          # Note that here we just want a normal "local" run (since in this case the "local" machine is the user's chosen CI runner)
          dvc exp run

          # Push experiment branch to custom ref (and associated run-cache) so it can be pulled and reviewed locally
          dvc exp push

          # Report metrics & params
          echo "## Experiment" >> report.md
          dvc exp show --show-md >> report.md

          # Publish other reports (plots, etc)
          ...

          cml-send-comment report.md
```

The main benefits of doing it this way would be that we can continue leveraging git and avoid needing to manage patch sets ourselves in some `.dvc/cache/exp/...` structure. And it is safe for us to make "auto-commits" in this case, since the commits are generated in `.dvc/experiments` on the CI runner and will only be pushed to our custom ref namespace (which will not recursively trigger more CI builds).
