### ISSUE TITLE
stage name incorrectly parsed with parametrization for dict

### ISSUE THREAD

**Issue by johnnychen94** [iterative/dvc#4957]
### Please provide information about your setup

List version works:

```yaml
stages:
  build:
    foreach:
      - 15
      - 25
      - 35
    do:
      cmd: echo ${item}
```

```console
jc@mathai3:~/Downloads/dvc_test$ dvc repro "build@15"
Running callback stage 'build@15' with command:
	echo 15
15
```

However, the dict version doesn't

```yaml
stages:
  build:
    foreach:
      - level: 15
      - level: 25
      - level: 35
    do:
      cmd: echo ${item.level}
```

```console
jc@mathai3:~/Downloads/dvc_test$ dvc repro --dry
Running callback stage 'build@{'level': 15}' with command:
	echo 15

Running callback stage 'build@{'level': 25}' with command:
	echo 25

Running callback stage 'build@{'level': 35}' with command:
	echo 35
Use `dvc push` to send your updates to remote storage.
jc@mathai3:~/Downloads/dvc_test$ dvc repro -f "build@{'level': 15}"
ERROR: 'build@{'level'' does not exist.
```

According to the error output, I guess the stage name is incorrectly parsed somewhere. I tried to look at the source code but failed to find a clue.

**Output of `dvc version`:**

```console
DVC version: 1.10.1+abb78c
---------------------------------
Platform: Python 3.8.3 on Linux-5.4.0-42-generic-x86_64-with-glibc2.10
Supports: All remotes
Cache types: symlink
Cache directory: nfs4 on storage:/home
Caches: local
Remotes: None
Workspace directory: nfs4 on storage:/home
Repo: dvc, git
```

**Comment by skshetry** [comment]
@johnnychen94, this is not supported. List in `foreach` data is not supported to have dict or any complex object inside it.

Can you refactor it to use dict than a list:
```yaml
stages:
  build:
    foreach:
      level1:
        level
      level2:
        level: 35
    do:
      cmd: echo ${item.level}
```

**Comment by johnnychen94** [comment]
Good to know the alternative and yes it works.

```yaml
# dvc.yaml
stages:
  build:
    foreach: ${models}
    do:
      cmd: "echo type: ${item.noise_type} level: ${item.noise_level}"
```

```yaml
# params.yml
models:
  model_1:
    noise_type: "gaussian"
    noise_level: 15
  model_2:
    noise_type: "gaussian"
    noise_level: 25
```

```console
jc@mathai3:~/Downloads/dvc_test$ dvc repro --dry -f
Running stage 'build@model_1' with command:
	echo type: gaussian level: 15

Running stage 'build@model_2' with command:
	echo type: gaussian level: 25
Use `dvc push` to send your updates to remote storage.
```

Should I update the wiki? I guess this is something that people will occasionally hit because it's simpler to write

```yaml
# params.yml
models:
  - noise_type: "gaussian"
    noise_level: 15
  - noise_type: "gaussian"
    noise_level: 25
```
