### ISSUE TITLE
Context.clone: deepcopy takes a lot of time

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4963]
### Steps to Reproduce
1) Create a file with large no. of files
```bash
#! /usr/bin/bash
$num=100
echo "vars:" > params.yaml 
for i in $(seq $num); do 
    echo "- $i" >> params.yaml
done
```
2)  Add the following to `dvc.yaml`:
```yaml
stages:
  build:
    foreach: ${vars}
    do:
      vars:
        - y: "3"
      cmd: "echo ${item} > ${item}.txt"
      outs:
      - ${item}.txt
```

3) `dvc repro`

Repeat these steps by changing num to 1000

Following is the visualization for `$num = 100`:
![Screenshot from 2020-11-25 12-59-35](https://user-images.githubusercontent.com/18718008/100194604-11daac00-2f1e-11eb-88f4-c71713f9f95f.png)

`repro` completed the run in `2m19s`, with each file getting resolved in 610.62 ms.

Following is the visualization for `$num = 1000`:
![Screenshot from 2020-11-25 13-01-49](https://user-images.githubusercontent.com/18718008/100194765-60884600-2f1e-11eb-9b3e-e9454b7dc6e3.png)

It takes 47s to 54s in resolving values, most of the time (if not all) spending on `__deepcopy__()`.  Though, I'm shocked to see it change with an increase in `num` as the data is the same size as when it was `100` (and is small).
