### ISSUE TITLE
Boolean value might get unnecessarily uppercased

### ISSUE THREAD

**Issue by johnnychen94** [iterative/dvc#4996]
## Bug Report

Python uses `True`/`False` as boolean values, while in other languages it might not be the case (Julia uses `true`/`false`).

It seems that the correct behavior is `dvc` faithfully stores the params as strings, and only does type conversion (str -> bool/int/float) when it needs to output some statistics, e.g., `dvc params diff`.

This seems to be an edge case for bool values only, so feel free to close if you don't plan to fix it.

### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.10.2 (pip)
---------------------------------
Platform: Python 3.8.3 on Linux-5.4.0-54-generic-x86_64-with-glibc2.10
Supports: All remotes
Cache types: symlink
Cache directory: nfs4 on storage:/home
Caches: local
Remotes: s3
Workspace directory: nfs4 on storage:/home
Repo: dvc, git
```

**Additional Information (if any):**

```yaml
# dvc.yaml
stages:
  build:
    cmd: julia -e "println(ARGS); println(typeof.(ARGS))" ${opt1} ${opt2} ${opt3}
```

```yaml
# params.yaml
opt1: true
opt2: "true"
opt3: some_other_string
```

Notice that `opt1` is transformed to `"True"` instead of `"true"`.

```console
jc@mathai3:~/Downloads/dvc_test$ dvc repro -f
Running stage 'build' with command:
	julia -e "println(ARGS); println(typeof.(ARGS))" True true some_other_string

["True", "true", "some_other_string"]
DataType[String, String, String]
```
