### ISSUE TITLE
parametrization: fails for non-string interpolations

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5006]
See: https://github.com/iterative/dvc/wiki/Parametrization#known-issues

If the interpolated value is not a string in the params file, DVC will fail with a validation error.
Let's say, you have params with the following values:

```yaml
# params.yaml
msg: true

# dvc.yaml
stages:
  echo:
    cmd: ${msg}
```

It might fail with the error similar to the following:

```console
Running stage 'echo' with command:
        True
ERROR: failed to reproduce 'dvc.yaml': expected str, bytes or os.PathLike object, not bool
```
