### ISSUE TITLE
no read locks to stage output

### ISSUE THREAD

**Issue by johnnychen94** [iterative/dvc#5007]
Separate from #4979, it would significantly improve the current dvc parallelization capibility if `data.txt` doesn't get locked.

```yaml
stages:
  prepare:
    cmd: echo "hello" > data.txt
    outs:
    - data.txt
  train:
    foreach:
      - 1
      - 2
      - 3
    do:
      cmd: cat data.txt && sleep 100
      deps:
      - data.txt
```
