### ISSUE TITLE
Imported Dependencies should have a configureable revision

### ISSUE THREAD

**Issue by tillbier** [iterative/dvc#5058]
When importing dependencies via the `dvc import` feature, I want to be able to set a revision for a stage in the `dvc.yaml`, from which the dependency should be pulled, so that i can change the revision with the parametrisation feature. 

This could look like the following:

dvc.yaml
```yaml
vars:
  - params.yaml

stages:
  regression:
    cmd: ./trainModel.sh
    deps:
    - images:
        revision: ${training.images.version}
    outs:
    - model.hdf5:
```

**Comment by efiop** [comment]
We are thinking about moving imports to dvc.yaml too https://github.com/iterative/dvc/issues/4841 , but so far we are thinking about a format that looks something like:

```
vars:
  - params.yaml

imports:
- images:
    repo: https://github.com/iterative/dvc
    path: data
    rev: ${training.images.version}

stages:
  train:
    cmd: ./trainModel.sh
    deps:
    - images
    outs:
    - model.hdf5
```
or similar, the main idea is that `imports` are separated from `stages`. Would something like that work for you?
