### ISSUE TITLE
Parameterize input files for `dvc repro` for integration testing

### ISSUE THREAD

**Issue by copaah** [iterative/dvc#5144]
I want to do some testing on my `dvc.yaml` files.

My current setup looks like this

```
data/
     raw/
         video1.mp4
         video2.mp4
     processed/
         video1/
             image1.png
             image2.png
         video2/
             image1.png
             image2.png
dvc/
    main_pipeline/
        dvc.yaml
tests/
    main_pipeline/
        test_dvc_stage_1.sh
```

Where my `dvc.yaml` looks something like this

```
stages:
     dump_frames:
          cmd: ...
     deps:
         data/raw
     outs:
         data/processed
```

Now this works fine when I want to process all videos in `data/raw`. For my integration testing I want to just pass one video through my dvc stage. This works if I do something like this:

```
test_dvc_stage_1.sh
-------------------------------
dvc pull data/raw/video1.mp4
dvc repro dvc/main_pipeline/dvc.yaml:dump_frames -s
```
The problem is that if a developer has pulled all data on his local machine the call `dvc repro dvc/main_pipeline/dvc.yaml:dump_frames -s` will work on all pulled data.

It would be nice to have a feature that parameterizes this input. An idea could be:

```
stages:
     dump_frames:
          cmd: ...
     deps:
         ${input_data}
     outs:
         data/processed
```

And then it could be called like:

```
dvc repro dvc/main_pipeline/dvc.yaml:dump_frames -s input_data=data/raw/video1.mp4
```
