### ISSUE TITLE
dvc.yaml: support looping nested substitutions

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5167]
How about support for combining params and loops (via nesting `${item}` inside `${param}`? E.g.

```yaml
# params.yaml
models:
  us:
    thresh: 10
    filename: 'model-us.hdf5'
  uk:
    thresh: 13
    filename: 'model-gb.hdf5'
```

```yaml
# dvc.yaml
stages:
  build:
    foreach:
      - us
      - uk
    do:
      desc: Dummy command
      cmd: echo "${models.${item}.thresh} ${var}" > ${models.${item}.filename}
      outs:
      - ${models.${item}.filename}
```

> This currently fails @ repro with `ERROR: failed to parse 'stages.build@us.cmd' in 'dvc.yaml': Could not find 'models.${item'` on DVC 1.11.0.

**Comment by jorgeorpinel** [comment]
Cc @skshetry thouoghts? 🙂

**Comment by skshetry** [comment]
![](https://media.giphy.com/media/3f0Rz4dEhQqPIR5mSS/source.gif)

**Comment by shcheklein** [comment]
@skshetry but we can achieve the same result by iterating on `models`, right? (`item` should be assigned a dict with values in that case)?

**Comment by skshetry** [comment]
> @skshetry but we can achieve the same result by iterating on `models`, right?

@shcheklein, yes, @jorgeorpinel just flattened the `foreach` here. Nested interpolation is more powerful, as it allows you to have unstructured/semi-structured data. But, it can become ugly and hard to maintain.

As an example, let's say you have data in the form of transpose (just to show that you can scatter your configs around) given in the above example as:

```yaml
# params.yaml
parameters:
  thresh:
    us: 10
    uk: 13
  files:
    us: "model-us.hdf5"
    uk: "model-gb.hdf5"

# dvc.yaml
stages:
  build:
    foreach:
      - us
      - uk
    do:
      cmd: echo "${parameters.thresh.${item}} ${var}" > ${parameters.files.${item}}
      outs:
      - ${parameters.files.${item}}
```

This easily gets complicated as more and more interpolations are used.
For now, users have to keep them in a particular structure. We should wait for this till the user asks for it (and, has enough interests in the community).


Thinking about the syntax, we could alternately use `[]` for accessing variables inside interpolations and force other string usages to be quoted:

```yaml
cmd: echo "${parameters.thresh[item]} ${var}" > ${parameters.files[item]}

cmd: echo "${parameters.thresh['uk']} ${var}" > ${parameters.files['uk']
```
