### ISSUE TITLE
Wildcards in pipeline dependencies

### ISSUE THREAD

**Issue by amin-nejad** [iterative/dvc#5252]
In pipeline dependencies, it would be a lot easier and more robust if we could include wildcards. For instance, let's say I have a `data` step in my pipeline which makes use of some source files. I'd like to specify all relevant python files in a given directory as being dependencies:

`dvc.yaml`:
```yaml
stages:
    data:
        cmd: python -m path.to.data_generation_script
        deps:
          - src/data/*.py
        ...
```

However, that doesn't work as wildcards aren't recognised. Instead, I can specify the directory itself (`src/data`) but this appears to include `__pycache__` and `.ipynbcheckpoints` (and anything else that may be in that directory) which is obviously not desired behaviour and results in the dvc hash being different to someone who has freshly cloned the repo.
