### ISSUE TITLE
deps is inconsistent between dvc.yaml and .dvc files

### ISSUE THREAD

**Issue by antonkulaga** [iterative/dvc#5370]
When I have something like:
```
    deps:
      - path: http://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
        etag: W/"5f8d62ed-34863818"
        cache: false
```
It works find in .dvc files, but when I add it to one of the stages, I get an error as it assumes deps are string only.
```
stages:
  prepare_genome:
    frozen: true
    deps:
      - path: http://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
        etag: W/"5f8d62ed-34863818"
        cache: false
    cmd: bin/prepare_genome.sh
    out:
      - data/gwas/homo_sapiens_ensembl_102/Homo_sapiens.GRCh38.dna.primary_assembly.fa
```
the error is:
```
 'dvc.yaml' format error: expected str @ data['stages']['prepare_genome']['deps'][0]
```
the dvc version is 1.11.10 (latest .deb file).
I suggest that "deps" should behave the same in .dvc and dvc.yaml as otherwise it creates a lot of confusion.

**Comment by skshetry** [comment]
@antonkulaga, the old `.dvc` file support is going to be removed in the upcoming release next month.  It's only supported for `dvc add/import`.

**Comment by antonkulaga** [comment]
@skshetry I was not talking about having stages in .dvc files, but having:
```
deps:
      - path: http://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
        etag: W/"5f8d62ed-34863818"
        cache: false
```
inside of the dependencies in dvc.yaml So far only "str" is supported for deps in dvc.yaml, I believe it should also support etags for external dependencies

**Comment by skshetry** [comment]
@antonkulaga, the checksums are kept in lockfile. You just have to write the entry as follows and then `dvc repro` it later:
```yaml
stages:
  prepare_genome:
    cmd: bin/prepare_genome.sh
    deps:
      - http://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
    out:
      - data/gwas/homo_sapiens_ensembl_102/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    frozen: true
```

`cache: false` were never honoured for `deps` and is not required.
