### ISSUE TITLE
pull -q: does not return 0 if error happens

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#5690]
# Bug Report

## Description

dvc pull -q is not returning 0 if an error happens

### Reproduce

Example:
1. create dvc.yaml
```yaml
stages:
  mystage:
    cmd: python train.py
    deps:
    - data
    - train.py
    metrics:
    - metrics.json:
        cache: true
    plots:
    - loss.csv:
        cache: true
```
2. Add some /data
2. dvc init
3. dvc add data
4. dvc push --run-cache
5. remove .dvc/tmp and .dvc/cache
6. (dvc pull --run-cache -q) || echo 'failed'

### Expected

0 returned not printing  'failed'

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.0.5 (deb)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.76-linuxkit-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: fuse.grpcfuse on grpcfuse
Caches: local
Remotes: s3
Workspace directory: fuse.grpcfuse on grpcfuse
Repo: dvc, git
```
