### ISSUE TITLE
Handle Virtual Environment Activation Within DVC

### ISSUE THREAD

**Issue by rogermparent** [iterative/dvc#5758]
There's many ways to go about solving this, some involving code changes for DVC and some simply establishing a convention with our current codebase, but each method has its own set of pros and cons and we'd like to use the one that best fits with how DVC is used.

Dealing with this issue properly can bring benefits to DVC CLI users, but will also greatly help with applications like the VSCode extension that consume DVC CLI as an API (for convenience, I'll call these consumers).

# The problem

Whenever DVC calls an external script (like in exp run), running dvc without a PATH modified by an activated virtual environment is not sufficient.

Initially, we wanted to get this information from the VSCode Python extension in the same way it activates integrated VSCode terminals, but currently that extension does not export its internal logic to activate Python environments- beyond that, there's the question of running DVC in environments that aren't handled by the Python extension, particularly other languages.

# Possible solutions

I'd like to present this list of solutions in order let others comment on them and pick which one is most preferred.

An overall theme I'd also like everyone to consider is:  
*"Is handling Virtual Environments something we'd like to handle within DVC itself?"*

## Activating Within dvc.yaml cmd
A dead-simple method is adding the activation command to the `cmd` field of `dvc.yaml`:
```yaml
stages:
  train:
    cmd: >-
      source .env/bin/activate;
      python train.py;
```

It almost feels too simple, but configuring this way provides maximum freedom for projects and requires the least adaptation from consumers. However, this technically has a drawback in that users and consumers cannot freely use a project configured like this with a different or no virtual environment unless they change this command.

## Adding a new `activate` configuration option
This is essentially a fancy version of the prior solution, but provides a feature that both users and consumers can get a lot of use out of.
Essentially, I'm thinking of a new activate config option that can be used like this:

At its most basic, a new top level option allows for specifying an activation command that will run before any normal cmd
```yaml
activate: source .env/bin/activate
stages:
  train:
    cmd: python train.py
```
But individual stages can opt out...
```yaml
  train_without_activation:
    activate: false
    cmd: python train.py
```
...or override the command.
```yaml
  train_with_unique_activation:
    activate: conda activate specialenv
    cmd: python condatrain.py
```

and this could be paired with a CLI flag that can override the dvc.yaml settings for a specific run, similar to the params overrides.

A feature like this could go a long way for both users and consumers, especially where it's very user-configurable and stack-agnostic.

## Templating
This is another solution that doesn't need modifications to `dvc`, but rather just establishes a convention that we'll want to document. Using Templating solves a few of the problems that the first `dvc.yaml` solution faces.

For example:
```yaml
vars:
  - activate: source .env/bin/activate;
stages:
  train:
    cmd: ${activate} python train.py
```
Alternatively:
```yaml
vars:
  - python: source .env/bin/activate; python
stages:
  train:
    cmd: ${python} train.py
```
I've had success running both of these with no activated environment needed beforehand.

## Activating in Consumer Applications
I've probably shown my hand in that I'm slightly biased against this one, as re-implementing this on every consumer application for every DVC stack seems like an unnecessary duplication of work, despite technically being possible. I'm open to opposing arguments, however.

As mentioned in the introduction, the Python extension in VSCode is currently a little wonky to hook into as far as environment activation- we'll have to either re-create the extension's functionality or petition Microsoft to expose the API (either through Issue or a PR, they have a GitHub repo), and putting in the effort of doing so won't address languages in virtual environments other than Python.

There's an argument that Python seems to be the only language used with DVC that has these venv issues, but I believe that this alone isn't enough to disqualify the idea that we should handle arbitrary activation commands for both simplicity of implementation and the ability to handle current and future corner cases.
