### ISSUE TITLE
repro: LockError due to unnecessary write lock

### ISSUE THREAD

**Issue by maximerischard** [iterative/dvc#5795]
# Bug Report

## Description

A LockError is raised if two dvc steps that share a dependency are run in parallel.

### Reproduce

```sh
dvc init
echo "hello" > dependency.txt
dvc add dependency.txt
```
The add the following to `dvc.yaml`:
```yaml
stages:
  step1:
    cmd:
        - sleep 20
        - echo 'output1' > out1.txt
    deps:
    - dependency.txt
    outs:
    - out1.txt
  step2:
    cmd:
        - sleep 20
        - echo 'output2' > out2.txt
    deps:
    - dependency.txt
    outs:
    - out2.txt
```
The run `dvc repro step1` and `dvc repro step2` in two separate terminals. The second command will result in a LockError:
```
ERROR: failed to reproduce 'dependency.txt.dvc': 'dependency.txt' is busy, it is being blocked by:
  (PID 159252): […]/dvc repro step1

If there are no processes with such PIDs, you can manually remove '.dvc/tmp/rwlock' and try again.
```

The reason seems to be that:
1. `step1` grabs a read lock on `dependency.txt`
2. `step2` triggers `dependency.txt.dvc` to be “run“
3. `dependency.txt.dvc` requests a write lock on `dependency.txt`
4.  the write lock is refused because of the read lock from (1)

Step (3) seems to be the problematic one, there should be no need for a write lock on `dependency.txt` to be requested.

### Expected

Two `dvc repro` or `dvc run` commands that read from the same file should be able to run in parallel.

### Workaround

`step2` can be run with `dvc repro --single-item step2` but this should not be necessary.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.9.0 on Linux-4.15.0-136-generic-x86_64-with-glibc2.27
Supports: http, https, s3
```
