### ISSUE TITLE
Freezing stages with parameter substitution

### ISSUE THREAD

**Issue by plomtb** [iterative/dvc#6070]
Hi, 
I'm opening this issue as discussed [here](https://discuss.dvc.org/t/freeze-stage-with-parameter-substitution/761). Using 
```yaml
# dvc.yaml
vars:
  - folder: .

stages:
  Test:
    cmd: dir ${folder}
    always_changed: true
```
as dvc.yaml and running
`dvc freeze Test` gives the following error:
`ERROR: failed to freeze 'Test' - cannot dump a parametrized stage: 'Test'`. I don't really understand why this is different from normal stages. Another question: Would it be possible to declare a (custom) stage an import stage, so that `dvc update Test` works, without freezing/unfreezing?
Thanks
