### ISSUE TITLE
exp run: "duplicated env variable" error is unexpected and not informative

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#6098]
# Bug Report

## Description

Changing outs from a folder to a few files in this folder produces "Duplicated env variable".
1. It's a usual thing when outputs change over time. It's not clear why this is not supported.
2. The message itself doesn’t help much with identifying the cause of the issue. At least it would be helpful to see what variable was duplicated to debug this faster.

### Reproduce

Let’s suppose I had the following dvc.yaml:

```
stages:
 train:
   deps:
     - train.py
   cmd: python train.py
   outs:
     - weights:
         checkpoint: true
```

Which I’ve used for some time with `dvc exp run` and then change it to:
```
stages:
 train:
   deps:
     - train.py
   cmd: python train.py
   outs:
     - weights/best.pt:
         checkpoint: true
     - weights/last.pt:
         checkpoint: true
```

And now I get the error:
```
$ dvc exp run train 
Running stage 'train':                                                                                                                                         
ERROR: failed to reproduce 'dvc.yaml': Duplicated env variable
```

### Expected

1. I've expected dvc to handle this situation: my pipeline can change over time and it's ok for my outputs to change, so from the user perspective it's not very clear why this doesn't work.
2. If that's wrong way to use dvc or this functionality is not implemented, I've expected to get helpful error message to understand what's gone wrong.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.1.0 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Additional Information (if any):**

1. If this will be helpful, I can reproduce this on some example repo and post exact steps to do it.
2. Not sure checkpoints are involved, but I decided to keep them in case they were present in my dvc.yaml
