### ISSUE TITLE
straight-to-remote: does not set size in the .dvc file

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6161]
When I do `dvc add cat.jpg`, I get the following contents in `cat.jpg.dvc`:
```yaml
outs:
- md5: 4a94da5d72618376ab28d789300308da
  size: 2092576
  path: cat.jpg
```

And, when I do `dvc add --to-remote -r webdav remote://webdav-root/cat.jpg`, I get the following contents in `cat.jpg.dvc`:
```yaml
outs:
- md5: 4a94da5d72618376ab28d789300308da
  path: cat.jpg
  nfiles: 1
```

Both of those should create identical `.dvc` files.
