### ISSUE TITLE
More informative message when dvc.yaml is malformed

### ISSUE THREAD

**Issue by nsorros** [iterative/dvc#6285]
I know we are supposed to let `dvc run` construct the `dvc.yaml` but I tend to write them manually as they are quite easy to construct. Often though I am receiving slightly difficult to decipher errors about the format. An example is below
```
stages:
  train:
    cmd:
      - spacy train config.cfg
    deps:
      - config.cfg
    outs:
      models/spacy-model
```

this throws `ERROR: 'dvc.yaml' format error: extra keys not allowed @ data['stages']['train']['cmd']`

it is quite difficult to decipher that this is missing a `-` in `outs`. not sure why it complains about `cmd` either. would it be possible to give back feedback closer to the error?
