### ISSUE TITLE
dvc exp show -n 1: Using the DVC exp show table doesn't return any metrics for me

### ISSUE THREAD

**Issue by robSanders818** [iterative/dvc#6315]
# Bug Report

## Description
When I try to run dvc exp show -n 1, it only shows the parameters I am using for my project, and this is even clearer when appending the --show-json parameter, and the metrics have no data in them.    However this is especially odd, because the data json file does return metrics if I just call the path, `dvc metrics show /src/sub_folder/data/performance_metrics.json` it shows the actual correct metrics.  
I have a 2 pipeline dvc system, where I have 2 folders that both contain separate dvc.yaml files.  I am curious if this is causing the un-targeted command to give an error.  On this platform I don't even need the 2nd folder, so I actually just deleted it, and I'm still getting the same issue after committing/re-running.

### Reproduce
I'm not exactly sure what led to this issue originating, but what I am doing is

1. `dvc exp show -n 1 --show-json`
     this gives no metrics, and shows {}
2. `dvc metrics show -v`
     gives no metrics, shows error
3. `dvc metrics show /src/sub_folder/data/performance_metrics.json`
     shows exact metrics I'm looking for

### Expected
Expect dvc exp show to a table listing parameters, and the corresponding metrics on the rightmost columns

### Environment information
This is required to ensure that we can reproduce the bug.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.14.173-137.229.amzn2.x86_64-x86_64-with-debian-10.9
Supports:
    hdfs (pyarrow = 3.0.0),
    http (requests = 2.25.1),
    https (requests = 2.25.1)
```

**Additional Information (if any):**
Using `dvc metrics show -v` shows 
```
dvc metrics show -v
2021-07-14 13:33:02,559 DEBUG: Check for update is enabled.
2021-07-14 13:33:05,064 DEBUG: Failed to acquire '/base_folder/.dvc/tmp/updater.lock' before checking updates
2021-07-14 13:33:05,225 ERROR: Could not parse metrics files. Use `-v` option to see more details.
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/command/metrics.py", line 22, in run
  File "dvc/repo/metrics/__init__.py", line 8, in show
  File "dvc/repo/__init__.py", line 51, in wrapper
  File "dvc/repo/metrics/show.py", line 127, in show
dvc.exceptions.NoMetricsParsedError: Could not parse metrics files. Use `-v` option to see more details.
------------------------------------------------------------
2021-07-14 13:33:05,227 DEBUG: Analytics is enabled.
2021-07-14 13:33:05,282 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpysij70j2']'
2021-07-14 13:33:05,283 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpysij70j2']'
```

Here are my dvc.yaml and dvc.lock files:
```
vars:
  - params.py

stages:
  run_code:
    cmd: python -m run_code
    deps:
    - ./run_code.py
    params:
      - params.py:
          - param_1
          - param_2
          - param_3
          - param_4
          - param_5
          - param_6
          - param_7
          - param_8
    outs:
    - /src/data_save_folder:
        persist: true
  test_accuracy:
    cmd: python -m run_accuracy_script
    deps:
      - ./run_accuracy_script.py
      - /src/data_save_folder
    metrics:
      - /src/sub_folder/data/performance_metrics.json:
          cache: false
          persist: true
    params:
      - params.py:
          - param_1
          - param_2
          - param_3
    outs:
    - /src/sub_folder/data/performance_metrics/metrics.txt
```
```
schema: '2.0'
stages:
  run_code:
    cmd: python -m run_code
    deps:
    - path: ./run_code.py
      md5: 9b9d917b729fe5de75e20c64c9272a69
      size: 864
    params:
      params.py:
        param_1: 20
        more_params....
    outs:
    - path: ../data_save_folder
      md5: f6f464bc6e8533ea052cd5153a3efab9.dir
      size: 5912566
      nfiles: 1366
test_accuracy:
    cmd: python -m run_accuracy_script
    deps:
    - path: ../data_save_folder
      md5: f6f464bc6e8533ea052cd5153a3efab9.dir
      size: 5912566
      nfiles: 1366
    - path: ./run_accuracy_script.py
      md5: 8ebcfedec0dd0f2334300c566b93cd9d
      size: 18824
    params:
      params.py:
        param_1: 0
        more_params
    outs:
    - path: ../sub_folder/data/performance_metrics/metrics.txt
      md5: 192a6ec9900d50eb15e13dcb47add1d1
      size: 2594
    - path: ../sub_folder/data/performance_metrics.json
      md5: 0be75473a3d4819fc3a09a14644541a8
      size: 207
```

In addition here is the /src/sub_folder/data/performance_metrics.json I am using:
```json
{"precision": 0.23404255319148937, "recall": 0.3235294117647059, "f1_score": 0.271604938271605, "true_positives": 11, "false_positives": 36, "false_negatives": 23, "metric": 49.09090909090909}
```
