### ISSUE TITLE
add: Pipeline branching based on params value

### ISSUE THREAD

**Issue by legendof-selda** [iterative/dvc#6500]
Allow users to create branching strategy in dvc pipeline based on a value in params. Currently, the only way to achieve branching in dvc pipeline is via connecting right outputs and dependencies for each stage. But, this might not always work well and its not very flexible either. Using a value from the `params.yml`, we can use that as a switch value to the required stage.
Example:
* `params.yml`:
``` yaml
pipeline_switch:
  value: true
```
* `dvc.yml`
``` yaml
stages:
  process_data:
    cmd: python process_data.py
    outs:
    - data/train/:
        persist: true
    - data/test/:
        persist: true
  switching_stage_name:
    switch:
      run_after: process_data
      value:
        params.yml: pipeline_switch
      case:
      - true: train_stage
      - false: inference_stage
  train_stage:
    cmd: python train.py
    deps: 
      - data/train/
      - data/test/
    metrics:
      - accuracy.txt:
          cache: false
  inference_stage:
    cmd: python infer.py
    deps: 
      - data/test/
    metrics:
      - accuracy.txt:
          cache: false
```

Something of this form we can achieve conditional branching
