### ISSUE TITLE
Can you evaluate python code within dvc.yaml (any plans for dvc.py)?

### ISSUE THREAD

**Issue by asmith26** [iterative/dvc#6512]
Hi there,

I have a python [config/templating file](https://dvc.org/doc/user-guide/project-structure/pipelines-files#templating), which is used by **dvc.yaml** for a number of variables. I believe you cannot evaluate any python code within **config.py** from **dvc.yaml** - e.g. I was wondering if **dvc.yaml** can evaluate python so that I could use something like

**config.py**

```python
from pathlib import Path

raw_data_dir = Path("raw")
processed_data_dir = Path("processed")
processed_data_filename =  "data.csv"
processed_data_path = raw_data_dir / processed_data_filename
model_name = "model.pkl"
```

**dvc.yaml**

```yaml
vars:
  - config.py

stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - ${raw_data_dir}
    outs:
      - ${processed_data_path}

  train:
    cmd: python train.py
    deps:
      - ${processed_data_path}
    outs:
      - ${model_name}
```

**Can you evaluate python code within dvc.yaml (any plans for dvc.py)?** Alternatively, like [params can now be a Python file](https://dvc.org/doc/command-reference/params#examples-python-parameters-file), I'm curious if you have any plans to support something like **dvc.py** (i.e a python file replacement for dvc.yaml that could potentially evaluate python code)?

Just some thoughts - I welcome any thoughts you may have on any of this and many thanks for these **_amazing_** libraries! :)
