### ISSUE TITLE
Extend the use of `desc` and support it in other dvc commands (e.g. as filter, etc) of the cli/api

### ISSUE THREAD

**Issue by meierale** [iterative/dvc#6548]
### Current situation / behaviour
Currently `dvc` supports the `--desc <text>` option in the `dvc add` command. This allows the user to add an optional description of the data to be added. However it does not affect any other `dvc` operations. Also it is only possible to add a description in plain text of unknown length.

On the other hand it is currently not possible do easily browse/query a `dvc` based data registry for a specific data set.

### Desired behaviour
This Feature Request is about to change that and suggests to support `desc` (or its content) in other dvc commands. Here's a non-exhaustive list of possible extensions:

- allow `dvc list` to filter or query for tracked files according to their description (`desc`). 
  - If no filter is set, list all files. 
  - If a filter is set, only list tracked files that match the filter (e.g. contain the filter keyword(s) in their description)
- add a `show-desc` or `show description` option to `dvc` which will show the description of a given file (e.g. `dvc show-desc url path` or similar)
- allow a data description to be used in `dvc get` and `dvc import` as a filter, so only data that matches the description gets downloaded / imported

The primary goal of these suggestions is to provide `dvc` with some kind of filter mechanism for data. This would allow data scientists to faster find data in a data registry.

---

At the same time it would be helpful to further organize the textual description of `--desc` so that it contains the following information in a structured way:

- (short) general description of the data content. 
- date when the data was added and/or modified (could be done automatically by dvc)
- name or author who added the data
- category of the data (e.g. text / image / pretrained model / etc.)
- flag or description whether the data is public or private (e.g. requires special permissions to get access on the storage account)
-  etc.

This could be done / provided in a `yaml` like fashion so that the resulting example `data.xml.dvc` could look like this:
```
 ➜ cat data.xml.dvc
outs:
- md5: a304afb96060aad90176268345e10355
  size: 37891850
  path: data.xml
  desc: 
     general: This is just a sample data file provided as xml. (text)
     added-by: Firstname, Lastname (text)
     added-date: 06.09.2021  (date)
     category: XML data (textual or enumeration)
     public: true/false (boolean)
```
