### ISSUE TITLE
params: bulk params from file

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6605]
Params need to be specified individually, which can be repetitive and inconvenient where users want to simply include all parameters from a file. 

For background, see:

* https://github.com/iterative/dvc/issues/3393#issuecomment-599896828
* https://github.com/iterative/dvc/discussions/6506#discussioncomment-1273357

Instead of specifying every parameter individually, it should be possible to do `dvc stage add foo -p my_params.yaml python foo.py` or `dvc stage add foo -p "my_params.yaml:*" python foo.py`, which could generate this `dvc.yaml`:

```yaml
stages:
  foo:
    cmd: python foo.py
    params:
    - my_params.yaml
```

or

```yaml
stages:
  foo:
    cmd: python foo.py
    params:
    - my_params.yaml:*
```

After running `dvc repro`, `dvc.lock` could treat `my_params.yaml` like a regular file dependency:

```yaml
stages:
  foo:
    cmd: python foo.py
    deps:
    - path: my_params.yaml
    - md5: abc123
```

However, commands that collect parameters to show info about them, like `dvc params diff` and `dvc exp show`, would parse `my_params.yaml` and show each individual parameter.
