### ISSUE TITLE
Make frozen field configurable

### ISSUE THREAD

**Issue by lefos99** [iterative/dvc#6989]
# Bug Report

## Issue name
Freeze a stage in `dvc.yaml` right now, it is not possible by using the `params.yaml`.

## Description
`PARAM_FROZEN` which is defined in `dvc/schema.py` [here](https://github.com/iterative/dvc/blob/master/dvc/schema.py#L20) and [here](https://github.com/iterative/dvc/blob/master/dvc/schema.py#L87), accepts only bool values for now.

That means that I can do the following:
```yaml
# dvc.yaml
  train:
    cmd: PYTHONPATH='../../.' python3 training/run_train.py
    frozen: true
```

But I cannot have something like this:
```yaml
# params.yaml
model:
  freeze: false
```

```yaml
# dvc.yaml
  train:
    cmd: PYTHONPATH='../../.' python3 training/run_train.py
    frozen: ${model.freeze}
```
which gives me the following error:
```
ERROR: 'dvc.yaml' format error: extra keys not allowed @ data['stages']['train']['cmd']
```

### Reproduce
If you define any stage with the following format, you will get the error:
```yaml
# params.yaml
model:
  freeze: false
```

```yaml
# dvc.yaml
  train:
    cmd: PYTHONPATH='../../.' python3 training/run_train.py
    frozen: ${model.freeze}
```

### Expected
I would expect this `frozen` parameter to be configurable by defining `PARAM_FROZEN` in [here](https://github.com/iterative/dvc/blob/master/dvc/schema.py) in  a way like
`StageParams.PARAM_FROZEN: Any(str, bool)` instead of just `StageParams.PARAM_FROZEN: bool`.

I tried this locally and it solved my issue by the way.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.4.0-90-generic-x86_64-with-glibc2.10
Supports: http, https, ssh
Cache types: symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme1n1p6
Repo: dvc, git
