### ISSUE TITLE
dvc.yaml created on Windows does not work on Linux

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#7056]
# Bug Report
Creating a `dvc.yaml` file with `dvc run` on windows will use `\` for directory seperation while on linux based systems `/` is required.
This can cause issues, e.g. using `dvc run` on a windows machine and then pushing to GIT and use CI/CML to process.

Example:

```yaml
stages:
  Simulation:
    cmd: "python -c \"from main import Simulation; Simulation(load=True, name='Simulation').run()\"\
      \ "
    outs:
    - data
    - nodes/Simulation/outs.json
```

vs.

```yaml
stages:
  Simulation:
    cmd: "python -c \"from main import Simulation; Simulation(load=True, name='Simulation').run()\"\
      \ "
    outs:
    - data
    - nodes\Simulation\outs.json
```

DVC is not able to reproduce the stages for at least outs and deps

```sh
Running stage 'Simulation':
> python -c "from main import Simulation; Simulation(load=True, name='Simulation').run()" 
ERROR: failed to reproduce 'dvc.yaml': output 'nodes\Simulation\outs.json' does not exist
```

### Reproduce

Either create a `dvc.yaml` on windows and run on linux or replace `\` with `/` and run on a linux machine.

### Expected

With DVCs goal of being `Language- & framework-agnostic` it would be helpful when DVC converts the paths to work with the OS where `dvc repro` is called and is independent of the OS where `dvc run` is called.

### Environment information

Tested with `dvc 2.8.3` on Windows 10 and Linux was a ubuntu-latest via a GitHub action runner.

### Proposed Fix

DVC could use `pathlib.Path` to convert any path to the path style required by the OS.
