### ISSUE TITLE
Runner friendly progress output

### ISSUE THREAD

**Issue by mevatron** [iterative/dvc#7076]
I am testing out `cml-runner` with Gitlab CI/CD pipelines, and I don't seem to get any of the tqdm progress in the gitlab-runner logs. I only see `dvc pull` until it is complete. I did try `dvc pull -v`, and that does result in lots of output, but filled up the gitlab-runner 4MB default log buffer quite quickly :smile: 

My current pipeline setup looks like so:
```yaml
stages:
  - deploy
  - train

deploy:
  stage: deploy
  when: always
  image: iterativeai/cml:0-dvc2-base1
  script:
    - cml-runner
      --cloud aws
      --cloud-region us-east
      --cloud-type p3.2xlarge
      --cloud-hdd-size 64
      --labels=cml-gpu

train:
  stage: train
  needs: [deploy]
  tags:
    - cml-gpu
  image: iterativeai/cml:0-dvc2-base1-gpu
  script:
    - dvc pull
    - pip install -r requirements.txt
    - dvc repro
```

Unfortunately, my dataset takes about an hour to pull into the runner :sweat_smile:, so having some intermittent pull progress would be great! I certainly understand if tqdm linefeeds cause issues with the runners, but maybe different verbose modes that print intermittently would be cool?
