### ISSUE TITLE
plots: flexible dvc.yaml spec

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7086]
YAML doesn't permit dup keys also even if we change that to arrays we will have the issue of duplication and discrepancy, i.e. one template under one key and another one under the second key. So plot names should be unique string, whichever you write in target I suppose and datafile should go as key. We may still use a key if `datafile` is absent, this will simplify a very common one file case. So:
```yaml
plots:
- train_vs_val:
    x: epoch
    y: loss
    data: [train_loss.csv, val_loss.csv]


- val_f1.csv:
    x: epoch
    y: [f1_class_0, f1_class_1]
    y_label: f1
    # data is absent, using key value: val_f1.csv

# Separately plot since we have TWO plots, even though with the same data file
- scores_acc:
    x: epoch
    y: acc
    data: scores.csv
- scores_auc:
    x: epoch
    y: auc
    data: scores.csv
```

_Originally posted by @Suor in https://github.com/iterative/dvc/discussions/5980#discussioncomment-1026072_

**Comment by dberenbaum** [comment]
@pared I think it makes sense to implement in reverse order of how it's listed above.

1. Multiple plot specs from the same file:

```
# Separately plot since we have TWO plots, even though with the same data file
- scores_acc:
    x: epoch
    y: acc
    data: scores.csv
- scores_auc:
    x: epoch
    y: auc
    data: scores.csv
```

Requirements:
* Have a way to define plots spec separate from a stage output.
* Add an optional `data` field to specify file, in which case plot key is used as a title.
* Update plots commands.
* Nice to have: `dvc plots add` command to generate plots.


2. Multiple series per axis:

```
- val_f1.csv:
    x: epoch
    y: [f1_class_0, f1_class_1]
    y_label: f1
    # data is absent, using key value: val_f1.csv
```

Requirements:
* Enable `x`, `y`, `x-axis`, and `y-axis` fields to be arrays.
* Show multiple lines/series in plots.
* Support diffs of multi-series plots -- most likely as a facet grid.

3. Multiple files within one plot:

```
- train_vs_val:
    x: epoch
    y: loss
    data: [train_loss.csv, val_loss.csv]
```

Requirements:
* Enable `data` field to be an array.
* Show multiple lines/series in plots and support diffs (similar to above).
* Out of scope: `x` or `y` field arrays combined with `data` array. This can throw an error.

**Comment by pared** [comment]
Questoin: can we provide parallel coordinates plots config alongside/inside plots spec?

**Comment by mattlbeck** [comment]
Related: #6316

**Comment by dberenbaum** [comment]
> Question: can we provide parallel coordinates plots config alongside/inside plots spec?

IMO let's not worry about it as part of this issue.

**Comment by daavoo** [comment]
Commenting here to not pollute https://github.com/iterative/dvc/pull/7477 with things that are not implementation-related.

The following syntax is currently supported in the P.R. and can cover all 3 use cases [above](https://github.com/iterative/dvc/issues/7086#issuecomment-985640176):

```
plots:
  scores_acc:
    x: epoch
    y: 
      scores.csv: acc
  scores_auc:
    x: epoch
    y: 
      scores.csv: auc
```

```
val_f1:
    x: epoch
    y: 
      val_f1.csv: acc
      val_f1.csv: loss
    y_label: f1
```

```
- train_vs_val:
    x: epoch
    y: 
      train_loss.csv: loss
      val_loss.csv: loss
```

I'm missing the reasoning behind adding the `data` field. The above syntax looks more intuitive to me.

cc @dberenbaum @pared

**Comment by dberenbaum** [comment]
@daavoo I find them about equally intuitive, although getting rid of `data` obviously is fewer fields to manage.

I can see two distinctions using `data`:

1. It impacts the legend (compare the left and right legends below). Should we strip common field names (`acc`) from the legend in this case?

<img width="1083" alt="Screen Shot 2022-05-12 at 11 32 50 AM" src="https://user-images.githubusercontent.com/2308172/168116700-a232c8f0-1043-4436-928d-fde6e2d0235f.png">

2. Should we support an x-axis from one file and y-axis from another file? For example:

```
plots:
  confusion:
    x: actual
    y: predicted
    data:
    - dir/actual.csv
    - dir/preds.csv
    template: confusion
```

Currently, this will produce two separate confusion matrices, which isn't what I want.

It won't work at all AFAIK without `data`, but maybe it could be supported like this:

```
plots:
  confusion:
    x: 
      dir/actual.csv: actual
    y:
      dir/preds.csv: predicted
    template: confusion
```

Thoughts @pared @daavoo?

**Comment by daavoo** [comment]
> although getting rid of data obviously is fewer fields to manage

And less code to maintain.

> it impacts the legend and axes

I think we should just remove data and iterate on the UI for legends.

> but maybe it could be supported like this:
> 
> plots:
>   confusion:
>     x: 
>       dir/actual.csv: actual
>     y:
>       dir/preds.csv: predicted
>     template: confusion

I would prefer this new syntax.

> Thoughts @pared @daavoo?

I would vote for getting rid of `data`. 

About the `x-axis` flexibility, I don't really know. How hard would it be if we focus on the explicit `{path}:{entry}` syntax @pared ? 
If it changes too many things, we could leave all this as a future follow-up. There are already a lot of new use cases we are covering with the current state of the P.R.

**Comment by pared** [comment]
AFAIR it should be not that big of a problem, we already have underlying logic. Just need to modify it a little bit. At least for `y`. `x` did not have this logic till now but still, I think we should be able to handle that. Currently I need to kind of search for x and handle situations when the particular column is not in the targeted files. With explicit `x` that would be easier, I think.

**Comment by dberenbaum** [comment]
So how does this look for updated syntax of the original comment at the top of this issue?

```yaml
plots:
- train_vs_val:
    x: 
    - train_loss.csv:epoch
    - val_loss.csv:epoch
    y: 
    - train_loss.csv:loss
    - val_loss.csv:loss

- val_f1.csv:
    x:
    - epoch
    - epoch
    y:
    - f1_class_0
    - f1_class_1
    y_label: f1
    # data source is absent, using key value: val_f1.csv

# Separately plot since we have TWO plots, even though with the same data file
- scores_acc:
    x: scores.csv:epoch
    y: scores.csv:acc
- scores_auc:
    x: scores.csv:epoch
    y: scores.csv:auc
```

It is more verbose, but I like that it's more clear and explicit. My only question would be to what extent to allow shortcuts and try to infer expected behavior. For example:

* If you specify the data source for only one of `x` or `y`, should dvc try to infer it for the other?
* In the `val_f1.csv` example, do you actually need to specify the `x` value twice?
 
I don't mind requiring everything to be listed explicitly for now since it does make behavior more clear.

**Comment by skshetry** [comment]
Another suggestion, that clearly separates plot level metadata with props, it's a bit verbose though.
```yaml
plots:
  train_vs_val:
    title: title
    props:
    - path: train_loss.csv  # or, train_loss.csv:epoch as proposed above
      key: epoch
      type: x
    - path: val_loss.csv
      key: epoch
      type: x
      label: f1
```

**Comment by dberenbaum** [comment]
@pared and I discussed and came up with the following action points:
 
* Remove `data` field support.
* Add new issue for `x` path support.
* Add new issue for CLI support.
* Check that syntax is consistent with params.

**Comment by dberenbaum** [comment]
@pared The example above in https://github.com/iterative/dvc/issues/7086#issuecomment-1121506619 uses file paths as dict keys under `y`, which doesn't work in one of the examples:

> ```
> val_f1:
>     x: epoch
>     y: 
>       val_f1.csv: acc
>       val_f1.csv: loss
>     y_label: f1
> ```

This will raise a duplicate keys error. Should it instead support a list of values here (note that this isn't supported today)?

```yaml
plots:
  scores_acc:
    x: epoch
    y: 
    - scores.csv: 
      - acc
  scores_auc:
    x: epoch
    y: 
    - scores.csv:
      - auc
```
 
```
val_f1:
    x: epoch
    y: 
    - val_f1.csv:
      - acc
    - val_f1.csv:
      - loss
    y_label: f1
```
 
```
train_vs_val:
    x: epoch
    y: 
    - train_loss.csv:
      - loss
    - val_loss.csv:
      - loss
```

This would be consistent with how `y` works without paths since it expects a list if there are multiple `y` values, and it would be similar to how stage parameters are handled:

```yaml
stages:
  train:
    cmd: python train.py
    params:
    - config.yaml:
      - alpha
      - beta
    outs:
    - model.h5
```
