### ISSUE TITLE
Support .cfg extension in parameters files

### ISSUE THREAD

**Issue by gitdoluquita** [iterative/dvc#7122]
Hey there folks!

I'm using DVC for a Spacy project and, since v3 of Spacy, all the params of the model are stored in a `config.cfg` file, as explained [here](https://spacy.io/usage/training#config) and [here](https://spacy.io/api/cli#train).
I thought that would be nice to use the `config.cfg` as a parameters file, the same way as we can use a `.toml` or `.yaml`. Example:
```yaml
  train:
    cmd: python -m spacy train config.cfg
    deps:
      - data/inter/train_legal_ner.spacy
      - data/inter/dev_legal_ner.spacy
    params:
      - config.cfg:
        - training.max_steps
        - training.dropout
```

This maybe would, even, affect the [Spacy integration with DVC](https://spacy.io/usage/projects#dvc) that right now doesn't use the params option.

I would be glad to help with any other information, and, with some tips, try to implement this .cfg parser.
Thank you in advance.
