### ISSUE TITLE
flatten `deps`  to facilitate more flexible templating

### ISSUE THREAD

**Issue by itcarroll** [iterative/dvc#7151]
The templating feature currently admits little flexibility for stage keys (e.g. `deps`) that expect lists. As a result, `foreach` stages cannot be given a variable number of dependencies. Causing lists to be flattened would make templating more powerful. For example, you could give extra dependencies to certain templated stages:

```
stages:
  build:
    foreach:
      us:
        deps:
      uk:
        deps:
        - uk_data
    do:
      cmd: myscript ${key}
      deps:
      - myscript
      - ${item.deps}
```

I have implemented the change at https://github.com/itcarroll/dvc/blob/feature/flattened-deps/dvc/dependency/__init__.py#L52, by (non-recursive) list [flattening](https://github.com/itcarroll/dvc/blob/feature/flattened-deps/dvc/dependency/__init__.py#L21-L26) in `dvc.dependency.loads_from`. I am sure it's not the right way to do it, and probably has unintended consequences, but it demonstrates the concept (and no tests failed).

I don't know how templating responds to missing keys, but not having to include the empty list for `us` would be even more better.

**Comment by itcarroll** [comment]
In ancient [discussions](https://discord.com/channels/485586884165107732/485596304961962003/823689452269994025) on `foreach` I found a suggestion (by @jorgeorpinel):

> I wonder actually if you can just do deps: ${list} (a list from params.yaml) 

This would add the same flexibility I'm interested in with the above, but it fails YAML validation, which appears to require `deps` to get a list before `${item}` is expanded. So, some change in the validation process might be an alternate route to this feature.

**Comment by alealv** [comment]
Hi, I'm also interested in this feature https://discord.com/channels/485586884165107732/485596304961962003/946817686220984350

```yaml
   data:
    foreach:
      librispeech:
        script: libri.sh
        links:
          - https://www.openslr.org/resources/12/dev-clean.tar.gz
          - https://www.openslr.org/resources/12/dev-other.tar.gz
          - https://www.openslr.org/resources/12/test-clean.tar.gz
          - https://www.openslr.org/resources/12/test-other.tar.gz
          - https://www.openslr.org/resources/12/train-clean-100.tar.gz
          - https://www.openslr.org/resources/12/train-clean-360.tar.gz
          - https://www.openslr.org/resources/12/train-other-500.tar.gz
      tedlium:
        script: tedlium.sh
        links:
          - https://www.openslr.org/resources/51/TEDLIUM_release-3.tgz
    do:
      cmd:
        - ./proc/${item.script} --output ${nas_data_dir}/${key} --tmp ${nas_data_dir} ${item.links}
      deps:
        - ${item.script}
        - ${item.links}
      outs:
        - data/${key}/${key}_text
        - data/${key}/${key}_utt2spk
        - data/${key}/${key}_wav.scp
        - data/${key}/${key}_waves
```

I have stages that have different list lengths
