### ISSUE TITLE
dvc repro keeps adding target files with brackets to .gitignore

### ISSUE THREAD

**Issue by achimgaedke** [iterative/dvc#7274]
# Bug Report

To reproduce:

Create a dvc repo with a single `dvc.yaml` file

```
stages:
    with-brackets:
        cmd:
            echo "yes" > all\[lovely\]people.txt
        outs:
            - all[lovely]people.txt
             
    without-brackets:
        cmd:
            echo "hi!" > all-welcome.txt
        outs:
          - all-welcome.txt
```

Run `dvc repro -f` multiple times and the `.gitignore` file will become longer and longer (here only 2 executions):

```
/all\[lovely\]people.txt
/all-welcome.txt
/all\[lovely\]people.txt
```

I'd expect the `/all\[lovely\]people.txt` line added only once, just like the `/all-welcome.txt` line.

This was observed on an ubuntu-20.04 system with 

```
dvc version
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.9.9 on Linux-5.11.0-1025-aws-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
```

and

```
git --version
git version 2.25.1
```
