### ISSUE TITLE
Verifying data sources in stage

### ISSUE THREAD

**Issue by sha-cmd** [iterative/dvc#7336]
When we have a lot of data, it seems to me that DVC does not present the action of :

* Suspend verifying data sources in stage
* While accessing to data (.dvc) in some experiments.

I think it should be of a great help (in question of time) to add the propriety of deps in dvc.yaml, for accessing to .dvc data in experiments, with the capacity of  deactivated the check of the integrity of the data as meta does in dvc.yaml file during runs.

Thanks for your concern. I failed in using meta data file (.dvc ones) in my experiments with dvc.

**Comment by dberenbaum** [comment]
Hi @sha-cmd! I see you were looking for help here and in [discord](https://discord.com/channels/485586884165107732/485596304961962003/938726047065726996). Would you mind providing some more details about your workflow, your dvc setup, and the exact commands that are causing you problems?

**Comment by sha-cmd** [comment]
![dvc_stage](https://user-images.githubusercontent.com/61082102/152497067-3a0c871d-5fea-4bf9-b651-29e37031af83.png)

This picture is a short description of my error. When I use meta in dvc.yaml to link a huge amount of data (pictures) that is add in one .dvc file then committed and even pushed in local dvc repository, I only can do dvc run or dvc repro, but I can’t do dvc exp, because the data are not accessible from the experiment space.

**Comment by dberenbaum** [comment]
Thank you for the additional details!

> When I use meta in dvc.yaml to link a huge amount of data (pictures) that is add in one .dvc file then committed and even pushed in local dvc repository

Do you mean the `meta` field in `dvc.yaml`, or metadata in general? The `meta` field is ignored by DVC and is only relevant for your own reference, so this should not have any impact on any issues you are experiencing.

> I only can do dvc run or dvc repro, but I can’t do dvc exp, because the data are not accessible from the experiment space

Could you provide the actual `dvc.yaml` or some sanitized version of it (or just the stage that's causing trouble)? Where are the dependencies located, and are they tracked by DVC?

Also, are you queuing the experiments? If possible, could you provide the verbose output of the entire command or set of commands, like `dvc exp run -v`?

**Comment by sha-cmd** [comment]
I do mean meta as the field in dvc.yaml. 

I have chosen meta instead of deps because I wanted to avoid the check of the integrity because computing hashes is not relevant in that case, cause I have 12 Go of photos (of a driving session with a car in many cities). 

But I need them as a dependence to make dvc experiments. I’m queuing those experiments, I launch them with ```dvc exp run --run-all```, I’ll give the script of generating of the experiments queue (and the dvc.yaml file) below and right now in fact.

```yaml
stages:
  octagones:
    cmd: python src/prepare_polygons.py

  brush-work:
    cmd: python src/prepare_masks.py

  k2000:
    cmd: python src/deeplabv3_plus.py --type dl
    meta:
    - data
    params:
    - k2000.epochs
    metrics:
    - k2000.json:
        cache: false
        persist: true
    outs:
    - models/k2000:
        cache: false
        persist: true
        desc: modeling of the segmentation of images of Cityscapes.
    - k2000/mIoU_density.jpg:
        cache: false
        persist: true
    - k2000/Dice_coefficient_density.jpg:
        cache: false
        persist: true
    plots:
    - k2000/mIoU.csv:
        cache: false
        persist: true
        title: mIoU k2000
        x: pics
        y: mIoU
    - k2000/Dice_coefficient.csv:
        cache: false
        persist: true
        title: Dice Coefficient k2000
        x: pics
        y: Dice_coefficient
    - k2000/accuracy_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Accuracy k2000
        template: multi_loss
        x: epoch
        y: accuracy
    - k2000/loss_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Loss k2000
        template: multi_loss
        x: epoch
        y: loss

  dolorean:
    cmd: python src/U-Net_Xception.py --type dl
    meta:
    - data
    metrics:
    - dolorean.json:
        cache: false
        persist: true
    outs:
    - models/dolorean:
        cache: false
        persist: true
        desc: modeling of the segmentation of images of Cityscapes.
    - dolorean/mIoU_density.jpg:
        cache: false
        persist: true
    - dolorean/Dice_coefficient_density.jpg:
        cache: false
        persist: true
    plots:
    - dolorean/mIoU.csv:
        cache: false
        persist: true
        title: mIoU dolorean
        x: pics
        y: mIoU
    - dolorean/Dice_coefficient.csv:
        cache: false
        persist: true
        title: Dice Coefficient dolorean
        x: pics
        y: Dice_coefficient
    - dolorean/accuracy_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Accuracy dolorean
        template: multi_loss
        x: epoch
        y: accuracy
    - dolorean/loss_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Loss dolorean
        template: multi_loss
        x: epoch
        y: loss
```

```python
from random import choice
from tools import optim_pool

num_exps = 21
seed(randint(1, 1000))
rand_nb = random

for n in range(num_exps):
    params = {
        "optimizer": choice(list(optim_pool().keys())),
        "learning_rate": choice([0.001, 0.0005, 0.00001]),
        "wce_beta": round(rand_nb(), 2),
        "bce_beta": round(rand_nb(), 2)
    }
    subprocess.run(["dvc", "exp", "run", "k2000", "-f", "--queue",
                    "--set-param", f"k2000.learning_rate={params['learning_rate']}",
                    "--set-param", f"k2000.optim_type={params['optimizer']}",
                    "--set-param", f"k2000.wce_beta={params['wce_beta']}",
                    "--set-param", f"k2000.bce_beta={params['wce_beta']}",
                    ])

    subprocess.run(["dvc", "exp", "run", "dolorean", "-f", "--queue",
                    "--set-param", f"dolorean.learning_rate={params['learning_rate']}",
                    "--set-param", f"dolorean.optim_type={params['optimizer']}",
                    "--set-param", f"dolorean.wce_beta={params['wce_beta']}",
                    "--set-param", f"dolorean.bce_beta={params['wce_beta']}",
                    ])
```
