### ISSUE TITLE
unroll an array of values for dvc repro

### ISSUE THREAD

**Issue by Rusteam** [iterative/dvc#7369]
When we run `foreach .. do ...` for items in an array inside `dvc.yaml` , we might want to join results of each `do` into one.
It would be nice to be able to unroll the array instead of adding each item separately.

Now I do this:
```
vars:
  - datasets:
     - one
     - two
     - three

stages:
  prep:
    foreach: ${datasets}
    do:
      cmd: python main.py prep ${item}
      outs:
       - data/processed/{item}
  join:
    cmd: python main.py merge ${datasets[0]} ${datasets[1]} ${datasets[2]}
    deps:
      - data/processed/${datasets[0]}
      - data/processed/${datasets[1]}
      - data/processed/${datasets[2]}
```
Obviously this leads to errors when we forget to update `join` stage after updating `datasets` variable.

We can have an option to unroll an array like this:
```
join:
    cmd: python main.py merge ${...datasets}
    deps:
      -  data/processed/
```
