### ISSUE TITLE
dvc repro --pull: does not pull the data but rather throws an error

### ISSUE THREAD

**Issue by francesco086** [iterative/dvc#7420]
# Bug Report

## Description

The command does not pull the data. If I first run `dvc pull` and then `dvc repro` everything works fine.

### Reproduce

1. clone project with this dvc.lock file (I omit the dvc.yaml file as it is obvious from this):
```yaml
schema: '2.0'
stages:
  prepare:
    cmd: ccs-prepare-trip-and-carrier-files --d4s-carriers-input-file-path=../curated-data/carriers.parquet
      --itms-trips-input-file-path=../curated-data/itms_trips.parquet --carriers-output-file-path=prepare/carriers.parquet
      --trips-output-file-path=prepare/trips.parquet
    deps:
    - path: ../curated-data/carriers.parquet
      md5: f986f68adf848bd94417c7fb70ebb6c0
      size: 16649304
    - path: ../curated-data/itms_trips.parquet
      md5: 505169e3e9c22a4a343f91ed945ad4f0
      size: 99230362
    outs:
    - path: prepare
      md5: 83ff1c7bc858643cd19cbfd7fa00260f.dir
      size: 42710154
      nfiles: 2
  elaborate:
    cmd: mkdir elaborate; wc -l prepare/carriers.parquet > elaborate/wcl.txt; wc -l
      prepare/trips.parquet >> elaborate/wcl.txt
    deps:
    - path: prepare/carriers.parquet
      md5: 720d1597378b2b41b4bcdec723b0f0c5
      size: 4177444
    - path: prepare/trips.parquet
      md5: 4d14501ebead5d1ebdc342eac1bf7ea2
      size: 38532710
    outs:
    - path: elaborate
      md5: 875dceddee991845ac5f33608d5e42ab.dir
      size: 65
      nfiles: 1
 ```
2. dvc repro --pull
3. get this error:
```
Verifying data sources in stage: '../curated-data/carriers.parquet.dvc'
ERROR: failed to reproduce '../curated-data/carriers.parquet.dvc': missing data 'source': ../curated-data/carriers.parquet
```

### Expected

Missing data source  ../curated-data/carriers.parquet should be pulled (or at least attempted to be downloaded).

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.5 (brew)
---------------------------------
Platform: Python 3.9.10 on macOS-11.6.4-x86_64-i386-64bit
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.1.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Additional Information (if any):**

As mentioned, if I run `dvc pull` and then `dvc repro` everything works fine.
