### ISSUE TITLE
dvc import: Cannot import file generated by foreach loop

### ISSUE THREAD

**Issue by mipo57** [iterative/dvc#7454]
# Bug Report

## dvc import: Cannot import file generated by foreach loop

Hi, I have 2 projects that use DVC
- wiki34 <-- this repo contains dataset generation code
- experiments <-- this repo contains code that runs experiments

I try to import one of the files generated in wiki34 repo to experiments repo
```bash
dvc import git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git dataset/split/train.jsonl
```
However, I get
```
Importing 'dataset/split/test.jsonl (git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git)' -> 'test.jsonl'
ERROR: failed to import 'dataset/split/test.jsonl' from 'git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git'. - failed to parse 'vars' in 'dvc.yaml': 'params.yaml' does not exist
```

The file is generated in wiki34 with following pipeline:
```yaml
stages:
  unzip:
    deps:
      - dataset/raw.zip
    outs:
     - dataset/raw:
        cache: False
    cmd: >-
      unzip -o -d dataset/ dataset/raw.zip

  preprocess:
      foreach:
        - test
        - train
      do:
        cmd: >-
          python scripts/preprocess.py
          --dataset_path dataset/raw/${item}
          --saving_name ${item}
          --output_dir dataset/split
        outs:
          - dataset/split/${item}.jsonl
        deps:
          - scripts/preprocess.py
          - dataset/raw/${item}

  merge:
    deps:
      - dataset/split/train.jsonl
      - dataset/split/test.jsonl
    outs:
      - dataset/${saving_name}.jsonl
    cmd: >-
      clarin-dataset merge 
      dataset/split/train.jsonl
      dataset/split/test.jsonl
      --output dataset/${saving_name}.jsonl

  sample:
    deps:
      - dataset/${saving_name}.jsonl
    outs:
      - dataset/${saving_name}-sample.jsonl:
          cache: False
    cmd: >-
      clarin-dataset sample dataset/${saving_name}.jsonl
      --max-samples ${sample_size}
      --output dataset/${saving_name}-sample.jsonl

  compute_metrics:
    cmd: clarin-dataset metrics dataset/${saving_name}.jsonl
    deps:
      - dataset/${saving_name}.jsonl
    outs:
      - METRICS.md:
          cache: False
      - images/metrics:
          cache: False
```
with following params.yaml file:
```yaml
saving_name: wiki34
sample_size: 10
```

However, when I do
```
dvc import git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git dataset/split
```
everything works fine.

I did a little debugging, and I added print to this funciton: https://github.com/iterative/scmrepo/blob/330bce52c922009e608c6e3dcc16f23e5f09ff18/scmrepo/fs.py#L111
so it looks like this:
```python
def exists(self, path: str, **kwargs: Any) -> bool:
        print("#########")
        key = self._get_key(path)
        print(key)
        print(self.trie.exists(key))
        return self.trie.exists(key)
```
Then, after executing 
```bash
dvc import git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git dataset/split/train.jsonl
```
in experiments repo, I got:

```
Importing 'dataset/split/train.jsonl (git@my.gitlab.server.eu:semantictextclustering/datasets/wiki34.git)' -> 'train.jsonl'
#########                                                                                                                           
('.dvc', 'config')
True
#########
('dvc.yaml',)
True
#########
('.dvcignore',)
True
#########
('.dvcignore',)
True
#########
('dvc.yaml',)
True
#########
('dvc.lock',)
True
#########
('params.yaml',)
True
#########)
True
#########
('dvc.yaml',)
True
#########
('.dvcignore',)
True
#########
('.dvcignore',)
True
#########
('dvc.yaml',)
True
#########
('dvc.lock',)
True
#########
('params.yaml',)
True
#########
('..', '..', 'data5', 'mpogoda', 'worktrees', 'semantictextclustering', 'experiments', 'sweeper', 'params.yaml')
False
```

So it looks like, for some reason, it checks for a existence params.yaml file from **experiments** in wiki34 repo, ad - because it obviously is outside of wiki34 repo, it fails.

The structure of experiments repo does't seem to matter, as I can reproduce this bug on a simple empty dvc project.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.10 on Linux-5.4.0-96-generic-x86_64-with-glibc2.27
Supports:
        hdfs (fsspec = 2022.2.0, pyarrow = 3.0.0),
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdf1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sdf1
```
