### ISSUE TITLE
Adding/Removing parameters with dvc exp run -S

### ISSUE THREAD

**Issue by RBMindee** [iterative/dvc#7476]
Hi all,

First I'd like to thank you for that awesome tool, which does marvel in our team.

I am not entirely sure if it is me misusing the tool or a missing feature, but I came across the following issue.

I have a params.yaml file, containing model configuration set as parameter in dvc.yaml stages. I can have two different types of configurations (this is a toy example).
 
```
# params.yaml : version 1
model:
  type: MLP1
  hidden: 128

# params.yaml : version 2
model:
  type: MLP2
  hidden1: 128
  hidden2: 128
```
During stage creation I used `dvc stage add -n mystage ... -p model ...`

I can switch from one to the other easily if I do it manually, but I do not know if it's possible to switch between the two versions using the `-S` argument of `dvc exp run`. For example if I am in the version two, dvc complains if I run `dvc exp run -S model.type=MLP1 model.hidden=256` because model.hidden does not exist.

Is there a clean way to do that ? or shall I always do stuff manually ? Basically, how can I switch model easily ?
Thank you very much

**Comment by dtrifiro** [comment]
Hey, I'm not sure I understand the issue completely, so I'll make an example here:

Let's assume you have `params.yaml`:
```yaml
model:
  type: MLP1
  hidden: 128
```

then you can run an experiment with a different hidden parameter: `dvc exp run -S model.hidden=256`.

Assume now you want to add a parameter: you have to modify `params.yaml` adding the new parameter:
```diff
model:
  type: MLP1
-  hidden: 128
+  hidden1: 128
+  hidden2: 128
``` 
Don't forget to modify `dvc.yaml` by updating the `params` session of the appropriate stage accordingly.

Now you should be able to execute `exp run` with `newparam` set to different values using `dvc exp run -S model.hidden2=256`.

Note that you can also have multiple parameters file, and you can provide them using the following syntax: `dvc exp run -S params_new.yaml:model.hidden=256`, but you need to make sure the parameter names match the stage's `params` section in `dvc.yaml` .

Let me know if this helps!

**Comment by RBMindee** [comment]
Hi @dtrifiro and thank you for answering,
I'll make a more detailed example:
My code can handle two types of model, which take a different config. The first model is MLP1 and takes model.hidden. The second one is MLP2 and takes hidden1 and hidden 2. So I could have a `params.yaml` looking like this:
```
model:
  type: MLP1  # or MLP2
  hidden: 128  # relevant for MLP1 only
  hidden1: 128  # relevant for MLP2 only
  hidden2: 128  # relevant for MLP2 only
```
In my dvc.yaml, the parameter is the whole model block:
```
params:
    - model
```
In principle, that works fine on that toy example, for example, I can do `dvc exp run -S model.type=MLP2 -S model.hidden1=256 `

But there are to issues:
- If I change an irrelevant parameter manually (like hidden, when working with MLP1), then the whole pipeline will run again, which I want to avoid.
- When working with bigger configuration, this while quickly become a mess. Thus my program allows only to versions of the `params.yaml` file:
First version, corresponding to model MLP1
```
model:
  type: MLP1  # MLP2 will fail if only hidden is given
  hidden: 128
```
Second version, corresponding to model MLP2
```
model:
  type: MLP2  # MLP1 will fail if only hidden1 and hidden2 are given
  hidden1: 128 
  hidden2: 128 
```
That works perfectly fine, but I have to manually do all the changes to switch from model 1 to model 2., as I cannot do it simply with `dvc exp run -S ...`.
I was wondering what would be the clean way to do that ?

**Comment by RBMindee** [comment]
Hi again, I found a perfect solution and honestly I am impressed, I was really not betting that DVC could handle that.

Here is the thing: My `params.yaml` now looks like this:
```
model:
  type: MLP1
  MLP1:
    hidden_dim: 128
  MLP2:
    hidden_dim1: 256
    hidden_dim2: 128
```
That way, all config coexist and that's considerably cleaner.

The trick was that  some of that config does nothing. For example, while model.type=MLP1 those to command do the same thing:
```
dvc exp run -S model.MLP2.hidden_dim1=1
dvc exp run -S model.MLP2.hidden_dim1=1000
```
But there is the new templating feature to the rescue, I just did that in my `dvc.yaml`:
```
params:
    - model.type
    - model.${model.type}
```
Honestly, I was guessing that it would not work or break everything. At least dvc exp show would be broken, but no... everything works like a charm with one trivial line. Really nice !
