### ISSUE TITLE
exp init: Revisit `type="dl"`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#7534]
Once https://github.com/iterative/dvclive/issues/225 is solved, the `live` section will be deprecated in favor of using `metrics` and `plots`.

How should `exp init` behave when `type="dl"`?

**Comment by daavoo** [comment]
Would it make sense for `type="dl"` to generate:

```
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    metrics:
      - dvclive.json:
          cache: false
    plots:
      - dvclive/scalars:
          cache: false
```

Where `dvclive` would be replaced by the value passed to `--live` (if any) ?
