### ISSUE TITLE
dvc exp run unavailable in CML

### ISSUE THREAD

**Issue by datacubeR** [iterative/dvc#7547]
Is there any way to run DVC exp run in CML?

My use case includes training several experiments in a Cloud or self hosted Server and publish in the PR the results of my work. 

For now when trying to do this using the setup action I get an unexpected error.

I understand that commit hides experiment results and I read that CML is not intended for experimentation but that is not quite clear in official documentation.

**Comment by casperdcl** [comment]
(Transferred to DVC because it looks like a config/setup issue unrelated to CML)

**Comment by pmrowla** [comment]
@dacbd's suggestion should be correct, github's checkout action only fetches a single shallow commit by default, this isn't enough of the Git repo for `exp run` to work properly.

**Comment by dberenbaum** [comment]
@pmrowla Why does `exp run` require more than the baseline commit to be fetched?

**Comment by pmrowla** [comment]
> @pmrowla Why does `exp run` require more than the baseline commit to be fetched?

The issue is that we use `git merge` in experiments and doing a `merge-base` operation in git requires fetch depth > 1 (the specific required depth depends on the commits being merged).

For our purposes w/DVC experiments, a fetch depth of 2 will usually be sufficient (meaning that we need baseline commit + 1 direct parent if it exists), but that won't be the case 100% of the time. So if users are trying to use `exp run` inside github actions, the general solution is to use `fetch-depth: 0` (and not use a shallow clone at all).

**Comment by dberenbaum** [comment]
Thanks @pmrowla. I guess even if we tried to minimize operations where merge is needed, it will still be needed sometimes, and it's probably better to document the proposed workaround above. Opened https://github.com/iterative/dvc.org/issues/3416.

**Comment by casperdcl** [comment]
Ah right so the CML solution would be [`cml ci`](https://cml.dev/doc/ref/ci) (a bit better than `fetch-depth: 0`)

**Comment by dberenbaum** [comment]
If we go with the suggestion in https://github.com/iterative/dvc.org/issues/3416#issuecomment-1089866190, we should keep this open to update the message in DVC to be more informative and helpful. Even if DVC can't tell whether it's in a CI context, it could at least suggest to fetch missing commits and maybe link to docs that could go into more depth about specific use cases like cml.

**Comment by skshetry** [comment]
On the UI side, we could detect the presence of `CI`/`GITHUB_ACTIONS`/`GITLAB_CI` environment variables.

**Comment by pmrowla** [comment]
If we get the invalid commit exception we can just do the extra check to see whether or not we are in a shallow repo (you just have to check whether or not `.git/shallow` exists). This problem isn't specific to CI environments, it's just more likely to show up there since github uses shallow clones in CI by default.

**Comment by dberenbaum** [comment]
Right, I guess the question is whether the message should be general like "don't use a shallow clone" or more CI-specific like "try fetch-depth: 0"? I think probably the former is better even if we can detect CI, since we don't want to have to cover the syntax of different git server behaviors, although we could link to docs where that level of detail could be provided.

**Comment by dacbd** [comment]
+1 for a general message w/  link to docs for more specific details/solutions.

**Comment by skshetry** [comment]
> Right, I guess the question is whether the message should be general like "don't use a shallow clone" or more CI-specific like "try fetch-depth: 0"? I think probably the former is better even if we can detect CI, since we don't want to have to cover the syntax of different git server behaviors, although we could link to docs where that level of detail could be provided.

I'd prefer general message with a CI specific hint and link to the docs wherever possible. I'd prefer less redirection as much as possible.

Example:
```
dvc exp run
ERROR: Cannot run in a shallow-cloned repository

If you are using `actions/checkout`, please set `fetch-depth: 0` so that the repo is not shallow-cloned.
See https://dvc.org/doc/user-guide/troubleshooting#shallow-clone.
```

**Comment by datacubeR** [comment]
Dear all, 
Thanks for all of your answers. I think the spirit of good open source is havomng everyone really involved, and I really appreciate your help on trying to solve this issue. 

I implemented the steps mentioned above and it worked partially. Once I run the experiments it turns out git is not recognized in the Github Machine:

![image](https://user-images.githubusercontent.com/48638337/162589259-e6fb8ac9-0006-4fa0-9a13-a482c102c93d.png)

In order to solve this issue I found a really nice action here: `fregante/setup-git-user@v1`. This helps the remote machine make the connection with git in order to make `dvc run exp` to work.

The final workflow will be like this:

```yaml
name: experiments
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Experiment
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          #bash exp_file.sh
          dvc exp run -S train.C=0.005
          dvc exp run -S train.C=100

          echo "## Resultados del Experimento" >> report.md
          dvc exp show --only-changed --drop 'assets|src' --no-pager --md >> report.md

          cml send-comment report.md
```

I think this could be mentioned as a user-case in the documentation because is a very common experimentation workflow, and if we can externalize experimentation to a Github machine or a Cloud Runner would be very good.

On another note, I noticed iterative/setup-dvc@v1 doesn't include yaml package which is a dependency on DVC. So you have to make sure to add it to the requirements.txt otherwise DVC will complain. Of course, unless you think it's a good idea to add it in the action.

Thanks and hope this helps DVC,

Alfonso
