### ISSUE TITLE
DVC stages are disconnected

### ISSUE THREAD

**Issue by RadionBik** [iterative/dvc#7560]
# Bug Report

## Issue name

DVC stages are disconnected

## Description

I have been using DVC for a while in my repo and after recent refactoring I noticed this broken behavior: when doing `dvc repro` the stages are executed not in the order I want them to be.

here is the dvc.yaml:
```
stages:
  download_data:
    cmd: >-
      PYTHONPATH=../. python data/download.py
    deps:
      - data/query.sql
    outs:
      - artifacts/ocr_data.csv

  filter_and_split:
    cmd: >-
      PYTHONPATH=../. python data/filter_and_split.py
      deps:
        - data/filter_and_split.py
        - artifacts/ocr_data.csv
      outs:
        - artifacts/train.csv
        - artifacts/test.csv

  train_classifier:
    cmd: >-
      PYTHONPATH=../. python train.py
      --finalize_results=${experiment.finalize_results}
      --log_as_run_name="${experiment.log_as_run_name}"
    deps:
      - train.py
      - model.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/model.pkl
      - artifacts/confusion_matrix.csv
    metrics:
      - artifacts/classifier_metrics.json
    params:
      - experiment
      - sklearn_params
```

here is the output of `dvc dag`:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/19979628/162402789-7adc977c-6ca5-4990-a70a-5a8d5ae98e02.png">

### Reproduce

Have no idea how it happened and how to reproduce

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.5 (brew)
---------------------------------
Platform: Python 3.9.10 on macOS-12.3-x86_64-i386-64bit
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.1.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

```
