### ISSUE TITLE
plots: support for flexible x-axis values

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7754]
In https://github.com/iterative/dvc/issues/7086#issuecomment-1125169586, there are plots where it can be useful to specify the `x` source file separately from `y`. For example, if I keep the actual independent variable saved with my original data, but save the predictions for each model in a separate file, I might need something like:

```yaml
plots:
  confusion:
    x: 
      dir/actual.csv: actual
    y:
      dir/preds.csv: predicted
    template: confusion
```

We might also need to change `x` between files. For example, maybe I want to plot ROC and precision-recall on the same plot to see how they correlate:

```yaml
plots:
  roc_vs_prc:
    x:
      precision_recall.json: recall
      roc.json: fpr
    y:
      precision_recall.json: precision
      roc.json: tpr
```

Another use case for this would be if I named `x` differently between files, like:

```yaml
plots:
  train_vs_val:
    x:
      train_loss.csv: epoch
      val_loss.csv: step
    y: 
      train_loss.csv: loss
      val_loss.csv: loss
```
