### ISSUE TITLE
```dvc exp run --queue```: deleting file 'params.yaml' for each command call

### ISSUE THREAD

**Issue by alimagadovk** [iterative/dvc#7842]
# Bug Report

 dvc exp run --queue: deleting file 'params.yaml' for each command call

## Description

```dvc exp run --queue``` deletes file 'params.yaml' for each trial to add a new experiment and the experiment don't put into queue. It works correctly only if command ```git add params.yaml``` was called before.

### Reproduce

Example files:
test.py
```
import numpy as np
import json
import yaml

params = yaml.safe_load(open('params.yaml'))["test"]

precision = np.random.random()
recall = params['value']
accuracy = np.random.random()

rows = {'precision': precision,
        'recall': recall,
        'accuracy': accuracy}

with open(params['metrics_path'], 'w') as outfile:
    json.dump(rows, outfile)

fpr = 10*np.random.random((1,10)).tolist()
tpr = 10*np.random.random((1,10)).tolist()

with open('plot.json', 'w') as outfile2:
    json.dump(
      {
        "roc": [ {"fpr": f, "tpr": t} for f, t in zip(fpr, tpr) ]
      }, 
      outfile2
      )
```

params.yaml
```
test:
  metrics_path: scores.json
  value: 2
```

dvc.yaml
```
stages:
  test:
    cmd: python test.py
    deps:
    - test.py
    params:
    - test.metrics_path
    - test.value
    metrics:
    - scores.json:
        cache: false
    plots:
    - plot.json:
        cache: false
        x: fpr
        y: tpr
```

1. ```dvc exp run --queue -S test.value=101```

### Expected

New experiments adds to queue without 'params.yaml' deleting.

### Environment information

Ubuntu 20.04

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-5.13.0-40-generic-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p6
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/nvme0n1p6
Repo: dvc, git
```

**Additional Information (if any):**
