### ISSUE TITLE
support subfolders in the remote storage as the root storage for different projects

### ISSUE THREAD

**Issue by shelper** [iterative/dvc#7843]
I would like to maintain a central git repo that is for all the data registry information for multiple projects. I host my data on google cloud storage: `gs://bucket/dvc-datastore`, and I would like to have subfolders in this place for my projects, say:
`gs://bucket/dvc-datastore/project1`, `gs://bucket/dvc-datastore/project2`, etc.

to do this, with current dvc data registry, first i have the following `data.dvc` for each project
```
├── project1
│   └── data.dvc
└── project2
    └── data.dvc
```

then i need to add each of this project data folder as the remote storage so in my `.dvc/config`
```
['remote "project1-storage"']
    url = gs://bucket/dvc-datastore/project1
['remote "project2-storage"']
    url = gs://bucket/dvc-datastore/project2
```

and then based on my undertanding, when i need to pull data based on the `data.dvc` for each project, i need to specify the remote storage first. which is not so convinent, so I wonder if there could be a keyword like `remote-subdir` in the `data.dvc` for project 1
```
remote-subdir: project1
outs:
- md5: d751713988987e9331980363e24189ce.dir
  size: 1234
  nfiles: 123
  path: data
```
and for `.dvc/config` i only need the single remote
```
['remote "project1-storage"']
    url = gs://bucket/dvc-datastore/project1
```
now dvc knows for project1 it needs to go to `gs://bucket/dvc-datastore/project1` to get the data.

Did i miss anything if such feature is already offered by dvc?

**Comment by karajan1001** [comment]
You can have a `remote` file in your `outs` scope to set a special default remote place for it. Something like 

```
outs:
- md5: d751713988987e9331980363e24189ce.dir
  size: 1234
  nfiles: 123
  path: data
  remote: project1-storage
```

It is in our [docs](https://dvc.org/doc/user-guide/project-structure/dvc-files#dvc-files) but we haven't provide a CLI command to set this parameter.
