### ISSUE TITLE
plots diff: Show previous revisions for new plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7913]
If I add a new plot, `dvc plots diff` should be able to try to render previous revisions even if the plots were not configured in that revision.

For example, let's say I have plots data in `train.csv` for multiple revisions and then add a plot in `dvc.yaml`:

```yaml
stages:
  train:
    cmd: train
    plots:
    - train.csv:
        x: epoch
        y: loss
        title: stage_plots
```

`dvc plots diff` shows only the workspace, but it should also show the HEAD revision.
