### ISSUE TITLE
dvc.exceptions.CyclicGraphError: Pipeline has a cycle involving: load_extract_save.

### ISSUE THREAD

**Issue by Padmanabhan100** [iterative/dvc#7915]
```
stages:
  load_extract_save: 
    cmd: python src/stage_01_load_extract_save.py --config=config/config.yaml
    deps:
      - config/config.yaml
      - src/utils/all_utils.py
      - src/stage_01_load_extract_save.py
      - artifacts/data
    outs:
      - artifacts/data
      - artifacts/clean_data/X.npy
      - artifacts/clean_data/Y.npy

  train_test_split_save:
    cmd: python src/stage_02_train_test_split_save.py --config=config/config.yaml --params=params.yaml
    deps:
      - artifacts/clean_data/X.npy
      - artifacts/clean_data/Y.npy
      - src/utils/all_utils.py
      - params.yaml
      - config/config.yaml
      - src/stage_02_train_test_split_save.py
    outs:
      - artifacts/train_data/X_train.npy
      - artifacts/train_data/Y_train.npy
      - artifacts/test_data/X_test.npy
      - artifacts/test_data/Y_test.npy
  
  train_model:
    cmd:  python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - artifacts/train_data/X_train.npy
      - artifacts/train_data/Y_train.npy
      - artifacts/test_data/X_test.npy
      - artifacts/test_data/Y_test.npy
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/checkpoints
      - artifacts/model
  
  metrics:
    cmd: python src/stage_04_metrics.py --config=config/config.yaml
    deps:
      - src/stage_04_metrics.py
      - config/config.yaml
      - src/utils/all_utils.py
      - artifacts/test_data/X_test.npy
      - artifacts/test_data/Y_test.npy
      - artifacts/checkpoints
      - artifacts/model
    outs:
      - confusion_matrix.png
```

This is my dvc.yaml. 

I have created github workflows, but the run fails and is giving me this error - 2022-06-17 21:34:59,843 ERROR: Pipeline has a cycle involving: load_extract_save.

I have tried down grading the dvc module but nothing works.
