### ISSUE TITLE
dvc dag emits weird output

### ISSUE THREAD

**Issue by hholst80** [iterative/dvc#7945]
Playing around with a very simple pipeline. Obviously the double outs is causing some poor formatting of the dag graph:

```
stages:
  export:
    cmd: ./export-1
    outs:
    - P10000/export.jsonl
  preproc:
    cmd: ./preproc-2
    deps:
    - P10000/export.jsonl
    outs:
    - P10000/input.jsonl
    - P10000/final.jsonl
  predict:
    cmd: ./predict-3
    deps:
    - P10000/input.jsonl
    outs:
    - P10000/output.jsonl
  correction:
    cmd: ./corr-4
    deps:
    - P10000/output.jsonl
    - P10000/final.jsonl
    outs:
    - P10000/correction.jsonl
  stats:
    cmd: ./stats-5
    deps:
    - P10000/correction.jsonl
    outs:
    - P10000/stats.json

```

```
                              +---------------------------+               
                              | ../export/dvc.yaml:export |               
                              +---------------------------+               
                                            *                             
                                            *                             
                                            *                             
                             +----------------------------+               
                             | ../export/dvc.yaml:preproc |               
                             +----------------------------+               
                            ****                         *****            
                       *****                                  ****        
                    ***                                           *****   
+----------------------------+                                         ***
| ../export/dvc.yaml:predict |                                    *****   
+----------------------------+                                ****        
                            ****                         *****            
                                *****               *****                 
                                     ***         ***                      
                            +-------------------------------+             
                            | ../export/dvc.yaml:correction |             
                            +-------------------------------+             
                                            *                             
                                            *                             
                                            *                             
                              +--------------------------+                
                              | ../export/dvc.yaml:stats |                
                              +--------------------------+          
```

```
[root@hholst-dev export]# dvc version
DVC version: 2.11.0 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-5.18.6-200.fc36.x86_64-x86_64-with-glibc2.14
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.8),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.8),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
Cache types: reflink, hardlink, symlink
Cache directory: btrfs on /dev/vda5
Caches: local
Remotes: azure
Workspace directory: btrfs on /dev/vda5
Repo: dvc, git
```
