### ISSUE TITLE
Add exit code for pre-commit hook

### ISSUE THREAD

**Issue by ralphbird** [iterative/dvc#7978]
When running the pre-commit hook I would like it to fail if there are updates to files tracked by DVC, at the moment I get the status message but pre-commit completes and I cannot "force" people to run `dvc commit` prior to running `git commit`.  I can get the exit code from the command line via `dvc status -q` but not within pre-commit.  

Ideally I would like the hook to look something like, 

```yaml
  - repo: https://github.com/iterative/dvc
    rev: 2.12.0
    hooks:
      - id: dvc-pre-commit
        language_version: python3
        stages:
          - commit
        args:
          - -q
```

I don't need the status message (it would be nice but not a requirement), users can run `dvc status` to get that afterwards.
