### ISSUE TITLE
dvc metrics/plots diff local files

### ISSUE THREAD

**Issue by shortcipher3** [iterative/dvc#7993]
You can use git diff to compare to local files.

```
git diff [<options>] --no-index [--] <path> <path>
```

It would be nice to have the same functionality with `dvc`, for example I have a model and then a quantized model, since there are many ways to quantize a model I would like to have stages that take the original model and create the quantized model - so they belong in the same commit.

For reporting purposes and understanding I would like to show the change in the metrics/plots between the original model and the quantized model.

**Comment by karajan1001** [comment]
Also for model distillation.

**Comment by pared** [comment]
@shortcipher3 regarding the plots it should be already available in latest release:

```yaml
#dvc.yaml
stages: # <- note that plots is on the same level as stages
  ....
plots:
  quantized_vs_no_quantized:
    x: x_val
    y:
      quantized_data_file.json: metric_name
      non_quantized_data_file.csv: metric_column
    template: linear
    title: "Comparing quantized vs non quantized"
```
