### ISSUE TITLE
`dvc.api.params_show()`: returns all params for stage with no params

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8064]
# Bug Report

## Description

When using `dvc.api.params_show(stages="train")`, if there are no `params` for stage `train`, all of `params.yaml` will be returned.

### Reproduce

Use the following files:

```yaml
# dvc.yaml
stages:
  train:
    cmd: python train.py
    deps:
    - train.py
```

```yaml
#params.yaml
batch_size: 64
lr: 0.2
```

```python
# train.py
import dvc.api

print(dvc.api.params_show(stages="train"))
```

Running `python train.py` or `dvc repro/exp run` outputs `{'batch_size': 64, 'lr': 0.2}`.

### Expected

An error for no params found or an empty dict.
