### ISSUE TITLE
`dvc.yaml`: pipeline-less params and metrics

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8371]
`dvc.yaml` now supports a top-level `plots` section. Similar sections should be supported for `params` and `metrics`:

```yaml
plots:
  roc.json:
    ...
params:
  - data_path
  - train.lr
  - optimizer_config.json:
metrics:
  - metrics.json
```

Params and metrics should not be cached, but they should be collected during `params`/`metrics`/`exp` commands.

Along with #6746, this allows users to start tracking experiments without needing pipelines.

**Comment by dberenbaum** [comment]
None of these top-level sections should be treated as deps or outs. That way, they can overlap with pipelines without causing issues. 

For example, you could have a `dvc.yaml` file like:

```
stages:
  train:
    cmd: python train.py
    outs:
      - dvclive
```

And inside dvclive, you could have `dvclive/dvc.yaml` that looks like:

```
plots:
  - metrics/accuracy.tsv:
    ...
params:
  - params.yaml:
metrics:
  - metrics.json
```

**Comment by dberenbaum** [comment]
> Params and metrics should not be cached, but they should be collected during `params`/`metrics`/`exp` commands.

Note from the example above that this info should be collected recursively since the `dvc.yaml` files will often be in a subdirectory.

**Comment by skshetry** [comment]
One thing that I don't like about `params` is that it requires to much indentation.

```yaml
params:
  - my_params.yaml:
       - foo
       - bar
  - my_params2.yaml:
      - foo
      - bar
```

It is same as follows, but we expand them (and dvc is opinionated on how dvc.yaml is formatted).
```yaml
params:
  - my_params.yaml: [foo, bar]
  - my_params2.yaml: [foo, bar]
```

I feel the same way about the stage that there is just too much indentation. We are definitely locked on above syntax (since it's closer to what we already have), but if we want to improve dvcfile language, it'd be also better to consider this extra indentation issue (it is easier for defaults but harder for everything else due to lack of proper structure).

I was playing with schema, and came with below alternatives.
```
# Alternative 1
params:
- path: my_params.yaml
- path: my_params_sub_keys.yaml
  keys: [key1, key2]
- path: my_params_sub_keys.yaml
  keys: [key1, key2]

# Alternative 2
params:
- my_params.yaml
- my_params.yaml:key1,key2
- my_params3.yaml:key*

# alternative 3
params:
- my_params.yaml
- my_params_sub_keys.yaml:
    keys: [key1, key2]
```

I prefer 1, because it is consistent, but harder for defaults (we could hack and add string support for easier defaults).
With 2, we are creating our own syntax, and 3 is like our `outs` section, which also has too much indentation.
(In hindsight, anything that is not static should probably not be a key, but a value).

---

I work with dvc.yaml very less, so my personal feelings toward it may not be the same as users.
Most likely we will go with the same format as stage params, as it's familiar, but the over-indentation does bother me whenever I try to write.

**Comment by dberenbaum** [comment]
> Most likely we will go with the same format as stage params

Yeah, I think it's not worth trying to support a different syntax, although those would be good alternatives if we didn't already have something at the stage level.

> One thing that I don't like about `params` is that it requires to much indentation.

Agreed, but now that we support entire files, it bothers me less, since I think many times it simplifies to:

```
params:
  - my_params.yaml:
  - my_params2.yaml:
```

I'm not sure I can think of a good use case where you need granular top-level params actually. Maybe if you have one `params.yaml` but multiple `dvc.yaml` files?

**Comment by skshetry** [comment]
In Stage-level params, the strings are param-keys to be tracked from `params.yaml`, but I don't think we need to support that. The strings could be considered a file, and the granular support can be via key-value pair.

```yaml
params:
- completely_tracked_params1.yaml
- completely_tracked_params2.yaml:
- granularly_tracked_params.yaml:
  - key1
  - key2
```
