### ISSUE TITLE
`repro`: Cannot interpolate data of type 'list'

### ISSUE THREAD

**Issue by TheFirstMe** [iterative/dvc#8372]
This is a sample of my dvc.yaml.

```yaml
stages:
    train:
        cmd: python train.py --list ${base.list}
```

and my params.yaml looks like this:

```yaml
base:
    loglevel: INFO
    list: ['a', 'b', 'c']
    random_key: random_value
```

`dvc repro` currently results in this error:

```
ERROR: failed to parse 'stages.train.cmd' in 'dvc.yaml':              
Cannot interpolate data of type 'list'
```

The expected command is `python train.py --list 'a' 'b' 'c'`

**Comment by pmrowla** [comment]
Related: https://github.com/iterative/dvc/issues/6107

**Comment by daavoo** [comment]
@TheFirstMe You can workaround this with https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dict-unpacking if you wrap the list inside a dict:

```yaml
dict:
    list: ['a', 'b', 'c']
```

```
stages:
    train:
        cmd: python train.py ${dict}
```

**Comment by CarMiranda** [comment]
@TheFirstMe does something like the following serves your purpose? 
```yaml
# params.yaml
base:
  loglevel: INFO
  list:
    list: ['a', 'b', 'c']
  random-key: 0.1

stage1:
  param1: 0.1
  param2: 0.2
  param3: 0.3

stage2:
  param1: 0.3
  param2: 0.2
```
```yaml
# dvc.yaml
stages:
  stage1:
    cmd: >-
      python script.py
      ${stage1}
      ${base.list}
      --random-key ${base.random-key}
      --log-level ${base.loglevel}
    deps:
      - script.py
  stage2:
    cmd: >-
      python script.py
      ${stage2}
      ${base.list}
      --random-key ${base.random-key}
      --log-level ${base.loglevel}
    deps:
      - script.py
```

As you can see, the common parameters remain under the `base` key, but `list` is replaced by `list: list: [...]` which allows to interpolate in the common manner. However, in this way, one cannot expect to interpolate `${base}`, which is why the other parameters are specified in the commands.

If you really do not want to write the other parameters, you can simply group them in another key, within the same (or another)  dictionary:
```yaml
base:
  list:
    list: ['a', 'b', 'c']
  others:
    log-level: INFO
    random-key: 0.1

# ...
```
```yaml
stages:
  stage1:
    cmd: >-
      python script.py
      ${stage1}
      ${base.list}
      ${base.others}
    deps:
      - script.py
# ...
```

This is a workaround, I would expect for plain list interpolation to land some time in the (near?) future.
