### ISSUE TITLE
dvc add and dvc repro cannot detect appended lines in a large file

### ISSUE THREAD

**Issue by junwang-wish** [iterative/dvc#8390]
Somehow, `dvc add` and `dvc repro` cannot detect changes to a large json list file (append a few lines to the bottom of a json list file for example)
1. We have a large json list file `large.jsonl` that was added to `dvc` through `dvc add large.jsonl`, thus resulting in a `large.jsonl.dvc` that looks like 
```
outs:
- md5: 32f6ce6669716694af9d6db23b00a89e
  size: 61951730
  path: large.jsonl
```
2. Now, we append some lines to the bottom of it and run `dvc add large.jsonl`, one would expect the file md5 hash of `large.jsonl.dvc` to change but no... Only size changes:
```
outs:
- md5: 32f6ce6669716694af9d6db23b00a89e
  size: 78951730
  path: large.jsonl
```
3. Now if we do `dvc push` or `dvc repro`: updated `large.jsonl` don't get pushed to remote, and pipelines that depend on `large.jsonl` don't run, because the md5 of `large.jsonl.dvc` didn't change

On the other hand if in Step 2., we prepend the lines to the top of `large.jsonl` instead of append lines to its bottom. the md5 hash of `large.jsonl.dvc` would change, and `dvc push` would push the updated file to remote, and `dvc repro` would run pipelines that depend on `large.jsonl`. 

This behavior is not intuitive. Is there away to fix it?
