### ISSUE TITLE
Problems with `dvc-pull` using ssh when running inside container

### ISSUE THREAD

**Issue by tadejsv** [iterative/dvc#8438]
I am experiencing problems when trying to run `dvc pull` that pull from a private repo (and uses SSH for authentication) when running inside a container in github actions. This issue is similar to https://github.com/iterative/dvc/issues/7702, but not exactly the same, as this only occurs when running inside the container.

How to reproduce:
1. Create a repo with DVC
2. Import a file from a private repo to it
3. Create a deploy key for the private repo, add it as a secret called `DEPLOY_KEY` to current repo
4. Add this workflow and create a PR to run it
```yaml
name: CI
on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v3
      - run: pip install dvc==2.30.0 
      - run: apt update && apt install git openssh-client

      - uses: webfactory/ssh-agent@v0.5.4
        name: Apply SSH deploy key for private repo
        with:
            ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # This will work
      - run: git clone git@github.com:tadejsv/private-repo.git

      # But this will not :(
      - name: Pull DVC artifacts
        run: dvc pull -v

```
Error you get would be
```
ERROR: failed to pull data from the cloud - Failed to clone repo 'git@github.com:tadejsv/private-repo' to '/tmp/tmpfb5gmsmqdvc-clone'
```

**Comment by tadejsv** [comment]
I did some more research - this workflows seems to work.
```yaml
name: CI
on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v3
      - run: pip install dvc==2.30.0 
      - run: apt update && apt install git openssh-client

      - shell:  bash -e {0}
        run: |
          id
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
          mkdir -p -m 0700 /root/.ssh && ssh-keyscan github.com > /root/.ssh/known_hosts
          ssh-keyscan github.com >> /root/.ssh/known_hosts
      # - uses: webfactory/ssh-agent@v0.5.4
      #   name: Apply SSH deploy key for private repo
      #   with:
      #       ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # This will work
      - run: git clone git@github.com:tadejsv/private-repo.git

      # But this will not :(
      - name: Pull DVC artifacts
        run: dvc pull -v
```

What I've discovered is that `$HOME` and the home dir specified in `/etc/passwd` are not the same in container. This is because GH Actions sets the env var `HOME=/github/home` in the container, but the "natural" home dir depends on the user inside the container (which, in this case, is `root`). SSH seems to look for config not inside `$HOME/.ssh`, but inside the "true" home dir - in this case `/root/.ssh`.

But this still does not answer why in the original workflow `git clone` worked, but `dvc pull` did not. Probably this actually depends now more on the specifics of what `webfactory/ssh-agent` does, than anything else. Still, since this is the "standard" way to set up SSH in GH workflows, you might want to look into it.

If not, feel free to close this issue.
