### ISSUE TITLE
import-url: `--version-aware` does not apply to directories

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#8506]
One more thing: `--version-aware` doesn't seem to do anything for directories. I would expect it to include the list of all files and the `version_id` for each inside the `.dvc` file.

If I do `dvc import-url --version-aware s3://dave-sandbox-versioning/example-cloud-remote/data/`, the `data.dvc` file looks like:

```
md5: 5e46b5ab89ac35532c82915752d2ddbe
frozen: true
deps:
- md5: 33ab906cdada8d288429ab9884d8e08b.dir
  size: 21
  nfiles: 3
  path: s3://dave-sandbox-versioning/example-cloud-remote/data/
outs:
- md5: 1fff39c58ffb2a046fb72f52eaff02db.dir
  size: 21
  nfiles: 3
  path: data
```

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/8249#issuecomment-1289117493_
