### ISSUE TITLE
Cannot plot with windows paths syntax

### ISSUE THREAD

**Issue by SamuelAnsel** [iterative/dvc#8689]
# Bug Report

## Windows path syntax

I work on windows and tried to display some plots, here is my `dvc.yaml` file :

```stages:
  train:
    cmd: python .\src\train.py
    deps:
    - .\data\train.csv
    params:
    - train.batch_size
    - train.seed
    outs:
    - .\train_out
    metrics:
    - .\dvclive\metrics.json:
        cache: false
    plots:
    - .\dvclive\plots\metrics\train_loss.tsv:
        cache: false
        x: step
        y: train_loss
    - .\dvclive\plots\metrics\train_acc.tsv:
        cache: false
        x: step
        y: train_acc
```
Notice that my paths have a Windows syntax here.

If I run `dvc plots show -v --json` it outputs :

```
{
  ".\\dvclive\\plots\\metrics\\train_loss.tsv": [],
  ".\\dvclive\\plots\\metrics\\train_acc.tsv": []
}
2022-12-13 13:48:49,678 DEBUG: Analytics is enabled.
2022-12-13 13:48:49,681 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\sansel\\AppData\\Local\\Temp\\tmpleidc5tk']'
2022-12-13 13:48:49,684 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\sansel\\AppData\\Local\\Temp\\tmpleidc5tk']'
```
Then if I replace `\` with `/` in my paths like so :

```
stages:
  train:
    cmd: python ./src/train.py
    deps:
    - ./data/train.csv
    params:
    - train.batch_size
    - train.seed
    outs:
    - train_out
    metrics:
    - ./dvclive/metrics.json:
        cache: false
    plots:
    - ./dvclive/plots/metrics/train_loss.tsv:
        cache: false
        x: step
        y: train_loss
    - ./dvclive/plots/metrics/train_acc.tsv:
        cache: false
        x: step
        y: train_acc
```
Now DVC is able to correctly display plots.

### Expected

You would expect Windows path syntax to work on Windows

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

```
DVC version: 2.34.0 (exe)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.19044-SP0
Subprojects:

Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git

You are using dvc version 2.34.0; however, version 2.37.0 is available.
To upgrade, uninstall dvc and reinstall from https://dvc.org.
```

**Comment by blakeNaccarato** [comment]
See my [original comment](https://github.com/iterative/dvc/issues/2059#issuecomment-1308197586) where I provided a repro for a related issue. I have since renamed that repro to reflect its relationship to the current issue number 8689. Here's that [repro](https://github.com/blakeNaccarato/iterative-dvc-8689) again. It breaks a plot when there's a `\` in the path. The plot `path\fail.png` doesn't show up in rendered HTML of `dvc plots show`, while `path/pass.png` does. The same goes for the plot rendering in the DVC VSCode extension. In [fix-offending-plot](https://github.com/blakeNaccarato/iterative-dvc-8689/tree/fix-offending-plot) the `\` is swapped for `/`, then in [remove-offending-plot](https://github.com/blakeNaccarato/iterative-dvc-8689/tree/remove-offending-plot) the offending plot is commented out of `dvc.yaml`. Each branch has the output of `dvc plots show` committed as well.

It is not an exhaustive reproduction for this now broader issue, but represents one way in which Windows paths can mess things up.

### Workaround

Here's an updated, generalized workaround since I last commented over in the other issue. Supply all paths in `params.yaml` under a key of your choosing (e.g. `dirs`), then inject them into `dvc.yaml` using DVC's built-in [templating support](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#templating) (e.g. `${dirs.<...>}`). Now you can watch your `params.yaml` for changes and always run a script like the `repl_path_in_params.py` below to normalize any `\` to `/` _before_ those parameters get injected into `dvc.yaml`. It's a bit of a bandaid solution, but it makes sure your paths are acceptable by DVC.

See below for an example normalizing script, parameters file, and `dvc.yaml` file.

<details><summary>repl_path_in_params.py</summary>

```Python
"""Replace Windows path separators with POSIX paths in configuration file."""

from pathlib import Path

from ruamel.yaml import YAML

PARAMS_FILE = "params.yaml"
DIRS_KEY = "dirs"

yaml = YAML()
yaml.indent(offset=2)


def main():
    params = yaml.load(PARAMS_FILE)
    params[DIRS_KEY] = repl_path(params[DIRS_KEY])
    yaml.dump(params, PARAMS_FILE)


def repl_path(dirs_dict: dict[str, Path]):
    """Replace Windows path separator with POSIX separator."""
    return {k: str(v).replace("\\", "/") for k, v in dirs_dict.items()}


if __name__ == "__main__":
    main()

```

</details>

<details><summary>params.yaml</summary>

```YAML
dirs:
  plot_new_fit_0: data/metrics/plots/new_fit_0.png
  plot_new_fit_1: data/metrics/plots/new_fit_1.png
  plot_new_fit_2: data/metrics/plots/new_fit_2.png
  file_pipeline_metrics: data/metrics/tables/pipeline_metrics.json
other_params:
  ...
```

</details>

</details>

<details><summary>dvc.yaml</summary>

```YAML
  ...
  metrics:
    cmd: "<metrics_cmd>"
    deps:
      - ...
    metrics:
      - "${dirs.file_pipeline_metrics}"
    plots:
      - "${dirs.plot_new_fit_0}"
      - "${dirs.plot_new_fit_1}"
      - "${dirs.plot_new_fit_2}"
    params:
      - ...
  ...
```

</details>
