### ISSUE TITLE
Support of relative paths as repo url in dvc files

### ISSUE THREAD

**Issue by Luux** [iterative/dvc#8692]
I want to setup experiment branches which refer to some data commits within the same repository, but in a distinct branch. Within my experiment branch, I have some subdirectories `subdirA/subdirB` which include the dvc files in question. Using `dvc import`, I'm able to refer to the repo origin using relative paths:

```
md5: (md5)
frozen: true
deps:
- path: data/mydata/someimages
  repo:
    url: ../../
    rev: data
    rev_lock: (rev_lock)
outs:
- md5: (md5).dir
  size: 500426099
  nfiles: 4062
  path: images
```

This works fine when running `dvc pull` from within `(root)/subdirA/subdirB`. However, running `dvc pull` from the root directory fails as dvc tries to traverse to  `(root)/../../` instead of `(root)/subdirA/subdirB/../../`

Vice versa, if I use `.` as url, it works from `(root)`, but not inside the subdirectory anymore.

Another idea would be to use the remote url from the repository, however this comes with some disadvantages: you need to have access to the remote and the referenced commit has to be available there.
You could also place the dvc files directly inside `(root)` and just point the outs to the subdirectories. This however is not as clean when it comes to file organization.

dvc already implemented the `dvc root` command, but I didn't come across a possiblity to use it as placeholder inside a dvc file yet. Is there a better way to achieve this or did I miss something?

**Comment by tupokraju** [comment]
Why don't just use the dvc root command in the repo field of the dvc.yaml file to specify the root directory of the repository as the base path for the data/mydata/someimages directory. This would allow you to use relative paths to reference the data commit within the same repository, regardless of the current working directory.

**Comment by Luux** [comment]
> Why don't just use the dvc root command in the repo field of the dvc.yaml file to specify the root directory of the repository as the base path for the data/mydata/someimages directory. This would allow you to use relative paths to reference the data commit within the same repository, regardless of the current working directory.

I'm not utilizing a dvc.yaml here, only .dvc files. Therefore I cannot run commands inside.

**Comment by rlamy** [comment]
Have you tried using a top-level [`wdir` parameter](https://dvc.org/doc/user-guide/project-structure/dvc-files#specification)?

**Comment by Luux** [comment]
> Have you tried using a top-level [`wdir` parameter](https://dvc.org/doc/user-guide/project-structure/dvc-files#specification)?

Yes, I also tried the following:

`(base)/local/path/images.yaml`
```
md5: (md5)
frozen: true
wdir: ../../../
deps:
- path: path/to/images
  repo:
    url: .
    rev: data
    rev_lock: (rev_lock)
outs:
- md5: (md5).dir
  size: (size)
  nfiles: (nfiles)
  path: `(base)/local/path/images.yaml`
```

However, this also results in `dvc pull` working when running it from `(base)/local/path/images.yaml`, but if I run `dvc pull` from `(base)`, I get `ERROR: failed to pull data from the cloud - Failed to clone repo '.' to '/tmp/tmpy9eulpq8dvc-clone'`
