### ISSUE TITLE
Cloud versioning: Track existing cloud dataset and push updates to it

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8704]
Related to https://github.com/iterative/dvc/issues/8382. The current UX is awkward if you want to track an existing cloud dataset and later push updates to it. You have to do something like:

```
$ dvc remote add my_dataset s3://bucket/path/to/dataset
$ dvc remote modify my_dataset worktree true
$ mkdir my_dataset
$ dvc add my_dataset
$ dvc update my_dataset
```

Edit: replaced `dvc pull` with `dvc update my_dataset`.

`dvc import-url --worktree s3://bucket/path/to/dataset my_dataset` could do the workflow above in a single command. The remote config could be stored either in the .dvc file or in config files. This would enable an easy workflow to update a cloud dataset like:

```
$ dvc import-url --worktree s3://bucket/path/to/dataset my_dataset
# Modify
$ rm my_dataset/old_files*
$ cp -R new_files/* my_dataset
# Track changes
$ dvc add/commit my_dataset
$ dvc push
```

**Comment by dberenbaum** [comment]
@dtrifiro Sorry for changing product reqs here, but thinking about this more, I lean towards it making more sense in `dvc add --worktree` than `dvc import-url --worktree`. It's a less confusing UX since the commands after downloading the dataset (`add`, `push`) are more typical for `dvc add`.

Also, `import-url` normally assumes both source `deps` and `outs`, and here there are really no `deps`. The final output should be something like this:

```yaml
outs:
- md5: 56db666947dc82019468d7fa5c25d5b4.dir
  size: 59789011
  nfiles: 2605
  path: cats-dogs
  files:
  - size: 34315
    etag: 10d2a131081a3095726c5721ed31c21f
    md5: 10d2a131081a3095726c5721ed31c21f
    relpath: data/train/cats/cat.10.jpg
    remote: myremote
  - size: 28377
    etag: 0f2bfe74e9c363064087d0cd8a322106
    md5: 0f2bfe74e9c363064087d0cd8a322106
    relpath: data/train/cats/cat.100.jpg
    remote: myremote
```

Compare that to `import-url` outputs, which would be like:

```yaml
md5: bc6502513858d60c8273554d99917133
frozen: true
deps:
- md5: 32666fe69170a00790117e76b90e42e2.dir
  size: 59789011
  nfiles: 2605
  path: s3://dave-sandbox-versioning/test/worktree/cats-dogs
  files:
  - size: 34315
    version_id: svPEUz3wOVBye5DMfyXkpz7CB2r.DpfW
    etag: 10d2a131081a3095726c5721ed31c21f
    relpath: data/train/cats/cat.10.jpg
  - size: 28377
    version_id: d3zndjpU2vUZZ.oSqQ1FKb24jDPh_pcG
    etag: 0f2bfe74e9c363064087d0cd8a322106
    relpath: data/train/cats/cat.100.jpg
...
md5: bc6502513858d60c8273554d99917133
frozen: true
deps:
- md5: 32666fe69170a00790117e76b90e42e2.dir
  size: 59789011
  nfiles: 2605
  path: s3://dave-sandbox-versioning/test/worktree/cats-dogs
  files:
  - size: 34315
    version_id: svPEUz3wOVBye5DMfyXkpz7CB2r.DpfW
    etag: 10d2a131081a3095726c5721ed31c21f
    relpath: data/train/cats/cat.10.jpg
  - size: 28377
    version_id: d3zndjpU2vUZZ.oSqQ1FKb24jDPh_pcG
    etag: 0f2bfe74e9c363064087d0cd8a322106
    relpath: data/train/cats/cat.100.jpg
```
