### ISSUE TITLE
[BUG?] Cached dir file pushed to remote throws error when pulled from remote

### ISSUE THREAD

**Issue by andrethrill** [iterative/dvc#872]
Hi!

I've `dvc add` a directory of raw data, which `.dvc` file is:

```
md5: 40dc65b691c196a0bc68a102c845cb21
outs:
- cache: true
  md5: ec0e6c9d86ca7e7238837f77464b2f61.dir
  metric: false
  path: *******                                                     # this is directory #1
```

After I've run a `dvc run` command (that depends on the directory I showed above) which `.dvc` file is:

```
cmd: python ../../../src/data/*******.py
deps:
- md5: 00ad5d690b0b1e20f7536ad7b9b13e56
  path: ../../../src/data/*******.py
- md5: ec0e6c9d86ca7e7238837f77464b2f61.dir
  path: ../../raw/*******                                                     # this is directory #1
md5: 6d5cc84c0048037818d2022d4caa6824
outs:
- cache: true
  md5: 0e278292ab6d1fe12bbcb890d1003f76.dir
  metric: false
  path: *******                                                                   # this is a directory #2
```
After I've done `dvc push` to S3.

Also, I don't know if this is relevant but I'm using shared cache. (cache location is outside of repo dir)

**The problem**

On a different machine, I've cloned the git repo and then when I do `dvc pull` (from S3) I always get the following errors:

```
Failed to load dir cache '../../******/ec/0e6c9d86ca7e7238837f77464b2f61.dir': [Errno 2] No such file or directory: '******/ec/0e6c9d86ca7e7238837f77464b2f61.dir'
Failed to load dir cache '../../******/0e/278292ab6d1fe12bbcb890d1003f76.dir': [Errno 2] No such file or directory: '******/0e/278292ab6d1fe12bbcb890d1003f76.dir'
(1/26): [##############################] 100% ab985a36268c5fd522e3837ba509bf9d
(2/26): [##############################] 100% 5fcc2be218d299581e7e6eda98471485
(3/26): [##############################] 100% ab7ee23dbafb29fdd9006abf6c0279a4
(4/26): [##############################] 100% ea03c52cf38849e4505288d4d8331f31
(5/26): [##############################] 100% 629389205697cda8caaba595dc07af0c
(6/26): [##############################] 100% 9e11a33bf9e09b6eb8523dd53b4ed9f5
(7/26): [##############################] 100% 2b3ed841e849f223af57c1512c03e88e
(8/26): [##############################] 100% 10e3e0ef98adf6e45b7b4fab507cdf16
(9/26): [##############################] 100% f63931f7e493ee6d16ba6ea0e1fb4dae
(10/26): [##############################] 100% 8dce1da718c77df818261bf627a636fc
(11/26): [##############################] 100% 19b8db23599828aa757c00097d3abe80
(12/26): [##############################] 100% 01775ba2dfb7cd941d2be742c68a1cb3
(13/26): [##############################] 100% 5518bd3663b36d2be860af83f3738faf
(14/26): [##############################] 100% 7d402e8053c0d0af40bafafef4c65864
(15/26): [##############################] 100% bd9193ab817de999b526f01845609ad0
(16/26): [##############################] 100% 304cacd01676e009f08a8bce354dedda
(17/26): [##############################] 100% 72659e880507f87c95146a3ed11f9255
(18/26): [##############################] 100% d70361968ccd4676a1ec87fad4d7dcc6
(19/26): [##############################] 100% d11a29269083bc839bff4aad3509f4c4
(20/26): [##############################] 100% 6792e382941dbb18c89fa57ed7c4a1fc
(21/26): [##############################] 100% d461cb099824287a77e6f369b34c6aaf
(22/26): [##############################] 100% 5b63fd9a7f9193c113085e09677fce5a
(23/26): [##############################] 100% deb3f81a2c3d7ccd3fb98890ffbc8e99
(24/26): [##############################] 100% 7dbc7f9aa5f21a13d72def4f4f3696e3
(25/26): [##############################] 100% 1c9144c607ecb2baf72f2fb5dbd70b0b
(26/26): [##############################] 100% e343f5915e3ca1dae351011a8cd767f4

```

As you can see, the remaining cached files which are not `.dir` download smoothly.

After I run `dvc checkout` no error is thrown. And when I run `dvc status` it always outputs that the .dvc files related to the two .dir files have changed:

```
***.dvc
        outs
                changed:  data/raw/****                                                       # this is directory #1
***.dvc
        deps
                changed:  data/raw/****                                                       # this is directory #1
        outs
                changed:  data/processed/****                                             # this is directory #2
```

This seems like a bug or I'm being silly and doing something wrong. Is this a known behaviour?
