### ISSUE TITLE
dvc repro: Tuples in parameters are always marked as modified

### ISSUE THREAD

**Issue by janrito** [iterative/dvc#8803]
# Bug Report

## Description

When tuples are used in parameters, dvc always marks them as modified.

```sh
dvc status
```
outputs
```yaml
train_model:
  changed deps:
    model/parameters.py:    
      modified: NGRAM_VECTORIZER_RANGE
```

regardless of whether `NGRAM_VECTORIZER_RANGE` has been changed
