### ISSUE TITLE
`dvc stage add`: configure dependencies to Nodes without outs

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#8881]
## Motivation

I have the following scenario. I've written a Node (using [ZnTrack](https://github.com/zincware/ZnTrack)) that does e.g. data selection

```python
class RandomSelection(Node):
	samples: int = zn.params()  # adds to params.yaml
	data = dvc.deps("data.txt")
	selected = dvc.outs("selected.txt")

	def run(self):
	   self.selected = self.select(self.data)
		
	def select(self, data): ... # using self.samples
```
which creates the following `dvc.yaml`

```yaml
stages:
    RandomSelection:
        cmd: zntrack run RandomSelection --name=RandomSelection
        deps:
        - data.txt
        outs:
        - selected.txt
        params:
        - RandomSelection
```

I also want to use the `RandomSelection.select()` in some other Node. E.g. in an on-the-fly learning where I generate a lot of data and want to select from it.

```python
class OnTheFly(Node):
	selection_method = zn.Node(RandomSelection(samples=10))
	steps: int = zn.params()
	data = dvc.deps("data.txt")
	selected = dvc.outs("selected.txt")

	def run(self):
	   for idx in range(self.steps):
	      data = ...
	      selected = 	self.selection_method.select(data)
	   self.selected = ...
```

This will create the following `dvc.yaml` where `OnTheFly-RandomSelection` does not have any outputs, because they are "moved" to the `OnTheFly` Node. 
```yaml
stages:
   OnTheFly:
      cmd: zntrack run OnTheFly --name=OnTheFly
      deps:
        - data.txt
      outs:
        - selected.txt
    OnTheFly-RandomSelection:
        cmd: zntrack run RandomSelection --name=RandomSelection
        params:
        - RandomSelection
```

My issue is, that `OnTheFly-RandomSelection` still has parameters in `params.yaml`. I prefer it like this, because `OnTheFly` could have a lot of parameters or depend on a lot of other Nodes and this makes it easier to see in `params.yaml`. But unfortunately, `OnTheFly` can not depend on `OnTheFly-RandomSelection` because it doesn't produce any outputs, if used inside the other Node.

My current solution is, to add a dummy output to `OnTheFly-RandomSelection`. 

## Feature Request
I suggest an addition to `dvc.yaml` that allows to define the order of execution / dependencies on stages, without files.

It could be under a dedicated key `deps_stages: ` or using a key like the following together with `dvc stage add <name> --deps-stage <other stage>`
```yaml
stages:
   OnTheFly:
      deps:
      - OnTheFly-RandomSelection:
         stage: true
      ...
   OnTheFly-RandomSelection:
      ...
```

I see a few small difficulties with this:
1. one could define dependencies that contradict other dependencies. This would require a check just like it is done with  file deps.
2. It could be confusing, so this should probably be treated an advanced feature.
3. It is not possible to have `OnTheFly-RandomSelection` as a file dependency *and* as a stage dependency.

**Comment by daavoo** [comment]
Just throwing ideas here. 

I like `needs` as in [GitHub workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds):

```yaml
stages:
   OnTheFly:
      needs: OnTheFly-RandomSelection
      ...
   OnTheFly-RandomSelection:
```

I think would be cleaner from a UX perspective but, most likely, from an implementation perspective too.

**Comment by alex000kim** [comment]
I have a similar scenario where there's a data verification step before the model training step (to ensure that the data is in the right format). E.g.
```yaml
stages:
...
  data_verification:
    cmd: python src/data_verification.py
    deps:
      - src/data_verification.py
      - data/
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/
    outs:
      - model
```

I'd like for the `train` stage to explicitly depend on the `data_verification` stage without having to generate a dummy output.
