### ISSUE TITLE
dvc.yaml: `foreach` dictionary does not accept numbers as keys

### ISSUE THREAD

**Issue by alkatar21** [iterative/dvc#8903]
# Bug Report

## Description

`foreach` in a stage has multiple options to pass arguments to iterate on. The third example in 
https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#foreach-stages uses dictionarys. However, if you replace `uk` and `us` by `2021` and `2022` it fails, because they are interpreted as int.

### Reproduce
1. dvc init
1. add the following `dvc.yaml`:
```yaml
stages:
  build:
    foreach:
      2021:
        epochs: 3
        thresh: 10
      2022:
        epochs: 10
        thresh: 15
    do:
      cmd: python train.py '${key}' ${item.epochs} ${item.thresh}
      outs:
        - model-${key}.hdfs
```
3. Run for example `dvc status` or any other command that visits the file:
  `ERROR: Stage 'build@2021' not found inside 'dvc.yaml' file`

### Expected

I would expect that it is possible to use numbers as keys in dicts.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.34.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-137-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.5
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2022.6.0)
Cache types: symlink
Cache directory: ext4 on /dev/sdc1
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

Additional context: (@dtrifiro) https://discord.com/channels/485586884165107732/485596304961962003/1068934989795827742
