### ISSUE TITLE
Tracking of explicitly ignored files in directory dependencies

### ISSUE THREAD

**Issue by severinsimmler** [iterative/dvc#8952]
Assuming one output entry depends on a directory, the lock file might look like:
```yaml
  foo:
    cmd: python foo.py
    deps:
    - path: foo/bar
      md5: 48d04b028c7974f63d3e88a3e2719dea.dir
      size: 45922
      nfiles: 25
    outs:
    - path: foo/baz.bin
      md5: 8c4567caf14d480fb3ece31c062e8c08
      size: 68487
```

Is it expected behavior that if I add a file to `foo/bar` which is explicitly ignored via `.dvcignore`, the count `nfiles` gets incremented and thus DVC tells me that stage is outdated?

**Output of `dvc doctor`:**

```console
DVC version: 2.43.2 (pip)
-------------------------
Platform: Python 3.10.6 on Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.37.3
        dvc_objects = 0.19.1
        dvc_render = 0.1.0
        dvc_task = 0.1.11
        dvclive = 2.0.0
        scmrepo = 0.1.7
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.1.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: zfs on rpool/USERDATA/severin_r7xzsy
Caches: local
Remotes: s3
Workspace directory: zfs on rpool/USERDATA/severin_r7xzsy
Repo: dvc, git
```
