### ISSUE TITLE
exp run: showing unhelpful error message for invalid pipeline

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8974]
Background in https://github.com/iterative/dvc/issues/8973.

Here is the setup from that issue:

```python
# train.py
from random import random

from dvclive import Live

NUM_EPOCHS = 10


with Live(save_dvc_exp=True) as live:

    live.log_param("NUM_EPOCHS", NUM_EPOCHS)

    for epoch in range(NUM_EPOCHS):
        step = live.read_step()
        live.log_metric("metric", random())
        live.log_param("my_step", step)
        live.next_step()
```

```yaml
# dvc.yaml
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    outs:
      - dvclive:
          checkpoint: true
    metrics:
      - dvclive/metrics.json
    plots:
      - dvclive/plots
```

When running `dvc exp run`, the error message looks like:

<img width="978" alt="216764996-eb2efe78-b5d0-4c47-b79e-1053280e322f" src="https://user-images.githubusercontent.com/2308172/217090450-6e893951-64b2-4264-8dc8-ddb142f3dfd5.png">

# Expected

`dvc repro` for a similar setup gives an error like:

```bash
ERROR: The output paths:
'dvclive'('train')
'dvclive/metrics.json'('train')
overlap and are thus in the same tracked directory.
To keep reproducibility, outputs should be in separate tracked directories or tracked individually.
```

The same error from `dvc repro` should be shown in `dvc exp run`.
