### ISSUE TITLE
`repro --downstream` seems to ignore dependencies in for loops

### ISSUE THREAD

**Issue by Stockemer** [iterative/dvc#9367]
We have the following pipeline structure:

```
stages:
  feature_extraction:
    foreach: ${list_of_features} 
    do:
      cmd: python feature.py --feature ${item.name}
      deps:
        - some_data
        - feature.py
      params:
        - list_of_features 
      outs:
        - folder/${item.name}
  train:
    cmd: python train.py
    deps:
      - folder
      - train.py
    outs:
      - model

```
If we run `dvc repro`, everything is fine.
If we run `dvc repro --downstream feature_extraction` it runs one of the feature_extraction stages from the for loop, then the train stage, then the other stages in the for loop. 
As our train script depends on all the features, it will fail. 

Did we miss something / use `--downstream` wrong or does it mess up the dependencies in the for loop?
