### ISSUE TITLE
dvc.yaml: ruamel.yaml 0.17.22 oddly splits long strings

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9397]
ruamel.yaml 0.17.22:
```
stages:
  copy-first-line:
    cmd: python
      /private/var/folders/fn/lxr30v5j0jldz5zbsb0jx_pr0000gn/T/pytest-of-efiop/pytest-10/test_cmd_changes_other_orders_0/head.py  foo  bar  foobar
    deps:
    - bar
    - foo
    - foobar
    outs:
    - bar-1
    - foo-1
    - foobar-1
```
vs old:
```
stages:
  copy-first-line:
    cmd: python  /private/var/folders/fn/lxr30v5j0jldz5zbsb0jx_pr0000gn/T/pytest-of-efiop/pytest-12/test_cmd_changes_other_orders_0/head.py  foo  bar  foobar
    deps:
    - bar
    - foo
    - foobar
    outs:
    - bar-1
    - foo-1
    - foobar-1
```

Which is causing our CI to fail on tests/func/test_lockfile.py::test_cmd_changes_other_orders_are_preserved
