### ISSUE TITLE
parsing: improve error message for unsupported types for local variables

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9503]
```yaml
stages:
  download-video-data:
    foreach:
      - 2023-05-09
    do:
      desc: |-
        Downloading video data from ${item}
      outs:
        - out.txt
      cmd:
        - echo ${item} >> out.txt
```

If you run `dvc repro` raises: `ERROR: unexpected error - Unsupported value of type 'date' in '<local>:item'`.
