### ISSUE TITLE
drop external outputs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9531]
Drop current implementation of external outputs as part of #7093.

**Comment by dberenbaum** [comment]
When dropping external outputs, can we continue to support `--outs-no-cache` with external paths, and can we allow them without the `--external` flag (which we can drop)?

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/7093#issuecomment-1567028789_

**Comment by dberenbaum** [comment]
Hi, I posted this [question regarding external outputs on Discord](https://discord.com/channels/485586884165107732/485596304961962003/1111663148777340989) and am moving the discussion here as suggested.

I currently moved a larger scale data analysis from our local server to run in AWS using a Ray Cluster (https://www.ray.io/). The different steps are implemented as individual Ray jobs which are compiled into a reproducible pipeline with DVC using a `dvc.yaml`. Because the execution of jobs / stages is in AWS, and because the size of the data is too large to store locally, the inputs and outputs of each stage are external AWS S3 URIs. As part of this I run into one or the other issue (stage output always "not in cache" even right after `dvc commit -f` was run; error to run stage the first time because S3 URI prefix does not exist) indicating some bug in DVC in regards to external outputs (still need to file GitHub issues for these).

However, looking at this roadmap for the next major release version 3.0, I can see that there is a To-Do item that reads "drop external outputs". So my more immediately pressing questions are:
- Will AWS S3 URIs for stage inputs and outputs no longer be supported from DVC version 3.0 onwards?
- What is the recommendation for being able to run large reproducible data processing in the cloud (AWS)? All stage outputs should only live in AWS S3. Stage scripts stream the data directly from/to this remote storage.

An example `dvc.yaml` would look something like:
```
vars:
- s3_uri_prefix: s3://bucket/prefix
stages:
  stage_1:
    cmd: ray job submit --working-dir . -- python stage_1.py --output ${s3_uri_prefix}/stage_1
    deps:
    - stage_1.py
    outs:
    - ${s3_prefix}/stage_1:
        push: false
  stage_2:
    cmd: ray job submit --working-dir . -- python stage_2.py --input ${s3_uri_prefix}/stage_1 --output ${s3_uri_prefix}/stage_2
    deps:
    - stage_2.py
    - ${s3_uri_prefix}/stage_1
    outs:
    - ${s3_uri_prefix}/stage_2:
        push: false
```

I'd appreciate any pointers as to how DVC would still fit into the picture here.

_Originally posted by @aschuh-hf in https://github.com/iterative/dvc/issues/7093#issuecomment-1572024046_
