### ISSUE TITLE
dvc exp pull/list/push: Authentication failed for origin when running with CML

### ISSUE THREAD

**Issue by kpetersen-hf** [iterative/dvc#9779]
# Bug Report

## Description

When using `dvc exp pull origin <my_experiment>` as part of a github actions workflow (using DVC 3.9.1), I obtain a git authorization error (see attached). I can pull the experiment on my local machine without problems, and within github actions commands like `dvc pull  run` perfectly fine.

### Reproduce
Setup a repo with a dvc.yaml file and add the following github workflow (adapt AWS permission).

```
name: CML Toy Workflow

on: [push]
 
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: // MY AWS ACCESS TOKEN
          aws-region: us-east-1 
      - uses: iterative/setup-cml@v1
      - name: Install environment
        run: |
          pip install -r requirements.txt
      - name: Git fetch
        run: |
          git fetch origin -v
      - name: Run experiment
        run: |
          dvc exp run -n lr
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |                    
          git fetch --prune
          dvc exp list origin -n 20
          cml comment create report.md
```
### Expected

No authentication error when running `dvc exp list` as part of GitHub Actions workflow with CML.
