### ISSUE TITLE
DVC not supporting templating for artifacts

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/dvc#9999]
I tried to use the templating artifacts section in dvc.yaml file, but Studio can't parse it and there are not artifact updates in `dvc.lock` (should it be there?)
Example repo: https://github.com/mnrozhkov/monorepo-reusable-pipelines

Here is dvc.yaml example:
```yaml
artifacts:
  pipeline_a_segment_model:
    path: pipeline_a_segment/${target}/${model_dir}/model_pipeline_a_segment_${target}_UPPER.file
    type: model
```
